In [1]:
from os.path import exists

# Prediction interface for Cog ⚙️
# Reference: https://github.com/replicate/cog/blob/main/docs/python.md
from torch.utils.data import Dataset, DataLoader
import clip
import os
import pandas as pd
import pickle
from torch import nn
import numpy as np
import torch
import torch.nn.functional as nnf
import sys
from typing import Tuple, List, Union, Optional
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    AdamW,
    get_linear_schedule_with_warmup,
)
from transformers import AutoConfig, AutoTokenizer, Gemma2ForCausalLM
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, TaskType, get_peft_model
import PIL.Image
tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")

In [2]:
tokenizer.vocab_size

131072

In [3]:
from transformers import AutoProcessor, AutoModelForVisualQuestionAnswering
from PIL import Image
processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
model = AutoModelForVisualQuestionAnswering.from_pretrained("Salesforce/blip2-opt-2.7b")

def imageExtractionVQA(image_data, question):
    image_data = Image.open(image_data).convert('RGB')
    inputs = processor(image=image_data, question='Describe the image. Answer:', return_tensors="pt")
    outputs = model(**inputs)
    return outputs

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:  65%|######4   | 6.46G/10.0G [00:00<?, ?B/s]

C:\Users\user\PycharmProjects\pythonProject\.venv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\user\.cache\huggingface\hub\models--Salesforce--blip2-opt-2.7b. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model-00002-of-00002.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/141 [00:00<?, ?B/s]

In [45]:
def imageExtractionVQA(image_data, question):
    image_data = Image.open(image_data).convert('RGB')
    inputs = processor(images=image_data, text=question, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=200)
    return outputs
image = imageExtractionVQA('./test_img.jpg', 'Describe the words: ')
print(processor.batch_decode(image, skip_special_tokens=True)[0])
image = imageExtractionVQA('./test_img.jpg', 'Describe the image in a sentence: ')
print(processor.batch_decode(image, skip_special_tokens=True)[0])

~~thank you for changing my life~~ literally the $5 meal deal

_____ is a cat that is eating a burger and fries

In [57]:
image

tensor([[    2,    10,  7674,     9,    10,   748,  3175,    19,  7716,     8,
            10, 14792,     9, 22391, 50118]])

In [58]:
image = imageExtractionVQA(['./test_img.jpg', './test_img2.jpg'], 'Describe the image. Answer:')
processor.batch_decode(image, skip_special_tokens=True)

AttributeError: 'list' object has no attribute 'read'

In [53]:
image = imageExtractionVQA('./test_img.jpg', 'What is in the image? Answer:')
print(processor.batch_decode(image, skip_special_tokens=True)[0])

 A McDonald's meal deal

In [56]:
image = imageExtractionVQA('./test_img2.jpg', 'Describe the image. Answer:')
print(processor.batch_decode(image, skip_special_tokens=True)[0])

 a painting of a vase with flowers and a bucket of fries

In [49]:
image = imageExtractionVQA('./test_img2.jpg', 'What is in the image? Answer:')
print(processor.batch_decode(image, skip_special_tokens=True)[0])

 a painting of a vase of flowers and a bucket of fries

In [47]:
image = imageExtractionVQA('./test_img2.jpg', 'Describe the words: ')
print(processor.batch_decode(image, skip_special_tokens=True)[0])
image = imageExtractionVQA('./test_img2.jpg', 'Describe the image in a sentence: ')
print(processor.batch_decode(image, skip_special_tokens=True)[0])

KeyboardInterrupt:

In [44]:
image = imageExtractionVQA('./test_img.jpg', 'Describe the words: ')
print(processor.batch_decode(image, skip_special_tokens=True)[0])

~~thank you for changing my life~~ literally the $5 meal deal

In [12]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Salesforce/blip2-opt-2.7b")
print(tokenizer.decode(image['logits'].argmax()))

In [ ]:
! pip install Pillow

In [ ]:
! pip install --upgrade huggingface_hub

In [ ]:
! huggingface-cli login  # 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

In [1]:
import gc
import os
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.optim as optim
from torch.nn import BCEWithLogitsLoss, CrossEntropyLoss, BCELoss
from torch.utils.data import DataLoader
from transformers import AutoConfig, AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
# from local_gemma import LocalGemma2ForCausalLM

from extractor import addImagePath, textExtraction, imageExtraction, textExtractReverse
eps = torch.finfo(torch.bfloat16).eps

C:\Users\user\PycharmProjects\pythonProject\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 1. Load the data and split the data

In [2]:
epochs = 30
batch_size = 10
optimizer_G_lr = 1e-5
optimizer_D_lr = 1e-5

In [3]:
class OxfordDataset(torch.utils.data.Dataset):
    def __init__(self, text, image, funny_score):
        self.text = text
        self.image = image
        self.funny_score = funny_score

    def __len__(self):
        return len(self.text)

    def __getitem__(self, idx):
        imageData = torch.load('../../Oxford_HIC/ImageData/'+ self.image[idx] +'.pt', weights_only=False)
        # all dtype to torch.float16
        imageData = imageData

        return self.text[idx], imageData, self.funny_score[idx]

In [5]:
# if args.img - dir == 'Oxford_HIC':
dirPath = '../Data/Oxford_HIC/CaptionID_oxford_hic_data.csv'
# else:
# dirPath = '../Data/Instagram/Filter_' + 'wendys' + '.csv'
# imgPath = '../Data/Instagram/' + 'wendys' + '_img/'
# load data
data = pd.read_csv(dirPath)
print("shape of data: ", data.shape)
data = data.sample(n=10000, random_state=42, replace=True).reset_index(drop=True)
# frac = 0.05 ==> 5% of the data = 169904
# n = 169920 ==> 72 * 2360 = 169920 (F2G)
# n = 169988 ==> 91 * 1868 = 169988 (G2F)
print("sample of data: ", data.shape)
data.head()

shape of data:  (3398081, 4)
sample of data:  (10000, 4)

,image_id,caption,funny_score,caption_id
0,imgflip_33,TRIES TO ROB BANK; LEAVES MONEY,0.000000,caption2219111
1,imgflip_123,"THAT WAS MY SISTER'S PICTURE, WE LOOK ALMOST I...",0.000041,caption2768308
2,imgflip_34,when a kid asks why 2020 is blank in the text ...,0.000071,caption2229085
3,imgflip_48,OFFICIAL PARDON; PLUTO IS A PLANET AGAIN!,0.000092,caption2356331
4,imgflip_4,Not every single problem is the President's fa...,0.000051,caption1692744

In [6]:
train, test = train_test_split(data, test_size=0.2, random_state=42)
train.head()

,image_id,caption,funny_score,caption_id
9254,bokete_76563,Not particularly!,0.000071,caption988652
1561,imgflip_1,GAMERS; FALL GUYS; AMONG US,0.000031,caption1589590
1670,imgflip_463,FINLAND 100 YEARS? 100 YEARS OF INDEPENDENCE I...,0.000010,caption3006317
6087,bokete_56921,That's him! That's him! That's him!,0.000031,caption737464
6669,bokete_9678,"I'm like, ""What is this big?""",0.000031,caption114457

In [ ]:
train, test = train_test_split(data, test_size=0.2, random_state=42)
train_text = train['caption'].tolist()
train_image = train['image_id'].tolist()
train_funny_score = train['funny_score'].tolist()
test_text = test['caption'].tolist()
test_image = test['image_id'].tolist()
test_funny_score = test['funny_score'].tolist()

train_dataset = OxfordDataset(train_text, train_image, train_funny_score)
test_dataset = OxfordDataset(test_text, test_image, test_funny_score)
# train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, num_workers=20)
# test_loader = DataLoader(test_dataset, batch_size=128, shuffle=True, num_workers=20)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=20, pin_memory=True, drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True, num_workers=20, pin_memory=True, drop_last=True)

In [ ]:
dataL = iter(train_loader)
text, imgs, funny_score = next(dataL)
# print("shape of text: ", text.shape)
# print("shape of image: ", imgs.shape)
print("shape of funny_score: ", funny_score.shape)

In [ ]:
print(text)

# 2. Load Gemma

In [ ]:
### 官方的Gemma #########################################################################################
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-27b-it")
gemma = AutoModelForCausalLM.from_pretrained("google/gemma-2-27b-it", device_map="auto", torch_dtype=torch.bfloat16)
# gemma = LocalGemma2ForCausalLM.from_pretrained("google/gemma-2-2b-it", preset="auto", torch_dtype=torch.bfloat16)
gemmaConfig =  AutoConfig.from_pretrained('google/gemma-2-27b-it')
########################################################################################################

In [7]:
# quantization_config = BitsAndBytesConfig(load_in_4bit=True)
quantization_config = BitsAndBytesConfig(load_in_8bit=True)

gemma = AutoModelForCausalLM.from_pretrained(
    "google/gemma-2-2b-it",
    quantization_config=quantization_config,
)

ImportError: Using `bitsandbytes` 8-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`

In [8]:
gemma

Gemma2ForCausalLM(
  (model): Gemma2Model(
    (embed_tokens): Embedding(256000, 2304, padding_idx=0)
    (layers): ModuleList(
      (0-25): 26 x Gemma2DecoderLayer(
        (self_attn): Gemma2Attention(
          (q_proj): Linear(in_features=2304, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2304, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2304, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2304, bias=False)
          (rotary_emb): Gemma2RotaryEmbedding()
        )
        (mlp): Gemma2MLP(
          (gate_proj): Linear(in_features=2304, out_features=9216, bias=False)
          (up_proj): Linear(in_features=2304, out_features=9216, bias=False)
          (down_proj): Linear(in_features=9216, out_features=2304, bias=False)
          (act_fn): PytorchGELUTanh()
        )
        (input_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
        (pre_feedforward_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
        (post_feedforward_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
        (post_attention_layernorm): Gemma2RMSNorm((2304,), eps=1e-06)
      )
    )
    (norm): Gemma2RMSNorm((2304,), eps=1e-06)
  )
  (lm_head): Linear(in_features=2304, out_features=256000, bias=False)
)

# 3. Generator

In [9]:
class self_multi(nn.Module):
    def __init__(self):
        super(self_multi, self).__init__()
        # self attention
        self.selfAttentionMultihead = nn.MultiheadAttention(768, 1)
        self.selfAttentionLayerNorm = nn.LayerNorm(768, eps=eps)
        self.selfAttentionLinear1 = nn.Linear(768, 768)
        self.selfAttentionRelu = nn.ReLU()
        self.selfAttentionLinear2 = nn.Linear(768, 768)
        self.selfAttentionLayerNorm2 = nn.LayerNorm(768, eps=eps)

        # multihead attention
        self.multiheadAttentionMultihead = nn.MultiheadAttention(768, 8)
        self.multiheadAttentionLinear1 = nn.Linear(768, 768)
        self.multiheadAttentionRelu = nn.ReLU()
        self.multiheadAttentionLinear2 = nn.Linear(768, 768)
        self.multiheadAttentionLayerNorm = nn.LayerNorm(768, eps=eps)

    def forward(self, image, text):
        # self attention module
        self_out = self.selfAttentionMultihead(image, image, image)[0]
        self_out = self.selfAttentionLinear1(self_out)
        self_out = self.selfAttentionRelu(self_out)
        self_out = self.selfAttentionLinear2(self_out)
        self_out = self.selfAttentionLayerNorm(self_out + image)

        # multihead attention module
        multi_out = self.multiheadAttentionMultihead(text, text, text)[0]
        multi_out = self.multiheadAttentionLinear1(multi_out)
        multi_out = self.multiheadAttentionRelu(multi_out)
        multi_out = self.multiheadAttentionLinear2(multi_out)
        multi_out = self.multiheadAttentionLayerNorm(multi_out + text)

        return self_out, multi_out

In [10]:
class co_attention(nn.Module):
    def __init__(self):
        super(co_attention, self).__init__()
        # co-attention text
        self.coAttentionTextMultihead = nn.MultiheadAttention(768, 1)
        self.coAttentionTextLinear1 = nn.Linear(768, 768)
        self.coAttentionTextRelu = nn.ReLU()
        self.coAttentionTextLinear2 = nn.Linear(768, 768)
        self.coAttentionTextLayerNorm = nn.LayerNorm(768, eps=eps)

        # co-attention image
        self.coAttentionImageMultihead = nn.MultiheadAttention(768, 1)
        self.coAttentionImageLinear1 = nn.Linear(768, 768)
        self.coAttentionImageRelu = nn.ReLU()
        self.coAttentionImageLinear2 = nn.Linear(768, 768)
        self.coAttentionImageLayerNorm = nn.LayerNorm(768, eps=eps)

    def forward(self, image, text):
        # co-attention image module
        visual_attending_textual = self.coAttentionTextMultihead(image, text, text)[0]
        visual_attending_textual = self.coAttentionTextLinear1(visual_attending_textual)
        visual_attending_textual = self.coAttentionTextRelu(visual_attending_textual)
        visual_attending_textual = self.coAttentionTextLinear2(visual_attending_textual)
        visual_attending_textual = self.coAttentionTextLayerNorm(visual_attending_textual + image)

        # co-attention text module
        textual_attending_visual = self.coAttentionTextMultihead(text, image, image)[0]
        textual_attending_visual = self.coAttentionTextLinear1(textual_attending_visual)
        textual_attending_visual = self.coAttentionTextRelu(textual_attending_visual)
        textual_attending_visual = self.coAttentionTextLinear2(textual_attending_visual)
        textual_attending_visual = self.coAttentionTextLayerNorm(textual_attending_visual + text)

        return visual_attending_textual, textual_attending_visual

In [11]:
class Generator(nn.Module):
    def __init__(self, depth=12):
        super(Generator, self).__init__()
        self.layers_self_multi = nn.ModuleList([self_multi() for _ in range(depth)])
        self.layers_co_attention = nn.ModuleList([co_attention() for _ in range(depth)])

        # feed forward
        self.feedForwardLinear = nn.Linear(768, 768)
        self.feedForwardLayerNorm = nn.LayerNorm(768, eps=eps)

        # gemma
        self.gemmaLinearMaxTokens = nn.Linear(64, 16)
        self.gemmaLinearBefore = nn.Linear(768, gemmaConfig.vocab_size)
        self.gemmaSoftmax = nn.Softmax(dim=2)
        self.gemma = nn.Sequential(*list(gemma.children())[:-1])
        # self.gemmaLm_head = nn.Sequential(*list(gemma.children())[1:])
        self.gemmaLm_headbf = nn.Linear(768, gemma_hiddenstate_size)
        self.gemmaLm_head = nn.Linear(gemma_hiddenstate_size, gemmaConfig.vocab_size)

        # funny score
        self.FunnyScorelinear1 = nn.Linear(768, 1)
        self.FunnyScorelinear2 = nn.Linear(64, 1)

    def gemmaGenerate(self, x):
        with torch.no_grad():
            # maximum 32 tokens
            x = self.gemmaLinearMaxTokens(x.transpose(1, 2)).transpose(1, 2)
            x = self.gemmaLinearBefore(x)
            x2 = self.gemmaSoftmax(x + eps)

            # get max value of each row, total 32*64
            top_k_values, top_k_indices = torch.topk(x2, 1, dim=2, largest=True)
            output_text = textExtractReverse(gemma, tokenizer, gemmaConfig, top_k_indices).to(device)
            # toGemma = textExtractReverse(gemma, tokenizer, top_k_indices, Test=True).to(device)
            # 使用gemma作為model的一部分
            # output = self.gemma(toGemma)
            # output[0] = last_hidden_state
            # output[1] = past_key_values

        return output_text

    def forward(self, text, image):
        # max_seq_len = max(text.shape[1], image.shape[1])
        # text = nn.functional.pad(text, (0, 0, 0, max_seq_len - text.shape[1]))
        # image = nn.functional.pad(image, (0, 0, 0, max_seq_len - image.shape[1]))
        text = text.transpose(0, 1)
        image = image.transpose(0, 1)

        ######################### Transformer #########################
        for self_multi_layer in self.layers_self_multi:
            image, text = self_multi_layer(image, text)
        for co_attention_layer in self.layers_co_attention:
            image, text = co_attention_layer(image, text)
        ###############################################################

        # feature fusion
        feature_fusion = image + text  # visual_attending_textual + textual_attending_visual
        feature_fusionFF = self.feedForwardLinear(feature_fusion)
        feature_fusion_final = self.feedForwardLayerNorm(feature_fusion + feature_fusionFF)
        feature_fusion_final = feature_fusion_final.squeeze(-1)
        feature_fusion_final = feature_fusion_final.transpose(0, 1)
        ####################### gemma  generate #######################
        last_hidden_state = self.gemmaGenerate(feature_fusion_final)
        output_text = self.gemmaLm_head(last_hidden_state)
        ###############################################################
        # output_text = self.gemmaLm_headbf(feature_fusion_final)
        # output_text = self.gemmaLm_head(output_text)
        ###############################################################
        output_text = output_text.to(torch.bfloat16)
        ######################### funny score #########################
        output_funny_score = self.FunnyScorelinear1(feature_fusion_final).squeeze(-1)
        output_funny_score = self.FunnyScorelinear2(output_funny_score).squeeze(-1)
        ###############################################################

        return output_text, output_funny_score

    def generate(self, text, image):
        generated_tokens = []
        generated_tokens.append(2)  # <bos> = 2
        text = torch.zeros_like(image).to(device)
        text = text.transpose(0, 1).to(torch.bfloat16)
        image = image.transpose(0, 1)
        depth = len(self.layers_self_multi)

        with torch.no_grad():
            # Transformer
            for i in range(depth):
                # self attention
                image, text = self.layers_self_multi[i](image, text)
                # co-attention
                image, text = self.layers_co_attention[i](image, text)

            # feature fusion
            feature_fusion = image + text  # visual_attending_textual + textual_attending_visual
            feature_fusionFF = self.feedForwardLinear(feature_fusion)
            feature_fusion_final = self.feedForwardLayerNorm(feature_fusion + feature_fusionFF)
            feature_fusion_final = feature_fusion_final.squeeze(-1)
            feature_fusion_final = feature_fusion_final.transpose(0, 1)

            # gemma generate
            output_text = self.gemmaGenerate(feature_fusion_final).to(torch.bfloat16)

            text = output_text.transpose(0, 1)

            # Transformer
            for i in range(depth):
                # self attention
                image, text = self.layers_self_multi[i](image, text)
                # co-attention
                image, text = self.layers_co_attention[i](image, text)

                # feature fusion
                feature_fusion = image + text  # visual_attending_textual + textual_attending_visual
                feature_fusionFF = self.feedForwardLinear(feature_fusion)
                feature_fusion_final = self.feedForwardLayerNorm(feature_fusion + feature_fusionFF)
                feature_fusion_final = feature_fusion_final.squeeze(-1)
                feature_fusion_final = feature_fusion_final.transpose(0, 1)

            # funny score
            output_funny_score = self.FunnyScorelinear1(feature_fusion_final).squeeze(-1)
            output_funny_score = self.FunnyScorelinear2(output_funny_score).squeeze(-1)

        return output_text, output_funny_score

# 5. Discriminator

In [ ]:
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.linearFake = nn.Linear(gemmaConfig.vocab_size, 768)
        # Generator
        self.g_con_mlp1 = nn.Linear(1536, 2)
        self.g_con_mlp2 = nn.Linear(64, 1)
        self.g_unc_mlp1 = nn.Linear(768, 1)
        self.g_unc_mlp2 = nn.Linear(64, 1)
        # Discriminator
        self.d_linearFake = nn.Linear(gemmaConfig.vocab_size, 768)
        self.d_con_mlp1_cd = nn.Linear(3072, 2)
        self.d_con_mlp2_cd = nn.Linear(64, 1)
        self.d_con_mlp1 = nn.Linear(1536, 2)
        self.d_con_mlp2 = nn.Linear(64, 1)
        self.d_unc_mlp1 = nn.Linear(768, 1)
        self.d_unc_mlp2 = nn.Linear(64, 1)

        self.con_mlp1 = nn.Linear(1536, 2)
        self.con_mlp2 = nn.Linear(64, 1)
        self.unc_mlp1 = nn.Linear(768, 1)
        self.unc_mlp2 = nn.Linear(64, 1)

    def forward(self, real_text, fake_text, image, GorD):
        # real_text = [batch_size, 64, 768]
        # fake_text = [batch_size, 64, 256000]
        # image = [batch_size, 64, 768]

        mismatched_text = torch.roll(real_text, 1, 0)
        # real_text = self.linearFake(real_text)
        # fake_text = self.linearFake(fake_text)
        # mismatched_text = self.linearFake(mismatched_text)
        if GorD == "G":
            g_C_g = torch.cat((fake_text, image), dim=-1)
            ########################  conditional  ########################
            g_C_g = self.g_con_mlp1(g_C_g)
            g_C_g = self.g_con_mlp2(g_C_g.transpose(1, 2)).squeeze(-1)
            ###############################################################
            ######################## unconditional ########################
            g_UC_g = self.g_unc_mlp1(fake_text).squeeze(-1)
            g_UC_g = self.g_unc_mlp2(g_UC_g).squeeze(-1)
            ###############################################################
            # g_C_g = torch.cat((fake_text, image), dim=-1)
            # ########################  conditional  ########################
            # g_C_g = self.con_mlp1(g_C_g)
            # g_C_g = self.con_mlp2(g_C_g.transpose(1, 2)).squeeze(-1)
            # ###############################################################
            # ######################## unconditional ########################
            # g_UC_g = self.unc_mlp1(fake_text).squeeze(-1)
            # g_UC_g = self.unc_mlp2(g_UC_g).squeeze(-1)
            # ###############################################################
            return g_C_g, g_UC_g

        elif GorD == "D":
            C_r = torch.cat((real_text, image), dim=-1)
            C_g = torch.cat((fake_text, image), dim=-1)
            C_m = torch.cat((mismatched_text, image), dim=-1)
            # contrastive discriminator
            cd_C_r = C_r.unsqueeze(0).expand(C_r.shape[0], -1, -1, -1)
            cd_C_g = C_g.unsqueeze(0).expand(C_g.shape[0], -1, -1, -1)
            d_C_r2f = torch.cat((cd_C_r, cd_C_g.transpose(0, 1)), dim=-1)
            d_C_f2r = torch.cat((cd_C_g, cd_C_r.transpose(0, 1)), dim=-1)

            ######################## conditional ########################
            d_C_r2f = self.d_con_mlp1_cd(d_C_r2f)
            d_C_f2r = self.d_con_mlp1_cd(d_C_f2r)
            d_C_g = self.d_con_mlp1(C_g)
            d_C_m = self.d_con_mlp1(C_m)

            d_C_r2f = self.d_con_mlp2_cd(d_C_r2f.transpose(2,3)).squeeze(-1).unsqueeze(0)
            d_C_f2r = self.d_con_mlp2_cd(d_C_f2r.transpose(2,3)).squeeze(-1).unsqueeze(0)
            d_C_g = self.d_con_mlp2(d_C_g.transpose(1,2)).squeeze(-1).unsqueeze(0)
            d_C_m = self.d_con_mlp2(d_C_m.transpose(1,2)).squeeze(-1).unsqueeze(0)

            d_C_r2f = torch.mean(d_C_r2f, dim=-2)
            d_C_f2r = torch.mean(d_C_f2r, dim=-2)

            d_con_output = torch.cat((d_C_r2f, d_C_f2r, d_C_g, d_C_m), dim=0)
            ###############################################################

            ######################## unconditional ########################
            d_UC_r = self.d_unc_mlp1(real_text).squeeze(-1)
            d_UC_g = self.d_unc_mlp1(fake_text).squeeze(-1)
            d_UC_m = self.d_unc_mlp1(mismatched_text).squeeze(-1)

            d_UC_r = self.d_unc_mlp2(d_UC_r).squeeze(-1).unsqueeze(0)
            d_UC_g = self.d_unc_mlp2(d_UC_g).squeeze(-1).unsqueeze(0)
            d_UC_m = self.d_unc_mlp2(d_UC_m).squeeze(-1).unsqueeze(0)

            d_unc_output = torch.cat((d_UC_r, d_UC_g, d_UC_m), dim=0)
            ###############################################################

            # ######################## conditional ########################
            # d_C_r2f = self.d_con_mlp1_cd(d_C_r2f)
            # d_C_f2r = self.d_con_mlp1_cd(d_C_f2r)
            # d_C_g = self.con_mlp1(C_g)
            # d_C_m = self.con_mlp1(C_m)
            #
            # d_C_r2f = self.d_con_mlp2_cd(d_C_r2f.transpose(2, 3)).squeeze(-1).unsqueeze(0)
            # d_C_f2r = self.d_con_mlp2_cd(d_C_f2r.transpose(2, 3)).squeeze(-1).unsqueeze(0)
            # d_C_g = self.con_mlp2(d_C_g.transpose(1, 2)).squeeze(-1).unsqueeze(0)
            # d_C_m = self.con_mlp2(d_C_m.transpose(1, 2)).squeeze(-1).unsqueeze(0)
            #
            # d_C_r2f = nn.LogSoftmax(dim=-1)(d_C_r2f)
            # d_C_f2r = nn.LogSoftmax(dim=-1)(d_C_f2r)
            # d_C_r2f = torch.mean(d_C_r2f, dim=-2)
            # d_C_f2r = torch.mean(d_C_f2r, dim=-2)
            #
            # d_con_output = torch.cat((d_C_r2f, d_C_f2r, d_C_g, d_C_m), dim=0)
            # ###############################################################
            #
            # ######################## unconditional ########################
            # d_UC_r = self.unc_mlp1(real_text).squeeze(-1)
            # d_UC_g = self.unc_mlp1(fake_text).squeeze(-1)
            # d_UC_m = self.unc_mlp1(mismatched_text).squeeze(-1)
            #
            # d_UC_r = self.unc_mlp2(d_UC_r).squeeze(-1).unsqueeze(0)
            # d_UC_g = self.unc_mlp2(d_UC_g).squeeze(-1).unsqueeze(0)
            # d_UC_m = self.unc_mlp2(d_UC_m).squeeze(-1).unsqueeze(0)
            #
            # d_unc_output = torch.cat((d_UC_r, d_UC_g, d_UC_m), dim=0)
            # ###############################################################
            return d_con_output, d_unc_output

In [33]:
# empty cuda memory
import gc
torch.cuda.empty_cache()
gc.collect()

742

In [34]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [35]:
optimizer_G_lr = 1e-5
optimizer_D_lr = 1e-5
NetG = Generator().to(torch.bfloat16).to(device)
NetD = Discriminator().to(torch.bfloat16).to(device)
optimizer_G = optim.Adam(NetG.parameters(), lr=optimizer_G_lr)
optimizer_D = optim.Adam(NetD.parameters(), lr=optimizer_D_lr)

train_losses_G = []
train_losses_D = []
test_losses_G = []
test_losses_D = []
save = []
present_epoch = 1
best_train_loss_G = 9999
best_train_loss_D = 9999
best_test_loss_G = 9999
best_test_loss_D = 9999

# separate loss
g_fc_loss_list = []
g_con_loss_list = []
g_unc_loss_list = []
d_con_r2f_loss_list = []
d_con_f2r_loss_list = []
d_con_f_loss_list = []
d_con_m_loss_list = []
d_unc_r_loss_list = []
d_unc_f_loss_list = []
d_unc_m_loss_list = []

checkpoint = True
if checkpoint:
    checkpoint_G = torch.load('D:/MemeGAN/Model/20241110_gemma_generate_onlyd/20241110_gemma_generate_onlyd_NetG_2.pth')
    checkpoint_D = torch.load('D:/MemeGAN/Model/20241110_gemma_generate_onlyd/20241110_gemma_generate_onlyd_NetD_2.pth')
    NetG.load_state_dict(checkpoint_G['model_state_dict'])
    NetD.load_state_dict(checkpoint_D['model_state_dict'])
    optimizer_G.load_state_dict(checkpoint_G['optimizer_state_dict'])
    optimizer_D.load_state_dict(checkpoint_D['optimizer_state_dict'])
    present_epoch = checkpoint_G['epoch'] + 1
    del checkpoint_G
    del checkpoint_D
    gc.collect()

def funnyScoreLoss(output_funny_score, funny_score):
    loss = nn.MSELoss()(output_funny_score, funny_score)
    g_fc_loss_list.append(loss.item())
    return loss

def generatorLoss(condition_logits, uncondition_logits):
    result_fake_con = torch.ones(condition_logits.shape[0]).to(torch.long).to(device)
    result_fake_unc = torch.FloatTensor(condition_logits.shape[0]).to(torch.bfloat16).uniform_(0.9, 1.0).to(device)
    con_loss = CrossEntropyLoss(label_smoothing=0.1)(condition_logits, result_fake_con)
    unc_loss = BCEWithLogitsLoss()(uncondition_logits, result_fake_unc)
    g_con_loss_list.append(con_loss.item())
    g_unc_loss_list.append(unc_loss.item())
    loss = con_loss + unc_loss
    return loss

def discriminatorLoss(condition_logits, uncondition_logits):
    result_true = torch.FloatTensor(uncondition_logits[0].shape[0]).to(torch.bfloat16).uniform_(0.9, 1.0).to(device)
    result_fake_ce = torch.zeros(uncondition_logits[0].shape[0]).to(torch.long).to(device)
    result_fake_unc_f = torch.FloatTensor(uncondition_logits[1].shape[0]).to(torch.bfloat16).uniform_(0.0, 0.1).to(device)
    result_fake_unc_m = torch.FloatTensor(uncondition_logits[2].shape[0]).to(torch.bfloat16).uniform_(0.0, 0.1).to(device)

    con_r2f = CrossEntropyLoss(label_smoothing=0.1)(condition_logits[0], result_fake_ce)
    con_f2r = CrossEntropyLoss(label_smoothing=0.1)(condition_logits[1], result_fake_ce)
    con_f = CrossEntropyLoss(label_smoothing=0.1)(condition_logits[2], result_fake_ce)
    con_m = CrossEntropyLoss(label_smoothing=0.1)(condition_logits[3], result_fake_ce)
    unc_r = BCEWithLogitsLoss()(uncondition_logits[0], result_true)
    unc_f = BCEWithLogitsLoss()(uncondition_logits[1], result_fake_unc_f)
    unc_m = BCEWithLogitsLoss()(uncondition_logits[2], result_fake_unc_m)
    d_con_r2f_loss_list.append(con_r2f.item())
    d_con_f2r_loss_list.append(con_f2r.item())
    d_con_f_loss_list.append(con_f.item())
    d_con_m_loss_list.append(con_m.item())
    d_unc_r_loss_list.append(unc_r.item())
    d_unc_f_loss_list.append(unc_f.item())
    d_unc_m_loss_list.append(unc_m.item())
    loss = ((con_r2f + con_f2r) / 2) + ((con_f + con_m) / 2) + unc_r + ((unc_f + unc_m) / 2)
    return loss

In [ ]:
save_name = '20241028'
if not os.path.exists('./Model/'+save_name):
    os.makedirs('./Model/'+save_name)
epochs = 30

In [36]:
startTime = 0
    textExtractionTime = 0
    GeneratorForwardTime = 0
    GeneratorBackwardGTime = 0
    DiscriminatorForwardTime = 0
    DiscriminatorBackwardTime = 0
    torch.autograd.set_detect_anomaly(True)
    for epoch in range(epochs):
        print("---------------------------------------- epoch " + str(
            epoch + present_epoch) + " ---------------------------------------")
        train_loss_G = 0
        train_loss_D = 0
        test_loss_G = 0
        test_loss_D = 0
        pre = 0
        ###################################### Train ######################################
        with tqdm(train_loader, unit="batch", leave=True) as tepoch:
            for idx, (text, image, funny_score) in enumerate(tepoch):
                # tepoch.set_postfix({'Now': tepoch.format_dict['elapsed'], 'Status': " New batch preprocessing"})
                if idx == 0:
                    startTime = tepoch.format_dict['elapsed']
                elif idx == 1:
                    startTime = (tepoch.format_dict['elapsed'] - pre) * 2
                else:
                    startTime += tepoch.format_dict['elapsed'] - pre
                pre = tepoch.format_dict['elapsed']
                text = textExtraction(tokenizer, gemmaConfig, text).to(torch.bfloat16)
                image = image.to(torch.bfloat16)
                funny_score = funny_score.to(torch.bfloat16)
                textExtractionTime += tepoch.format_dict['elapsed'] - pre
                pre = tepoch.format_dict['elapsed']
                ######################################################
                # (1) Update Generator network
                ######################################################
                optimizer_G.zero_grad()
                logits, output_funny_score = NetG(text.to(device), image.to(device))
                g_con_logits, g_unc_logits = NetD(text.to(device), logits, image.to(device), "G")
                GeneratorForwardTime += tepoch.format_dict['elapsed'] - pre
                pre = tepoch.format_dict['elapsed']

                loss_G = generatorLoss(g_con_logits.to(device), g_unc_logits.to(device)) + (
                        100 * funnyScoreLoss(output_funny_score.to(device), funny_score.to(device)))
                loss_G.backward(retain_graph=True)
                train_loss_G += loss_G.item()
                optimizer_G.step()
                GeneratorBackwardGTime += tepoch.format_dict['elapsed'] - pre
                pre = tepoch.format_dict['elapsed']
                ######################################################
                # (4) Update Discriminator network
                ######################################################
                optimizer_D.zero_grad()
                d_con_logits, d_unc_logits = NetD(text.to(device).detach(), logits.detach(), image.to(device).detach(), "D")
                DiscriminatorForwardTime += tepoch.format_dict['elapsed'] - pre
                pre = tepoch.format_dict['elapsed']
                loss_D = discriminatorLoss(d_con_logits.to(device), d_unc_logits.to(device))
                loss_D.backward()
                DiscriminatorBackwardTime += tepoch.format_dict['elapsed'] - pre
                pre = tepoch.format_dict['elapsed']
                optimizer_D.step()
                train_loss_D += loss_D.item()
                ######################################################
                # tepoch.set_postfix({'FC_loss': train_loss_FC/ (idx+1), 'G_loss': train_loss_G/ (idx+1), 'D_loss': train_loss_D/ (idx+1)})
                tepoch.set_postfix({'start': startTime / (idx + 1), 'textExtraction': textExtractionTime / (idx + 1),
                                    'GeneratorForward': GeneratorForwardTime / (idx + 1),
                                    'GeneratorBackwardG': GeneratorBackwardGTime / (idx + 1),
                                    'DiscriminatorForward': DiscriminatorForwardTime / (idx + 1),
                                    'DiscriminatorBackward': DiscriminatorBackwardTime / (idx + 1)})
                sepateLoss = pd.DataFrame()
                sepateLoss['g_fc_loss'] = g_fc_loss_list
                sepateLoss['g_con_loss'] = g_con_loss_list
                sepateLoss['g_unc_loss'] = g_unc_loss_list
                sepateLoss['d_con_r2f_loss'] = d_con_r2f_loss_list
                sepateLoss['d_con_f2r_loss'] = d_con_f2r_loss_list
                sepateLoss['d_con_f_loss'] = d_con_f_loss_list
                sepateLoss['d_con_m_loss'] = d_con_m_loss_list
                sepateLoss['d_unc_r_loss'] = d_unc_r_loss_list
                sepateLoss['d_unc_f_loss'] = d_unc_f_loss_list
                sepateLoss['d_unc_m_loss'] = d_unc_m_loss_list
                sepateLoss.to_csv('./Model/' + save_name + "/" + save_name + '_sepateLoss.csv', index=False)
                ######################################################
        train_loss_G /= len(train_loader)
        train_loss_D /= len(train_loader)
        train_losses_G.append(train_loss_G)
        train_losses_D.append(train_loss_D)
        ###################################### Train ######################################

        ######################################  Test ######################################
        with tqdm(test_loader, unit="batch", leave=True) as tepoch:
            for idx, (text, image, funny_score) in enumerate(tepoch):
                text = textExtraction(tokenizer, gemmaConfig, text).to(torch.bfloat16)
                image = image.to(torch.bfloat16)
                funny_score = funny_score.to(torch.bfloat16)
                # Generator
                logits, output_funny_score = NetG(text.to(device), image.to(device))
                # Discriminator
                g_con_logits, g_unc_logits = NetD(text.to(device), logits, image.to(device), "G")
                d_con_logits, d_unc_logits = NetD(text.to(device).detach(), logits.detach(), image.to(device).detach(),"D")
                # loss
                loss_G = generatorLoss(g_con_logits.to(device), g_unc_logits.to(device)) + (
                        100 * funnyScoreLoss(output_funny_score.to(device), funny_score.to(device)))
                loss_D = discriminatorLoss(d_con_logits, d_unc_logits)
                test_loss_G += loss_G.item()
                test_loss_D += loss_D.item()
                tepoch.set_postfix({'G_loss': test_loss_G / (idx + 1),
                                    'D_loss': test_loss_D / (idx + 1)})
        test_loss_G /= len(test_loader)
        test_loss_D /= len(test_loader)
        test_losses_G.append(test_loss_G)
        test_losses_D.append(test_loss_D)
        ######################################  Test ######################################

        ######################################  Save ######################################
        hasSaved = False
        # 任一個loss小於最佳loss就存檔
        if train_loss_G < best_train_loss_G and test_loss_G < best_test_loss_G:
            best_train_loss_G = train_loss_G
            best_test_loss_G = test_loss_G
            hasSaved = True
            torch.save({
                'epoch': epoch + present_epoch,
                'model_state_dict': NetG.state_dict(),
                'optimizer_state_dict': optimizer_G.state_dict(),
            }, './Model/' + save_name + "/" + save_name + '_NetG_' + str(epoch + present_epoch) + '.pth')
            torch.save({
                'epoch': epoch + present_epoch,
                'model_state_dict': NetD.state_dict(),
                'optimizer_state_dict': optimizer_D.state_dict(),
            }, './Model/' + save_name + "/" + save_name + '_NetD_' + str(epoch + present_epoch) + '.pth')
        if train_loss_D < best_train_loss_D and test_loss_D < best_test_loss_D:
            best_train_loss_D = train_loss_D
            best_test_loss_D = test_loss_D
            hasSaved = True
            torch.save({
                'epoch': epoch + present_epoch,
                'model_state_dict': NetG.state_dict(),
                'optimizer_state_dict': optimizer_G.state_dict(),
            }, './Model/' + save_name + "/" + save_name + '_NetG_' + str(epoch + present_epoch) + '.pth')
            torch.save({
                'epoch': epoch + present_epoch,
                'model_state_dict': NetD.state_dict(),
                'optimizer_state_dict': optimizer_D.state_dict(),
            }, './Model/' + save_name + "/" + save_name + '_NetD_' + str(epoch + present_epoch) + '.pth')

        if hasSaved:
            save.append("V")
        else:
            save.append(" ")

        loss_data = pd.DataFrame()
        loss_data['train_G'] = train_losses_G
        loss_data['train_D'] = train_losses_D
        loss_data['test_G'] = test_losses_G
        loss_data['test_D'] = test_losses_D
        loss_data['save'] = save
        loss_data.to_csv('./Model/' + save_name + "/" + save_name + '_loss.csv', index=False)

        plt.plot(train_losses_G, label='train_G')
        plt.plot(train_losses_D, label='train_D')
        plt.plot(test_losses_G, label='test_G')
        plt.plot(test_losses_D, label='test_D')
        plt.legend()
        plt.show()
        # save plot
        plt.savefig('./Model/' + save_name + "/" + save_name + '_loss.png')
        ######################################  Save ######################################

---------------------------------------- epoch 1 ---------------------------------------

  0%|          | 0/4248 [00:00<?, ?batch/s]

torch.Size([32, 32, 256, 768]) torch.Size([32, 32, 256, 768]) torch.Size([32, 128, 768]) torch.Size([32, 128, 768])
torch.Size([32, 32, 256, 2]) torch.Size([32, 32, 256, 2]) torch.Size([32, 128, 768]) torch.Size([32, 128, 768])
torch.Size([32, 32, 2]) torch.Size([32, 32, 2]) torch.Size([32, 128, 768]) torch.Size([32, 128, 768])
torch.Size([1, 32, 2]) torch.Size([1, 32, 2]) torch.Size([32, 128, 768]) torch.Size([32, 128, 768])

  0%|          | 1/4248 [00:25<30:14:19, 25.63s/batch, start=0.052, textExtraction=0.673, GeneratorForward=8.24, GeneratorBackwardFC=1.5, GeneratorBackwardG=4.57, DiscriminatorForward=0.727, DiscriminatorBackward=1.62]

KeyboardInterrupt: