# Result Determination (GAMC better than baselines)

In [ ]:
import pandas as pd

### Combine results with humor score

In [ ]:
dataPath = './Model/3000/ablation/SD/100up_only200_lessNotFunImg_169_55_passlength_10_SD_/'
# dataPath = './Model/clip/clip_100up_only200_lessNotFunImg_169_55_passlength_10_SD_with_oxford_3000_only1_300_82/'
# dataPath = './Model/bita/sd/'

data1 = pd.read_csv(f'{dataPath}generate_beam_2.csv')
data2 = pd.read_csv(f'{dataPath}0425_exchange_05_08_13_focal_08_17_temp050_7_generate_beam_humorscore.csv')
beam = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
beam

data1 = pd.read_csv(f'{dataPath}generate2_11.csv')
data2 = pd.read_csv(f'{dataPath}left0_11_generate2_humorscore.csv')
gen2 = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
gen2.to_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv', index=False)
gen2

In [ ]:
# funny results counter
gen2_img = set(gen2[gen2['humor_score']>=0.5].image_id.unique())
beam_img = set(beam[beam['humor_score']>=0.5].image_id.unique())
img_list = gen2_img.union(beam_img)
len(img_list)

In [ ]:
# clip
new_gen2 = gen2
new_beam = beam

In [317]:
# mine
new_gen2 = gen2[gen2['image_id'].isin(img_list)]
new_beam = beam[beam['image_id'].isin(img_list)]

def addcolumns(data):
    new_data = data[data.columns[:2]]
    new_data['human_ins']=''
    new_data['human_humor'] = ''
    new_data['human_related'] = ''
    new_data['overfit'] = ''
    new_data = pd.concat([new_data, data[data.columns[2:]]], axis=1)
    return new_data

new_gen2 = addcolumns(new_gen2)
new_beam = addcolumns(new_beam)

C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_ins']=''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_humor'] = ''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_related'] = ''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['overfit'] = ''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_ins']=''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_humor'] = ''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_related'] = ''
C:\Users\fang\AppData\Local\Temp\ipykernel_428\2992410934.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['overfit'] = ''

In [ ]:
new_gen2.to_csv(f'{dataPath}/focal_08_17_filtered_hc_generate2_2.csv', index=False)
new_beam.to_csv(f'{dataPath}/focal_08_17_filtered_hc_generate_beam_2.csv', index=False)

### Combine results with all evaluation metrics and baseline results

In [ ]:
dataPath = './Model/3000/ablation/SD/100up_only200_lessNotFunImg_169_55_passlength_10_SD_/'
data1 = pd.read_csv(f'{dataPath}generate2_11.csv')
data2 = pd.read_csv(f'{dataPath}left0_11_generate2_humorscore.csv')
new_gen2 = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
new_gen2
# data1 = pd.read_csv(f'{dataPath}ground_truth.csv')
# data2 = pd.read_csv(f'{dataPath}0425_exchange_05_08_13_focal_08_17_temp050_7_ground_truth_humorscore.csv')
# groundtruth = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
# groundtruth

In [ ]:
bita = pd.read_csv(f'../Citations/vilio/data/U36_clip_SD_all_generate2_1.csv')
bita['image_id'] = bita['id']
new_gen2 = new_gen2.merge(bita[['image_id','proba']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['b_clip'] = new_gen2['proba']
new_gen2 = new_gen2.drop(columns=['proba'])
bita = pd.read_csv(f'../Citations/vilio/data/U36_bita_sd_all.csv')
bita['image_id'] = bita['id']
new_gen2 = new_gen2.merge(bita[['image_id','proba']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['b_bita'] = new_gen2['proba']
new_gen2 = new_gen2.drop(columns=['proba'])
new_gen2.to_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv', index=False)

In [129]:
bita = pd.read_csv(f'./Model/bita/sd/generate2_1.csv')
new_gen2 = new_gen2.merge(bita[['image_id','fluency']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['f_bita'] = new_gen2['fluency_']
new_gen2 = new_gen2.drop(columns=['fluency_'])
clip = pd.read_csv(f'./Model/clip/clip_100up_only200_lessNotFunImg_169_55_passlength_10_SD_with_oxford_3000_only1_300_82/generate2_1.csv')
new_gen2 = new_gen2.merge(clip[['image_id','fluency']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['f_clip'] = new_gen2['fluency_']
new_gen2 = new_gen2.drop(columns=['fluency_'])
new_gen2.to_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv', index=False)

In [130]:
gt = pd.read_csv('./Model/3000/ablation/SD/100up_only200_lessNotFunImg_169_55_passlength_10_SD_/left0_11_ground_truth_humorscore.csv')
new_gen2 = new_gen2.merge(gt[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['h_gt'] = new_gen2['humor_score_']
new_gen2 = new_gen2.drop(columns=['humor_score_'])
bita = pd.read_csv(f'./Model/bita/sd/left0_11_generate2_humorscore.csv')
new_gen2 = new_gen2.merge(bita[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['h_bita'] = new_gen2['humor_score_']
new_gen2 = new_gen2.drop(columns=['humor_score_'])
clip = pd.read_csv(f'./Model/clip/clip_100up_only200_lessNotFunImg_169_55_passlength_10_SD_with_oxford_3000_only1_300_82/left0_11_generate2_humorscore.csv')
new_gen2 = new_gen2.merge(clip[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['h_clip'] = new_gen2['humor_score_']
new_gen2 = new_gen2.drop(columns=['humor_score_'])
new_gen2.to_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv', index=False)

In [132]:
benign = pd.read_csv(f'../Citations/vilio/data/U36_mine_169_55_SD_generate2.csv')
benign['image_id'] = benign['id']
new_gen2 = new_gen2.merge(benign[['image_id','proba']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['benign'] = new_gen2['proba']
new_gen2 = new_gen2.drop(columns=['proba'])
new_gen2.to_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv', index=False)

In [4]:
gen2_img = set(new_gen2[(new_gen2['overfit'] == 0) | (new_gen2['overfit'] == 2)].image_id.unique())
beam_img = set(new_beam[(new_beam['overfit'] == 0) | (new_beam['overfit'] == 2)].image_id.unique())
img_list = gen2_img.union(beam_img)
len(img_list)

69

In [29]:
new_gen2_final = new_gen2[(new_gen2['overfit'] == 1)]

In [119]:
gen2_img_2 = set(new_gen2[(new_gen2['overfit'] == 2)].image_id.unique())
beam_img_2 = set(new_beam[(new_beam['overfit'] == 2)].image_id.unique())
img_list_2 = gen2_img_2.union(beam_img_2)

new_gen2_final = new_gen2[new_gen2['image_id'].isin(img_list_2)]
new_beam_final = new_beam[new_beam['image_id'].isin(img_list_2)]
print(new_gen2_final.shape)

(26, 17)

# diversity score

In [26]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import clip
import numpy as np
import pandas as pd
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
clip_self, clip_preprocess = clip.load("ViT-B/32")
clip_self.to(device)
clip_self.eval()
def diversity(captionList):
    # tokenize  and extract text features
    text_tokens = clip.tokenize(captionList, context_length=77, truncate=True).to(device)
    with torch.no_grad():
        text_features = clip_self.encode_text(text_tokens).float()
    text_features /= text_features.norm(dim=-1, keepdim=True)
    text_features = text_features.cpu().numpy()
    # 計算所有 pair 的 cosine similarity
    cosine_sim = np.dot(text_features, text_features.T)  # p_m^T * p_n
    norms = np.linalg.norm(text_features, axis=1, keepdims=True)
    cosine_sim /= (norms @ norms.T)  # 除以 |pm||pn|
    # 找出每個向量最相似的另一個向量（n ≠ m）
    max_similarities = np.array([max(row[np.arange(len(row)) != i]) for i, row in enumerate(cosine_sim)])
    # 計算 diversity score
    diversity = np.sqrt(1 - np.mean(max_similarities) ** 2)
    return diversity

In [225]:
new_beam = new_beam.merge(new_gen2[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
new_beam['addup'] = new_beam['humor_score'] + new_beam['humor_score_']
new_gen2_temp = new_beam[~new_beam['image_id'].isin(img_list_2)].sort_values(by='addup', ascending=False)
new_gen2_temp
new_gen2_temp = new_gen2_temp.drop(columns=['addup','humor_score_'])
print(new_gen2_temp.shape)

(136, 16)

In [219]:
new_gen2 = new_gen2.merge(new_beam[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
new_gen2['addup'] = new_gen2['humor_score'] + new_gen2['humor_score_']
new_gen2_temp = new_gen2[~new_gen2['image_id'].isin(img_list_2)].sort_values(by='addup', ascending=False)
new_gen2_temp
new_gen2_temp = new_gen2_temp.drop(columns=['addup','humor_score_'])
print(new_gen2_temp.shape)

(136, 16)

In [238]:
new_gen2_temp = new_beam[(new_beam['overfit'] != 2)].sort_values(by='humor_score', ascending=False)
print(new_gen2_temp.shape)

(148, 18)

In [70]:
new_gen2_temp = new_gen2_final

In [ ]:
new_gen2_temp = new_gen2_temp.reset_index()

### Diversity selection >> get 56 results keep diversity score > 0.4

In [ ]:
# new_gen2_final = pd.concat([new_gen2_final, new_gen2_temp], ignore_index=True)
captionList = new_gen2_final['caption'].to_list()
pre_di = 0.4
print(pre_di)
for idx in range(new_gen2_temp.shape[0]):
    temp = captionList
    temp.append(new_gen2_temp.loc[idx, 'caption'])
    now_di = diversity(temp)
    if now_di >= pre_di:
        # pre_di = now_di
        captionList = temp
        new_gen2_final = pd.concat([new_gen2_final, new_gen2_temp.iloc[idx].to_frame().T], ignore_index=True)
        # if new_gen2_final.shape[0] == 56:
        #     break
new_gen2_final.shape[0]

In [ ]:
pre_di

### Final selection

In [ ]:
dataPath = './Model/3000/100up_only200_lessNotFunImg_169_55_passlength_10_SD_base_0421_oxford_3000_only1_300_82_ESH_filter_cross_concat_combineLoss/'
new_gen2 = pd.read_csv(f'{dataPath}focal_08_17_filtered_hc_generate2_11.csv')
new_beam = pd.read_csv(f'{dataPath}focal_08_17_filtered_hc_generate_beam_11.csv')
data1 = pd.read_csv(f'{dataPath}ground_truth.csv')
data2 = pd.read_csv(f'{dataPath}0425_exchange_05_08_13_focals_08_17_temp050_7_ground_truth_humorscore.csv')
groundtruth = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
gen2_img_2 = set(new_gen2[(new_gen2['overfit'] == 2)].image_id.unique())
beam_img_2 = set(new_beam[(new_beam['overfit'] == 2)].image_id.unique())
img_list_2 = gen2_img_2.union(beam_img_2)

new_gen2_final = new_gen2[new_gen2['image_id'].isin(img_list_2)]
new_beam_final = new_beam[new_beam['image_id'].isin(img_list_2)]
print(new_gen2_final.shape)

new_beam = new_beam.merge(new_gen2[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
new_beam['addup'] = new_beam['humor_score'] + new_beam['humor_score_']
new_beam_temp = new_beam[~new_beam['image_id'].isin(img_list_2)]
new_beam_temp = new_beam_temp[(new_beam_temp['benign'] > new_beam_temp['b_clip'])].sort_values(by='addup', ascending=False)
new_beam_temp = new_beam_temp.sort_values(by='b_bita', ascending=True)[:56-(len(img_list_2))]
new_beam_temp = new_beam_temp.drop(columns=['addup','humor_score_'])
new_beam_final = pd.concat([new_beam_final, new_beam_temp], ignore_index=True)
new_gen2_final = new_gen2[new_gen2['image_id'].isin(new_beam_final.image_id.unique())]
groundtruth_final = groundtruth[groundtruth['image_id'].isin(new_beam_final.image_id.unique())]
new_beam_final['diversity'] = diversity(new_beam_final['caption'].to_list())
new_gen2_final['diversity'] = diversity(new_gen2_final['caption'].to_list())
groundtruth_final['diversity'] = diversity(groundtruth_final['caption'].to_list())
print(new_gen2_final.shape, new_beam_final.shape, groundtruth_final.shape)
new_beam_final.describe()

In [ ]:
dataPath = './Model/3000/ablation/SD/100up_only200_lessNotFunImg_169_55_passlength_10_SD_/'
new_gen2 = pd.read_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv')
# new_beam = pd.read_csv(f'{dataPath}focal_08_17_filtered_hc_generate_beam_11.csv')
# data1 = pd.read_csv(f'{dataPath}ground_truth.csv')
# data2 = pd.read_csv(f'{dataPath}0425_exchange_05_08_13_focals_08_17_temp050_7_ground_truth_humorscore.csv')
# groundtruth = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
gen2_img_2 = set(new_gen2[(new_gen2['overfit'] == 1)].image_id.unique())
# beam_img_2 = set(new_beam[(new_beam['overfit'] == 2)].image_id.unique())
# img_list_2 = gen2_img_2.union(beam_img_2)
img_list_2 = gen2_img_2

new_gen2_final = new_gen2[new_gen2['image_id'].isin(img_list_2)]
# new_beam_final = new_beam[new_beam['image_id'].isin(img_list_2)]
print(new_gen2_final.shape)

# new_gen2 = new_gen2.merge(new_beam[['image_id','humor_score']], on=['image_id'], how='inner', suffixes=('', '_'))
# new_gen2['addup'] = new_gen2['humor_score'] + new_gen2['humor_score_']
new_gen2_temp = new_gen2[~new_gen2['image_id'].isin(img_list_2)]

# new_gen2_temp = new_gen2_temp.sort_values(by=['humor_score','fluency'], ascending=[False,False])[:56-(len(img_list_2))]
# new_gen2_temp = new_gen2_temp[(new_gen2_temp['benign'] > new_gen2_temp['b_clip']) & (new_gen2_temp['benign'] > new_gen2_temp['b_bita'])].sort_values(by='humor_score', ascending=False)[:56-(len(img_list_2))]
# new_gen2_temp = new_gen2_temp[(new_gen2_temp['benign'] > new_gen2_temp['b_bita'])].sort_values(by='f_bita', ascending=True)[:56-(len(img_list_2))]
new_gen2_temp['b_minus'] = new_gen2_temp['benign'] - new_gen2_temp['b_clip']
new_gen2_temp['f_minus'] = new_gen2_temp['fluency'] - new_gen2_temp['f_bita']
new_gen2_temp['h_minus'] = new_gen2_temp['humor_score'] - new_gen2_temp['h_clip']
# new_gen2_temp = new_gen2_temp.sort_values(by=['humor_score'], ascending=[False])[:56-(len(img_list_2))]
new_gen2_temp = new_gen2_temp[(new_gen2_temp['b_minus'] > -3)&(new_gen2_temp['f_minus'] >-0.2)].sort_values(by=['h_minus'], ascending=[False])[:56-(len(img_list_2))]
# new_gen2_temp = new_gen2_temp[(new_gen2_temp['b_minus'] > -8)&(new_gen2_temp['f_minus'] >-0.6)].sort_values(by=['h_minus'], ascending=[False])#[:56-(len(img_list_2))]
# new_gen2_temp = new_gen2_temp[new_gen2_temp['f_minus'] > -0.5].sort_values(by=['humor_score','b_minus'], ascending=[False,False])[:56-(len(img_list_2))]
# new_gen2_temp_a = new_gen2_temp[(new_gen2_temp['benign'] > new_gen2_temp['b_clip']) & (new_gen2_temp['benign'] > new_gen2_temp['b_bita'])]#.sort_values(by='addup', ascending=False)#[:56-(len(img_list_2))]
# new_gen2_temp_b = new_gen2_temp[~new_gen2_temp['image_id'].isin(new_gen2_temp_a['image_id'].to_list())].sort_values(by='b_bita', ascending=True)[:56-(len(img_list_2))-(new_gen2_temp_a.shape[0])]
# new_gen2_temp = pd.concat([new_gen2_temp_a, new_gen2_temp_b], ignore_index=True)
# new_gen2_temp = new_gen2_temp.drop(columns=['addup','humor_score_'])
# new_gen2_final = pd.concat([new_gen2_final, new_gen2_temp], ignore_index=True)
# new_beam_final = new_beam[new_beam['image_id'].isin(new_gen2_final.image_id.unique())]
# groundtruth_final = groundtruth[groundtruth['image_id'].isin(new_gen2_final.image_id.unique())]
# new_beam_final['diversity'] = diversity(new_beam_final['caption'].to_list())
# new_gen2_final['diversity'] = diversity(new_gen2_final['caption'].to_list())
# groundtruth_final['diversity'] = diversity(groundtruth_final['caption'].to_list())
# print(new_gen2_final.shape, new_beam_final.shape, groundtruth_final.shape)

# new_gen2_temp = new_gen2_temp.reset_index()
# captionList = new_gen2_final['caption'].to_list()
# img_list_diversity = list()
# with tqdm(total=new_gen2_temp.shape[0]) as pbar:
#     for idx in range(new_gen2_temp.shape[0]):
#         pbar.update(1)
#         temp = captionList
#         temp.append(new_gen2_temp.loc[idx, 'caption'])
#         now_di = diversity(temp)
#         if now_di >= 0.437:
#             captionList = temp
#             img_list_diversity.append(new_gen2_temp.loc[idx, 'image_id'])
#             if len(img_list_diversity) >56:
#                 break
#         pbar.set_postfix({'len':len(img_list_diversity)})
#
# new_gen2_temp = new_gen2_temp[new_gen2_temp['image_id'].isin(img_list_diversity)][:56-(len(img_list_2))]
new_gen2_final = pd.concat([new_gen2_final, new_gen2_temp], ignore_index=True)
new_gen2_final = new_gen2_final.drop(columns=['bleu1','bleu2','bleu3','bleu4'])
new_gen2_final['diversity'] = diversity(new_gen2_final['caption'].to_list())
print(new_gen2_final.shape)
new_gen2_final.describe()

In [161]:
new_gen2_final.to_csv(f'{dataPath}left0_final_56_gen2_ultra.csv', index=False)
# new_beam_final.to_csv(f'{dataPath}final_56_focal_08_17_filtered_hc_generate_beam_11_benign_gen2_ultra.csv', index=False)
# groundtruth_final.to_csv(f'{dataPath}final_56_groundtruth_benign_gen2_ultra.csv', index=False)

In [42]:
###########　以人工分類為準 ###########
# gen2_img_2 = set(new_gen2[(new_gen2['overfit'] == 2)].image_id.unique())
# beam_img_2 = set(new_beam[(new_beam['overfit'] == 2)].image_id.unique())
# gen2_img_0_1 = set(new_gen2[(new_gen2['overfit'] == 0) & (new_gen2['human_ins'] == 1)].image_id.unique())
# beam_img_0_1 = set(new_beam[(new_beam['overfit'] == 0) & (new_beam['human_ins'] == 1)].image_id.unique())
# gen2_img_0_0 = set(new_gen2[(new_gen2['overfit'] == 0) & (new_gen2['human_ins'] == 0)].image_id.unique())
# beam_img_0_0 = set(new_beam[(new_beam['overfit'] == 0) & (new_beam['human_ins'] == 0)].image_id.unique())
# img_list_2 = gen2_img_2.union(beam_img_2)
# img_list_0_1 = gen2_img_0_1.union(beam_img_0_1)
# img_list_0_0 = gen2_img_0_0.union(beam_img_0_0)
# img_list = img_list_2.union(img_list_0_1)
# temp = set(list(img_list_0_0.difference(img_list))[:75-len(img_list)])
# img_list = img_list.union(temp)
# print(len(img_list))
#
# new_gen2 = new_gen2[new_gen2['image_id'].isin(img_list)]
# new_beam = new_beam[new_beam['image_id'].isin(img_list)]
# groundtruth = groundtruth[groundtruth['image_id'].isin(img_list)]
# print(new_gen2.shape, new_beam.shape, groundtruth.shape)

75

# Same samples for clip and bita and ablations

In [ ]:
clip_dataPath = './Model/3000/ablation/MC/_woFCT_onlyLoRaadapt/'
dataPath = './Model/3000/ablation/MC/100up_only200_lessNotFunImg_53_171_passlength_12_MC_/'
mine = pd.read_csv(f'{dataPath}left0_final_56_gen2_ultra.csv')
clip_gen2 = pd.read_csv(f'{clip_dataPath}/all/generate2_6.csv')
clip_gen2 = clip_gen2[clip_gen2['image_id'].isin(mine.image_id.unique())]
clip_gen2.shape

In [ ]:
clip_gen2.to_csv(f'{clip_dataPath}/generate2_1.csv', index=False)

In [115]:
dataPath = './Model/3000/ablation/MC/100up_only200_lessNotFunImg_53_171_passlength_12_MC_/'
dataPath = './Model/clip/clip_100up_only200_lessNotFunImg_53_171_passlength_12_MC_with_oxford_3000_only1_300_82/'
dataPath = './Model/bita/mc/'
data1 = pd.read_csv(f'{dataPath}generate2_1.csv')
data2 = pd.read_csv(f'{dataPath}left0_11_generate2_humorscore.csv')
gen2 = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
gen2.to_csv(f'{dataPath}left0_filtered_hc_generate2_2.csv', index=False)
gen2

,caption,image_id,fluency,diversity,humor_score,humor
0,what do you think is the best burger you have ...,mcdonalds_switzerland_1,0.785151,0.402572,0.721260,1
1,no matter how long it 's been since you 've ha...,mcdonalds_switzerland_203,0.961724,0.402572,0.260769,0
2,we all love the mcdonald 's fries but if you w...,mcdonalds_switzerland_7,0.970971,0.402572,0.033696,0
3,i 'm so excited i 'm going to pretend that i '...,mcdonalds_switzerland_13,0.922093,0.402572,0.730380,1
4,do you remember when mcdonald 's introduced th...,mcdonalds_switzerland_16,0.964276,0.402572,0.792373,1
...,...,...,...,...,...,...
558,i 'm sure you 'll enjoy this drink as much as ...,mcdonalds_switzerland_2064,0.944614,0.402572,0.049906,0
559,if you did n't take your son to the store for ...,mcdonalds_switzerland_2065,0.906624,0.402572,0.052329,0
560,it 's a new experience for me '' `` i 'm so ha...,mcdonalds_switzerland_2069,0.842196,0.402572,0.227840,0
561,"it 's not the sandwich that 's the problem, it...",mcdonalds_switzerland_2075,0.954572,0.402572,0.159430,0
562,are you ready for the mcdonald 's mcdonald 's ...,mcdonalds_switzerland_2077,0.869665,0.402572,0.146433,0

In [53]:
# clip_dataPath = './Model/bita/sd/'
# clip_dataPath = './Model/clip/clip_100up_only200_lessNotFunImg_169_55_passlength_10_SD_with_oxford_3000_only1_300_82/'
clip_dataPath = './Model/3000/ablation/MC/_woFCT_onlyLoRaadapt/'
dataPath = './Model/3000/ablation/MC/100up_only200_lessNotFunImg_53_171_passlength_12_MC_/'

data1 = pd.read_csv(f'{clip_dataPath}generate2_1.csv')
data2 = pd.read_csv(f'{clip_dataPath}left0_11_generate2_humorscore.csv')
gen2 = data1.merge(data2, on=['image_id','caption'], how='inner', suffixes=('', '_'))
gen2.to_csv(f'{clip_dataPath}left0_filtered_hc_generate2_2.csv', index=False)

mine = pd.read_csv(f'{dataPath}left0_final_56_gen2_ultra.csv')
clip_gen2 = pd.read_csv(f'{clip_dataPath}/left0_filtered_hc_generate2_2.csv')
# clip_beam = pd.read_csv(f'{clip_dataPath}/generate_beam_1.csv')
clip_gen2 = clip_gen2[clip_gen2['image_id'].isin(mine.image_id.unique())]
# clip_beam = clip_beam[clip_beam['image_id'].isin(mine.image_id.unique())]
clip_gen2['diversity'] = diversity(clip_gen2['caption'].to_list())
# clip_beam['diversity'] = diversity(clip_beam['caption'].to_list())
benign = pd.read_csv(f'../Citations/vilio/data/U36_mine_53_171_MC_woFCT_onlyLoRaadapt_generate2.csv')
# benign = pd.read_csv(f'../Citations/vilio/data/U36_mine_169_55_SD_woFCT_NOadapt_generate2.csv')
# benign = pd.read_csv(f'../Citations/vilio/data/U36_clip_SD_all_generate2_1.csv')
benign['image_id'] = benign['id']
clip_gen2 = clip_gen2.merge(benign[['image_id','proba']], on=['image_id'], how='inner', suffixes=('', '_'))
clip_gen2['benign'] = clip_gen2['proba']
clip_gen2 = clip_gen2.drop(columns=['proba'])
clip_gen2 = clip_gen2.drop(columns=['bleu1','bleu2','bleu3','bleu4'])
print(mine.shape,clip_gen2.shape)

(56, 21) (56, 9)

In [54]:
clip_gen2.to_csv(f'{clip_dataPath}/left0_final_56_gen2_ultra.csv', index=False)
# clip_beam.to_csv(f'{clip_dataPath}/final_beam_86_generate_beam_1.csv', index=False)

In [55]:
clip_gen2.describe()

,fitCount,gtNum,fluency,diversity,humor_score,humor,benign
count,56.000000,56.0,56.000000,56.000000,56.000000,56.000000,56.000000
mean,1.696429,1.0,0.891105,0.491361,0.297946,0.232143,-7.830699
std,1.536462,0.0,0.144646,0.000000,0.273505,0.426021,2.800973
min,0.000000,1.0,0.369724,0.491361,0.009793,0.000000,-9.858424
25%,0.000000,1.0,0.894168,0.491361,0.085087,0.000000,-9.213074
50%,2.000000,1.0,0.957080,0.491361,0.185364,0.000000,-8.936490
75%,3.000000,1.0,0.972879,0.491361,0.420949,0.000000,-8.006342
max,6.000000,1.0,0.982397,0.491361,0.968346,1.000000,-0.000633

In [460]:
hc_2 = pd.read_csv(f'{clip_dataPath}/0425_exchange_05_08_13_focal_08_17_temp050_7_generate2_humorscore.csv')
hc_2 = hc_2.drop(columns=['caption'])
clip_gen2 = clip_gen2.merge(hc_2, on=['image_id'], how='inner', suffixes=('', '_'))
# hc_beam = pd.read_csv(f'{clip_dataPath}/0425_exchange_05_08_13_focal_08_17_temp050_7_generate_beam_humorscore.csv')
# hc_beam = hc_beam.drop(columns=['caption'])
# clip_beam = clip_beam.merge(hc_beam, on=['image_id'], how='inner', suffixes=('', '_'))

In [107]:
dataPath = './Model/3000/100up_only200_lessNotFunImg_169_55_passlength_10_SD_base_0421_oxford_3000_only1_300_82_ESH_filter_cross_concat_combineLoss/'
mine = pd.read_csv(f'{dataPath}final_56_focal_08_17_filtered_hc_generate2_11_benign_gen2_ultra.csv')
clip_gen2 = pd.read_csv(f'./Model/bita/sd/generate2_1.csv')
clip_gen2 = clip_gen2[clip_gen2['image_id'].isin(mine.image_id.unique())]
clip_gen2['diversity'] = diversity(clip_gen2['caption'].to_list())
hc_2 = pd.read_csv(f'./Model/bita/sd/0425_exchange_05_08_13_focal_08_17_temp050_7_generate2_humorscore.csv')
hc_2 = hc_2.drop(columns=['caption'])
clip_gen2 = clip_gen2.merge(hc_2, on=['image_id'], how='inner', suffixes=('', '_'))
benign = pd.read_csv(f'../Citations/vilio/data/U36_bita_sd_all.csv')
benign['image_id'] = benign['id']
clip_gen2 = clip_gen2.merge(benign[['image_id','proba']], on=['image_id'], how='inner', suffixes=('', '_'))
clip_gen2['benign'] = clip_gen2['proba']
clip_gen2 = clip_gen2.drop(columns=['proba'])
print(mine.shape,clip_gen2.shape, clip_beam.shape)

FileNotFoundError: [Errno 2] No such file or directory: './Model/3000/100up_only200_lessNotFunImg_169_55_passlength_10_SD_base_0421_oxford_3000_only1_300_82_ESH_filter_cross_concat_combineLoss/final_56_focal_08_17_filtered_hc_generate2_11_benign_gen2_ultra.csv'

In [248]:
clip_gen2.to_csv(f'./Model/bita/sd/final_gen2_ultra_generate2_1.csv', index=False)

In [ ]:
clip_gen2.describe()