In [18]:
import pandas as pd
path = './Model/20250412_100up_only200_lessNotFunImg_169_55_passlength_10_SD_base_0410_oxford_1265_only1_300_82_ESH_filter_cross_concat_combineLoss\generate2_5.csv'
data = pd.read_csv(path)
data.columns
new_data = data[data.columns[:2]]
new_data['human_ins']=''
new_data['human_humor'] = ''
new_data['human_related'] = ''
new_data['overfit'] = ''
new_data = pd.concat([new_data, data[data.columns[2:]]], axis=1)
new_data.to_csv(path)

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_12588\3405793738.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_ins']=''
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_12588\3405793738.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_humor'] = ''
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_12588\3405793738.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['human_related'] = ''
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_12588\3405793738.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['overfit'] = ''

,image_id,caption,human_ins,human_humor,human_related,overfit,fitCount,gtNum,fluency,diversity,bleu1,bleu2,bleu3,bleu4
0,sonicdrivein_505,the # foodof the day is a chicken sandwich wit...,,,,,0,1,0.810365,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
1,sonicdrivein_65,"the first one who said, "" i don't know how to ...",,,,,2,1,0.836135,0.438491,0.153846,2.225074e-308,2.225074e-308,2.225074e-308
2,sonicdrivein_808,a few of my favorite brands are coming back fo...,,,,,5,1,0.931435,0.438491,0.166667,2.225074e-308,2.225074e-308,2.225074e-308
3,sonicdrivein_634,the first time i’ ve ever had a sandwich in my...,,,,,0,1,0.968221,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
4,sonicdrivein_1029,when you’ re craving something sweet and salty...,,,,,0,1,0.978385,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,sonicdrivein_1467,we're going to make a snowman today.,,,,,1,1,0.979966,0.438491,0.107354,1.672092e-308,1.672092e-308,1.672092e-308
182,sonicdrivein_89,it's the perfect way to end a long day at work.,,,,,0,1,0.974499,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
183,sonicdrivein_798,the one who’ s got a little bit of it in the end.,,,,,0,1,0.922994,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
184,sonicdrivein_470,i love this! i'm so excited to get my new dog ...,,,,,1,1,0.884971,0.438491,0.047619,2.225074e-308,2.225074e-308,2.225074e-308
185,sonicdrivein_1028,@ # thebestofthebests: this is our first post ...,,,,,0,1,0.943537,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00

In [19]:
data

,image_id,caption,fitCount,gtNum,fluency,diversity,bleu1,bleu2,bleu3,bleu4
0,sonicdrivein_505,the # foodof the day is a chicken sandwich wit...,0,1,0.810365,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
1,sonicdrivein_65,"the first one who said, "" i don't know how to ...",2,1,0.836135,0.438491,0.153846,2.225074e-308,2.225074e-308,2.225074e-308
2,sonicdrivein_808,a few of my favorite brands are coming back fo...,5,1,0.931435,0.438491,0.166667,2.225074e-308,2.225074e-308,2.225074e-308
3,sonicdrivein_634,the first time i’ ve ever had a sandwich in my...,0,1,0.968221,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
4,sonicdrivein_1029,when you’ re craving something sweet and salty...,0,1,0.978385,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
181,sonicdrivein_1467,we're going to make a snowman today.,1,1,0.979966,0.438491,0.107354,1.672092e-308,1.672092e-308,1.672092e-308
182,sonicdrivein_89,it's the perfect way to end a long day at work.,0,1,0.974499,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
183,sonicdrivein_798,the one who’ s got a little bit of it in the end.,0,1,0.922994,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
184,sonicdrivein_470,i love this! i'm so excited to get my new dog ...,1,1,0.884971,0.438491,0.047619,2.225074e-308,2.225074e-308,2.225074e-308
185,sonicdrivein_1028,@ # thebestofthebests: this is our first post ...,0,1,0.943537,0.438491,0.000000,0.000000e+00,0.000000e+00,0.000000e+00

In [153]:
import pandas as pd
dirPath = '../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix.csv'
data = pd.read_csv(dirPath)
data

,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated
0,bokete_2176,"lowercase ""y"".",0.007244,711.0,69.727273,0
1,bokete_2176,"anpanman, new face!",0.000132,13.0,69.727273,0
2,bokete_2176,it's a driving shot!,0.000122,12.0,69.727273,0
3,bokete_2176,"if it's not moving, it's going to leak ...",0.000061,6.0,69.727273,0
4,bokete_2176,fracture of left ankle,0.000061,6.0,69.727273,0
...,...,...,...,...,...,...
4901249,bokete_91043,don't give up!,0.001691,166.0,25.428571,0
4901250,bokete_91043,"all right! if you save everything, you'll be a...",0.000051,5.0,25.428571,0
4901251,bokete_91043,"""don't save it, save it!""",0.000020,2.0,25.428571,0
4901252,bokete_91043,"i gave in to temptation and opened it, but tha...",0.000020,2.0,25.428571,0
4901253,bokete_91043,(in all 500 yen balls),0.000000,0.0,25.428571,0

In [14]:
# counter group ['image_id', 'funny_score_y']
data['counter'] = data.groupby(['image_id', 'funny_score_y'])['caption'].transform('count')

In [154]:
data= pd.read_csv('../../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix_filter.csv')
data = data[data['counter'] >298].sort_values(by=['image_id', 'funny_score_y'], ascending=[True, False])

In [179]:
i = 14
img = data['image_id'].unique()[i]
print(img)
data[data['image_id'] == img].counter.unique()

bokete_101650

array([ 667,  551, 1274, 2797, 7581])

In [176]:
data[data['image_id'] == img]

,Unnamed: 0,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated,counter
68260,1241340,bokete_101574,it's a ring pin that never falls.,0.00002,2.0,38.0,0,1080
68261,1241341,bokete_101574,"i said, ""i'm going to get down first.""",0.00002,2.0,38.0,0,1080
68262,1241342,bokete_101574,a guide that allows tapioca smooth through the...,0.00002,2.0,38.0,0,1080
68263,1241343,bokete_101574,it's a misunderstanding! i wasn't staying up a...,0.00002,2.0,38.0,0,1080
68264,1241344,bokete_101574,i told you to bring a dryer! can you dry my ha...,0.00002,2.0,38.0,0,1080
...,...,...,...,...,...,...,...,...
74820,1287631,bokete_101574,i 've got a long way to go until i get home fr...,0.00000,0.0,38.0,1,3614
74821,1287632,bokete_101574,i 've got a long way to go until i get home to...,0.00000,0.0,38.0,1,3614
74822,1287633,bokete_101574,i 've got a long way to go until i get home . ...,0.00000,0.0,38.0,1,3614
74823,1287634,bokete_101574,i 've got a long way to go until i get home an...,0.00000,0.0,38.0,1,3614
74824,1287635,bokete_101574,"i 've got a long way to go until i get home , ...",0.00000,0.0,38.0,1,3614

In [177]:
data[data['image_id'] == img][7+146+63+198:7+146+63+198+236]
# data[data['image_id'] == img][7+146+63+198+236+177:7+146+63+198+236+177+253]

,Unnamed: 0,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated,counter
68674,1244283,bokete_101574,I told you to bring a dryer! can you dry my ha...,0.00002,2.0,38.0,1,1080
68675,1244284,bokete_101574,We told you to bring a dryer! can you dry my h...,0.00002,2.0,38.0,1,1080
68676,1244285,bokete_101574,They told you to bring a dryer! can you dry my...,0.00002,2.0,38.0,1,1080
68677,1244286,bokete_101574,Someone told you to bring a dryer! can you dry...,0.00002,2.0,38.0,1,1080
68678,1244287,bokete_101574,i need you to bring a dryer! can you dry my ha...,0.00002,2.0,38.0,1,1080
...,...,...,...,...,...,...,...,...
68905,1244514,bokete_101574,i told you to bring a dryer! can you dry my in...,0.00002,2.0,38.0,1,1080
68906,1244515,bokete_101574,i told you to bring a dryer! can you dry your ...,0.00002,2.0,38.0,1,1080
68907,1244516,bokete_101574,i told you to bring a dryer! can you dry it cl...,0.00002,2.0,38.0,1,1080
68908,1244517,bokete_101574,i told you to bring a dryer! can you dry the y...,0.00002,2.0,38.0,1,1080
68909,1244518,bokete_101574,i told you to bring a dryer! can you dry this ...,0.00002,2.0,38.0,1,1080

In [178]:
temp = data[data['image_id'] == img][7+146+63+198:7+146+63+198+236]
# new_data = data[data['image_id'] == 'bokete_100219'][:385]
new_data = pd.concat([new_data, temp])
new_data.to_csv('../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix_filter_done.csv')
new_data.shape

(3539, 8)

In [135]:
new_data

,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated,counter
1156120,bokete_100219,"""you know, don't give up your asthma every tim...",0.000082,8.0,1637.000000,0,385
1170568,bokete_100219,"And you know, do n't give up your asthma every...",0.000082,8.0,1637.000000,1,385
1170569,bokete_100219,"But you know, do n't give up your asthma every...",0.000082,8.0,1637.000000,1,385
1170570,bokete_100219,"So you know, do n't give up your asthma every ...",0.000082,8.0,1637.000000,1,385
1170571,bokete_100219,"Now you know, do n't give up your asthma every...",0.000082,8.0,1637.000000,1,385
...,...,...,...,...,...,...,...
1225705,bokete_101023,it was n't until i got there that i realized t...,0.000031,3.0,71.730159,1,950
1225706,bokete_101023,it was n't until i got there that i realized t...,0.000031,3.0,71.730159,1,950
1225707,bokete_101023,it was n't until i got there that i realized t...,0.000031,3.0,71.730159,1,950
1225708,bokete_101023,it was n't until i got there that i realized t...,0.000031,3.0,71.730159,1,950
1225709,bokete_101023,it was n't until i got there that i realized t...,0.000031,3.0,71.730159,1,950

In [10]:

dirPath = './Generate_bert_top1000_oxford_mix.csv'
data = pd.read_csv(dirPath)
image_id_counts = data['image_id'].value_counts()
data['caption'] = data['caption'].str.lower()
data['funny_score'] = data['funny_score_y']
# normalize the funny_score
data['funny_score'] = (data['funny_score'] - data['funny_score'].min()) / (data['funny_score'].max() - data['funny_score'].min())

valid_image_ids = image_id_counts[image_id_counts >= 800].index
filtered_data = data[data['image_id'].isin(valid_image_ids)]
print(f'Number of image_id with 800 captions: {len(valid_image_ids)}')
split = filtered_data.groupby('image_id').head(1)
train_img = set(split.sort_values(by=['fc_mean'], ascending=[False])[:1120].image_id.tolist())

valid_image_ids = image_id_counts[image_id_counts >= 300].index
filtered_data = data[data['image_id'].isin(valid_image_ids)]
print(f'Number of image_id with 300 captions: {len(valid_image_ids)}')
test_img = set(filtered_data.image_id.tolist()).difference(train_img)
print(f'train_img: {len(train_img)}, test_img: {len(test_img)}')

train_data = filtered_data[filtered_data['image_id'].isin(train_img)]
test_data = filtered_data[filtered_data['image_id'].isin(test_img)]
print(f'train_data: {train_data.shape}, test_data: {test_data.shape}')

shape of data:  (460574, 3)

,caption,image_id,funny_score,text_len,gen_count
0,consider this a wake up call for more fun. 🥤#l...,sonicdrivein_0,0.0,10,182
2,@parishilton and @nicolerichie returned to the...,sonicdrivein_2,0.0,13,161
8,we picked up a few new faces for our superfan ...,sonicdrivein_8,0.0,16,175
11,no but how do we know what blue tastes like,sonicdrivein_11,0.0,10,173
12,boss asked me to make something cool...what is...,sonicdrivein_12,0.0,12,221
...,...,...,...,...,...
2224,"and, the gold medal goes to the greenbrier go...",sonicdrivein_2235,0.0,22,237
2225,congrats to nate s. who was crowned the inner ...,sonicdrivein_2236,0.0,13,116
2226,"sonicland has moved to san antonio, tex. this ...",sonicdrivein_2237,0.0,13,206
2227,best skaters in all of sonicland!! sonic skate...,sonicdrivein_2238,0.0,15,147
2228,sonic ceo cliff hudson interviewing with @news...,sonicdrivein_2239,0.0,19,163

In [11]:
import shutil
for img in set(original.image_id.tolist()):
    src = f'../Data/Instagram/sonicdrivein_img/{img}.jpg'
    dst = f'../Data/Instagram/filter_SD_img/{img}.jpg'
    shutil.copyfile(src, dst)

In [2]:
# Prediction interface for Cog ⚙️
# Reference: https://github.com/replicate/cog/blob/main/docs/python.md
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import sys
# sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import torch
import torch.nn as nn
from torch import Tensor
from torch.nn import functional as nnf
from torch.utils.data import Dataset, DataLoader
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    AdamW,
    get_linear_schedule_with_warmup,
)
from transformers import AutoConfig, AutoTokenizer, Gemma2ForCausalLM
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, TaskType, get_peft_model
import PIL.Image
from typing import Tuple, Optional, Union, Any
from tqdm import tqdm
import os
import pickle
from typing import Tuple, Optional, Union, Any
from typing import Tuple, List, Union, Optional
import numpy as np
import pandas as pd
from peft import LoraConfig, TaskType, get_peft_model
from nltk.translate.bleu_score import sentence_bleu
import gc
import loralib as lora
from Citations.Parrot_Paraphraser.parrot.filters import Fluency
from scipy.special import softmax
import clip
import ast


N = type(None)
V = np.array
ARRAY = np.ndarray
ARRAYS = Union[Tuple[ARRAY, ...], List[ARRAY]]
VS = Union[Tuple[V, ...], List[V]]
VN = Union[V, N]
VNS = Union[VS, N]
T = torch.Tensor
TS = Union[Tuple[T, ...], List[T]]
TN = Optional[T]
TNS = Union[Tuple[TN, ...], List[TN]]
TSN = Optional[TS]
TA = Union[T, ARRAY]
WEIGHTS_PATHS = {
    "coco": "coco_weights.pt",
    "conceptual-captions": "conceptual_weights.pt",
}
D = torch.device
CPU = torch.device("cpu")



class OxfordDataset(torch.utils.data.Dataset):
    def __len__(self) -> int:
        return len(self.captions_tokens)

    def pad_tokens(self, item: int):
        tokens = self.captions_tokens[item].cpu()
        padding = self.max_seq_len - tokens.shape[0]
        if padding > 0:
            tokens = torch.cat((tokens, torch.zeros(padding, dtype=torch.int64) - 1))
            self.captions_tokens[item] = tokens
        elif padding < 0:
            tokens = tokens[:self.max_seq_len]
            self.captions_tokens[item] = tokens
        mask = tokens.ge(0)  # mask is zero where we out of sequence
        tokens[~mask] = 0
        mask = mask.float()
        mask = torch.cat((torch.ones(self.prefix_length), mask), dim=0)  # adding prefix mask
        return tokens, mask

    def pad_emotion(self, item: int):
        emotion = self.emotion[self.image_ids[item]]
        sentiment = self.sentiment[self.image_ids[item]]
        humor = self.humor[self.image_ids[item]]
        padding_emotion = self.max_seq_len_emo - emotion.shape[0]
        padding_sentiment = self.max_seq_len_emo - sentiment.shape[0]
        padding_humor = self.max_seq_len_emo - humor.shape[0]
        if padding_emotion > 0:
            emotion = torch.cat((emotion, torch.zeros(padding_emotion, dtype=torch.int64)))
        elif padding_emotion < 0:
            emotion = emotion[:self.max_seq_len_emo]
        if padding_sentiment > 0:
            sentiment = torch.cat((sentiment, torch.zeros(padding_sentiment, dtype=torch.int64)))
        elif padding_sentiment < 0:
            sentiment = sentiment[:self.max_seq_len_emo]
        if padding_humor > 0:
            humor = torch.cat((humor, torch.zeros(padding_humor, dtype=torch.int64)))
        elif padding_humor < 0:
            humor = humor[:self.max_seq_len_emo]

        return emotion, sentiment, humor

    def __getitem__(self, item: int) -> tuple[Tensor, Tensor, Any, int, Tensor, Tensor, Tensor, Any, Any, Any]:
        tokens, mask = self.pad_tokens(item)
        if self.dataFrom == 'Oxford':
            prefix = torch.load('../../Oxford_HIC/ImageData/' + self.image_ids[item] + '.pt', weights_only=False)
        else:
            prefix = torch.load('../../Instagram/ImageData/' + self.dataFrom + '/' + self.image_ids[item] + '.pt',
                                weights_only=False)
        # emotion, sentiment, humor = self.pad_emotion(item)
        emotion, sentiment, humor = self.emotion[self.image_ids[item]], self.sentiment[self.image_ids[item]], self.humor[self.image_ids[item]]
        if self.normalize_prefix:
            prefix = prefix.float()
            prefix = prefix / prefix.norm(2, -1)
        funnyscore = self.funny_scores[item]
        image_id = self.image_ids[item]
        caption = self.captions[item]
        return tokens, mask, prefix, item, emotion, sentiment, humor, funnyscore

        # return tokens, mask, prefix, item, emotion, sentiment, humor, funnyscore, image_id, caption

    def filter_data_by_bleu(self, model, batch_size=20, bleu_threshold=0.1, file_path=None):
        """
        Filter dataset based on BLEU scores using batch processing.

        Args:
            model: The model used for generating sentences.
            batch_size: Number of samples per batch.
            bleu_threshold: Minimum BLEU score to keep a sample.
        """
        dataloader = DataLoader(self, batch_size=batch_size, shuffle=False, drop_last=True)

        # Temporary storage for filtered indices
        filtered_indices = []
        device = torch.device('cuda:0')

        progress = tqdm(total=len(dataloader), desc="Filtering train dataset")
        for batch in dataloader:
            tokens_batch, masks_batch, prefixes_batch, original_indices = batch
            tokens_batch, masks_batch, prefixes_batch = tokens_batch.to(device), masks_batch.to(
                device), prefixes_batch.to(device, dtype=torch.bfloat16)

            # Forward pass
            prefix_embeds = model.clip_project(prefixes_batch).view(-1, self.prefix_length, model.embedding_size)
            text_embeds = model.falcon.model.embed_tokens(tokens_batch)
            embedding_cat = torch.cat((prefix_embeds, text_embeds), dim=1)
            outputs = model.falcon(inputs_embeds=embedding_cat, attention_mask=masks_batch)
            logits = outputs.logits[:, self.prefix_length - 1:-1]
            generated_tokens_batch = torch.argmax(logits, dim=-1)

            # BLEU calculation and filtering
            for i, original_idx in enumerate(original_indices):
                reference = self.captions_tokens[original_idx].tolist()
                candidate = generated_tokens_batch[i].tolist()
                bleu_score = sentence_bleu([reference], candidate, weights=(1, 0, 0, 0))

                if bleu_score <= bleu_threshold:
                    filtered_indices.append(original_idx)
            progress.update()

        # Update dataset based on filtered indices
        print(f"Before Filtered: {len(self.captions_tokens)}, After Filtered: {len(filtered_indices)}, BLEU <= {bleu_threshold}")
        self.captions = [self.captions[i] for i in filtered_indices]
        self.image_ids = [self.image_ids[i] for i in filtered_indices]
        self.captions_tokens = [self.captions_tokens[i] for i in filtered_indices]
        self.caption2embedding = [self.caption2embedding[i] for i in filtered_indices]
        del tokens_batch, masks_batch, prefixes_batch, original_indices, prefix_embeds, text_embeds, embedding_cat, outputs, logits, generated_tokens_batch, reference, candidate, bleu_score
        gc.collect()
        torch.cuda.empty_cache()

    def __init__(self, data_path: str, prefix_length: int, gpt2_type: str = "gpt2", normalize_prefix=False, model=None,
                 batch_size=30, bleu_threshold=0.4, dataFrom='Oxford'):
        self.data_path = data_path
        self.dataFrom = dataFrom
        self.bleu = False
        # self.tokenizer = GPT2Tokenizer.from_pretrained(gpt2_type)
        # self.tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
        self.tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
        # self.tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")
        # self.tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")
        # self.tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-2.7B")
        self.prefix_length = prefix_length
        self.normalize_prefix = normalize_prefix
        with open(data_path, 'rb') as f:
            all_data = pickle.load(f)
        sys.stdout.flush()
        self.prefixes = all_data["clip_embedding"]
        captions_raw = all_data["captions"]
        self.funny_scores = all_data["funnyscore"]
        self.image_ids = [caption["image_id"] for caption in captions_raw]
        self.captions = [caption['caption'] for caption in captions_raw]
        if os.path.isfile(f"{data_path[:-4]}_bleu_all.pkl"):
            del all_data
            gc.collect()
            torch.cuda.empty_cache()
            with open(f"{data_path[:-4]}_bleu_all.pkl", 'rb') as f:
                self.captions_tokens, self.caption2embedding, self.max_seq_len = pickle.load(f)
        else:
            self.captions_tokens = []
            self.caption2embedding = []
            max_seq_len = 64
            for caption in captions_raw:
                self.captions_tokens.append(torch.tensor(self.tokenizer.encode(caption['caption'], max_length=64, truncation=True),dtype=torch.int64))
                self.caption2embedding.append(caption["clip_embedding"])
                max_seq_len = max(max_seq_len, self.captions_tokens[-1].shape[0])
            self.max_seq_len = max_seq_len
            with open(f"{self.data_path[:-4]}_bleu_all.pkl", 'wb') as f:
                pickle.dump([self.captions_tokens, self.caption2embedding, self.max_seq_len], f)
        if dataFrom == 'Oxford':
            # self.emotions_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_Oxford.csv')
            # self.emotions_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_Oxford_filter.csv')
            # self.emotions_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford.csv')
            self.emotions_data = pd.read_csv('../../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_bert.csv')
            # self.emotion_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_Oxford_emotion_filter.csv')
            # self.sentiment_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_Oxford_sentiment_filter.csv')
            # self.humor_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_Oxford_humor_filter.csv')
        else:
            # self.emotions_data = pd.read_csv(f'../Data/Instagram/Minigpt4_{dataFrom}.csv')
            # self.emotions_data = pd.read_csv(f'../Data/Instagram/Minigpt4_{dataFrom}_filter.csv')
            # self.emotions_data = pd.read_csv(f'../Data/Instagram/Minigpt4_sentence_{dataFrom}.csv')
            self.emotions_data = pd.read_csv(f'../Data/Instagram/Minigpt4_sentence_{dataFrom}_bert.csv')
            # self.emotion_data = pd.read_csv(f'../Data/Instagram/Minigpt4_{dataFrom}_emotion_filter.csv')
            # self.sentiment_data = pd.read_csv(f'../Data/Instagram/Minigpt4_{dataFrom}_sentiment_filter.csv')
            # self.humor_data = pd.read_csv(f'../Data/Instagram/Minigpt4_{dataFrom}_humor_filter.csv')
        # self.emotion will save the emotion data for each image
        self.emotion = dict()
        self.sentiment = dict()
        self.humor = dict()

        # self.max_seq_len_emo = 21
        # for i in range(self.emotions_data.shape[0]):
        #     image_id = self.emotions_data.iloc[i]['image_id']
        #     emotion = str(self.emotions_data.iloc[i]['emotion']).replace(';', ' ')
        #     sentiment = str(self.emotions_data.iloc[i]['sentiment']).replace(';', ' ')
        #     humor = str(self.emotions_data.iloc[i]['humor']).replace(';', ' ')
        #     self.emotion[image_id] = torch.tensor(self.tokenizer.encode(emotion, max_length=64, truncation=True), dtype=torch.int64)
        #     self.sentiment[image_id] = torch.tensor(self.tokenizer.encode(sentiment, max_length=64, truncation=True), dtype=torch.int64)
        #     self.humor[image_id] = torch.tensor(self.tokenizer.encode(humor, max_length=64, truncation=True, padding=True), dtype=torch.int64)

        # padding_emotion = 384 - (self.emotion_data.shape[1] - 1)
        # padding_sentiment = 384 - (self.sentiment_data.shape[1] - 1)
        # padding_humor = 768 - (self.humor_data.shape[1] - 1)
        # for i in range(self.emotion_data.shape[0]):
        #     image_id = self.emotion_data.iloc[i]['image_id']
        #     emotion = torch.tensor(self.emotion_data.iloc[i][1:].tolist())
        #     self.emotion[image_id] = torch.cat((emotion, torch.zeros(padding_emotion, dtype=torch.int64)))
        #     sentiment = torch.tensor(self.sentiment_data.iloc[i][1:].tolist())
        #     self.sentiment[image_id] = torch.cat((sentiment, torch.zeros(padding_sentiment, dtype=torch.int64)))
        #     humor = torch.tensor(self.humor_data.iloc[i][1:].tolist())
        #     self.humor[image_id] = torch.cat((humor, torch.zeros(padding_humor, dtype=torch.int64)))
        with tqdm(total=self.emotions_data.shape[0]) as pbar:
            for i in range(self.emotions_data.shape[0]):
                image_id = self.emotions_data.iloc[i]['image_id']
                if image_id in self.image_ids:
                    self.emotion[image_id] = torch.tensor(ast.literal_eval(self.emotions_data.iloc[i]['emotion']))
                    self.sentiment[image_id] = torch.tensor(ast.literal_eval(self.emotions_data.iloc[i]['sentiment']))
                    self.humor[image_id] = torch.tensor(ast.literal_eval(self.emotions_data.iloc[i]['humor']))
                pbar.update(1)
            pbar.close()
        del self.emotions_data
        gc.collect()
        print(f"Train Data size: {len(self.captions_tokens)}")
        # self.filter_data_by_bleu(model, batch_size, bleu_threshold)

class ClipCocoDataset(Dataset):

    def __len__(self) -> int:
        return len(self.captions_tokens)

    def pad_tokens(self, item: int):
        tokens = self.captions_tokens[item]
        padding = self.max_seq_len - tokens.shape[0]
        if padding > 0:
            tokens = torch.cat((tokens, torch.zeros(padding, dtype=torch.int64) - 1))
            self.captions_tokens[item] = tokens
        elif padding < 0:
            tokens = tokens[:self.max_seq_len]
            self.captions_tokens[item] = tokens
        mask = tokens.ge(0)  # mask is zero where we out of sequence
        tokens[~mask] = 0
        mask = mask.float()
        mask = torch.cat((torch.ones(self.prefix_length), mask), dim=0)  # adding prefix mask
        return tokens, mask

    def __getitem__(self, item: int) -> Tuple[torch.Tensor, ...]:
        tokens, mask = self.pad_tokens(item)
        prefix = self.prefixes[self.caption2embedding[item]]
        if self.normalize_prefix:
            prefix = prefix.float()
            prefix = prefix / prefix.norm(2, -1)
        return tokens, mask, prefix

    def __init__(self, data_path: str, prefix_length: int, gpt2_type: str = "gpt2",
                 normalize_prefix=False):
        # self.tokenizer = GPT2Tokenizer.from_pretrained(gpt2_type)
        # self.tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
        self.tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
        self.prefix_length = prefix_length
        self.normalize_prefix = normalize_prefix
        with open(data_path, 'rb') as f:
            all_data = pickle.load(f)
        print("Data size is %0d" % len(all_data["clip_embedding"]))
        sys.stdout.flush()
        self.prefixes = all_data["clip_embedding"]
        captions_raw = all_data["captions"]
        self.image_ids = [caption["image_id"] for caption in captions_raw]
        self.captions = [caption['caption'] for caption in captions_raw]
        if os.path.isfile(f"{data_path[:-4]}_tokens.pkl"):
            with open(f"{data_path[:-4]}_tokens.pkl", 'rb') as f:
                self.captions_tokens, self.caption2embedding, self.max_seq_len = pickle.load(f)
        else:
            self.captions_tokens = []
            self.caption2embedding = []
            max_seq_len = 0
            for caption in captions_raw:
                self.captions_tokens.append(torch.tensor(self.tokenizer.encode(caption['caption']), dtype=torch.int64))
                self.caption2embedding.append(caption["clip_embedding"])
                max_seq_len = max(max_seq_len, self.captions_tokens[-1].shape[0])
            # self.max_seq_len = max_seq_len
            with open(f"{data_path[:-4]}_tokens.pkl", 'wb') as f:
                pickle.dump([self.captions_tokens, self.caption2embedding, max_seq_len], f)
        all_len = torch.tensor([len(self.captions_tokens[i]) for i in range(len(self))]).float()
        self.max_seq_len = min(int(all_len.mean() + all_len.std() * 10), int(all_len.max()))


# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device = torch.device("cpu")
trainData = '../Data/Oxford_HIC/parse/oxford_1408_300_8_300_2_ViT-B_32_train.pkl'
testData = '../Data/Oxford_HIC/parse/oxford_1408_300_8_300_2_ViT-B_32_test.pkl'
# trainData = '../Data/Instagram/parse/100up_only200_passlength_12_o_mcdonalds_switzerland_ViT-B_32_train.pkl'
# testData = '../Data/Instagram/parse/100up_only200_passlength_12_x_mcdonalds_switzerland_ViT-B_32_test.pkl'
# testData = '../Data/Instagram/parse/100up_only100_passlength_x_10_sonicdrivein_ViT-B_32_test.pkl'
prefix_length = 64
normalize_prefix = False
train_dataform = "Oxford"
trainDataset = OxfordDataset(trainData, prefix_length, normalize_prefix=normalize_prefix, dataFrom = train_dataform)
test_dataform = "Oxford"
testDataset = OxfordDataset(testData, prefix_length, normalize_prefix=normalize_prefix, dataFrom = test_dataform)
# train_dataform = None
# test_dataform = None

if train_dataform:
    ##################### oxford_300k #####################
    # train_image = ['imgflip_34', 'bokete_3820', 'imgflip_0','imgflip_8', 'imgflip_15', 'imgflip_19', 'bokete_104530','imgflip_730', 'imgflip_130', 'imgflip_677']
    # train_text = ['You finish doing something at your friends house and look at your phone; 7 missed calls from your mom; 7 missed calls from your mom'
    #               ,'I\'m in my 50s!'
    #               ,'School; Memes'
    #               ,'image tagged in memes,one does not simply'
    #               ,'THAT; IS WHAT A GOOD MEME LOOKS LIKE'
    #               ,'NOT SURE IF PEOPLE ARE UPVOTING MEMES; OR USER NAMES'
    #               ,'It\'s a family night runaway.'
    #               ,'CHUCK IS THE GOOD TYPE OF SCUMBAG; CUZ HE ONLY ROASTS YOU FROM YOUR INSIDES'
    #               ,'SO YOUR TELLIN\' ME THAT SCHOOLS GOOD FOR YOU'
    #               ,'Y\'ALL GOT ANY MORE OF THEM; JOBS?']
    ##################### oxford_100k #####################
    # train_image = ['imgflip_34', 'bokete_3820', 'imgflip_0','imgflip_8', 'imgflip_15', 'imgflip_19', 'bokete_104530','imgflip_730', 'imgflip_130', 'imgflip_677']
    # train_text = ['You finish doing something at your friends house and look at your phone; 7 missed calls from your mom; 7 missed calls from your mom'
    #               ,'I\'m in my 50s!'
    #               ,'School; Memes'
    #               ,'image tagged in memes,one does not simply'
    #               ,'THAT; IS WHAT A GOOD MEME LOOKS LIKE'
    #               ,'NOT SURE IF PEOPLE ARE UPVOTING MEMES; OR USER NAMES'
    #               ,'It\'s a family night runaway.'
    #               ,'Chuck Norris doesn\'t go washroom; He goes washBOOM!'
    #               ,'SO YOUR TELLIN\' ME THAT SCHOOLS GOOD FOR YOU'
    #               ,'Y\'ALL GOT ANY MORE OF THEM; JOBS?']
    ##################### oxford_Top10_300k #####################
    # train_image = ['bokete_100136', 'bokete_100144', 'bokete_100174','bokete_100193', 'bokete_100268', 'bokete_100287', 'bokete_100295','bokete_10031', 'bokete_100498', 'bokete_24339']
    # train_text = ['The wax isn\'t dry yet.'
    #               ,'I\'m sorry to hear that.'
    #               ,'You didn\'t put that microphone in the register, did you?'
    #               ,'I\'m showing my brother the privilege of being the youngest.'
    #               ,'Are you ready to join us?'
    #               ,'He\'s cute, he\'s 100% capable of killing.'
    #               ,'The ground suddenly fell to the left.'
    #               ,'"Mama, there\'s something in the front mat!"'
    #               ,'"You don\'t have a dad?" "You don\'t have a mom?"'
    #               ,'This month, I\'ve only got this much to offer.']
    ##################### oxford_Top10_300k_mess #####################
    # train_image = ['bokete_100345', 'bokete_100360', 'bokete_100364','bokete_100193', 'bokete_100372', 'bokete_100432', 'bokete_100295','bokete_100453', 'bokete_100498', 'bokete_100459']
    # train_text = ['I had a dream about going to school, so I want to take a day off from school.'
    #               ,'I went to the woods for a jog, and there was a lot of spider webs.'
    #               ,'I\'d like to ask you a different color.'
    #               ,'I\'m showing my brother the privilege of being the youngest.'
    #               ,'Ah! You bumped into me in the morning!'
    #               ,'Are you sure it\'s your dad who left you when you were three?'
    #               ,'The ground suddenly fell to the left.'
    #               ,'In the first place, there\'s a problem with Snow White, who eats apples given to an old lady who looks so bad.'
    #               ,'It was at this time that they switched.'
    #               ,'Did you think it was corn?']
    ##################### oxford_Only1200_300k #####################
    # train_image = ['imgflip_0', 'imgflip_101', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_47', 'imgflip_504']
    # train_text = ['12 dollars; 11 dollars with 1 dollar shipping'
    #               ,'I HAD A GIRLFRIEND; AAAAAAND ITS GONE'
    #               ,'I POUR THE CEREAL AFTER I POUR THE MILK'
    #               ,'WAITING FOR MY PHONE TO GET  TO 100%'
    #               ,'You when you have over one test at school in a day'
    #               ,'IF SOMEONE WANTS TO KILL YOU; GO TO A LIVING ROOM'
    #               ,'you; eating 5 pounds of cheese; every day; your stomach'
    #               ,'Me:stands up to stretch my legs; The person who had been pushing my wheelchair for the last 26 years'
    #               ,'Me: Opens door for some fresh air; Everyone else in the submarine:'
    #               ,'THEY TOOK AWAY MY HAPPY MEAL I TOOK AWAY THEIR HAPPINESS']
    ##################### oxford_Only100_300k #####################
    # train_image = ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504']
    # train_text = ['climb a mountain? pff, i have wings...'
    #               ,'go to a pizza buffet eat all the pizza'
    #               ,'12 dollars; 11 dollars with 1 dollar shipping'
    #               ,'I POUR MILK BEFORE CEREAL'
    #               ,'ME WAITING FOR MY INTERNET TO RECONNECT'
    #               ,'calling the teacher mom'
    #               ,'IF SOMEONE DIES IN THE LIVING ROOM... IS IT STILL CALLED THE LIVING ROOM?'
    #               ,'you; losing a few seconds of your life looking at this'
    #               ,'me: gets up and starts clapping because the chiefs won; the guy who has been pushing my wheelchair for 10 years'
    #               ,'THEY TOOK AWAY MY HAPPY MEAL I TOOK AWAY THEIR HAPPINESS']
    ##################### oxford_only10 #####################
    # train_image = ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504']
    # train_text = ['i\'ll take it sure ur not chicken?',
    #               'avoid all the work',
    #               'due tomorrow; do tomorrow',
    #               'i want to speak to your manager',
    #               'school: *closes*; the kid who was in the bathroom:',
    #               'almost getting pass an extremely hard level but failing last minute',
    #               'you can\'t lose your mind; if you don\'t have one',
    #               'you; doing nothing; today; teacher',
    #               'students: *acting crazy*; teacher: pay attention! that kid named attention:',
    #               'they called me four eyes. i call them no eyes.']
    ####################### default #######################
    train_image = []
    train_text = []
    for i in range(len(trainDataset)):
        caption = trainDataset.captions[i]
        image_id = trainDataset.image_ids[i]
        if image_id not in train_image:
            print(f"Image ID: {image_id}, Caption: {caption}")
            train_image.append(image_id)
            train_text.append(caption)
            if len(train_image) == 10:
                break
    #######################################################
    tokens_list = []
    mask_list = []
    prefix_list = []
    train_emotion_list = []
    train_sentiment_list = []
    train_humor_list = []
    train_funnyscore = []
    train_gt = []
    train_caption = dict()
    train_image_id_list = []
    if train_dataform != "Oxford":
        load = pd.read_csv(f'../Data/Instagram/CaptionID_{train_dataform}.csv')
        load['caption'] = load['caption'].str.lower()
        train_text = []
        for i in range(len(train_image)):
            caption = load[load['image_id'] == train_image[i]]['caption'].values[0]
            train_text.append(caption)
        inside = []
        for i in range(len(trainDataset)):
            caption = trainDataset.captions[i]
            image_id = trainDataset.image_ids[i]
            if image_id in train_image and image_id not in train_image_id_list:
                train_caption[image_id] = []
                train_caption[image_id].append(caption)
                tokens, mask, prefix, item, emotion, sentiment, humor, funnyscore = trainDataset[i]
                tokens_list.append(tokens)
                mask_list.append(mask)
                prefix_list.append(prefix)
                # emotion, sentiment, humor = trainDataset.pad_emotion(item)
                train_emotion_list.append(emotion)
                train_sentiment_list.append(sentiment)
                train_humor_list.append(humor)
                train_funnyscore.append(funnyscore)
                train_gt.append(caption)

                train_image_id_list.append(image_id)
    else:
        for i in range(len(trainDataset)):
            caption = trainDataset.captions[i]
            image_id = trainDataset.image_ids[i]
            if image_id in train_image:
                if train_caption.get(image_id) is not None:
                    train_caption[image_id].append(caption)
                else:
                    train_caption[image_id] = []
                    train_caption[image_id].append(caption)
                if caption in train_text and image_id not in train_image_id_list:
                    tokens, mask, prefix, item, emotion, sentiment, humor, funnyscore = trainDataset[i]
                    tokens_list.append(tokens)
                    mask_list.append(mask)
                    prefix_list.append(prefix)
                    train_gt.append(caption)
                    # emotion, sentiment, humor = trainDataset.pad_emotion(item)
                    train_emotion_list.append(emotion)
                    train_sentiment_list.append(sentiment)
                    train_humor_list.append(humor)
                    train_funnyscore.append(funnyscore)
                    train_image_id_list.append(image_id)
    train_tokens = torch.stack(tokens_list).to(device)
    train_mask = torch.stack(mask_list).to(device)
    train_prefix = torch.stack(prefix_list).to(device)
    train_emotion = torch.stack(train_emotion_list).to(device)
    train_sentiment = torch.stack(train_sentiment_list).to(device)
    train_humor = torch.stack(train_humor_list).to(device)
    train_funnyscore = torch.tensor(train_funnyscore).to(device)
    print(train_tokens.shape, train_mask.shape, train_prefix.shape, len(train_image_id_list))
    print(train_emotion.shape, train_sentiment.shape, train_humor.shape, train_funnyscore.shape)

if test_dataform:
    ##################### oxford_300k #####################
    # test_image = ['imgflip_7', 'imgflip_32']
    # test_text = ['CHEESE; ME AT 3 AM; CHEESE; MY MOM WHO WAS WAITING; ME'
    #               ,'IS THIS A PIGEON?']
    ##################### oxford_100k #####################
    # test_image = ['imgflip_7', 'imgflip_32']
    # test_text = ['THE DOG FOOD; MY DOG; DOG FOOD; ME LOOKING AT HIM; MY DOG'
    #               ,'MATH; ME; IS THIS THE REASON I DROPPED OUT OF COLLEGE?']
    ##################### oxford_10 k #####################
    # test_image = ['bokete_111723', 'imgflip_57']
    # test_text = ['I\'m going to take care of you. I\'m going to take care of you. I\'m going to take care of you.'
    #               ,'WHAT\'S DONE IN THE DARK WILL ALWAYS COME OUT IN THE LIGHT; BUT THATS NONE OF MY BUSINESS']
    ##################### oxford_Top10_300k ###############
    # test_image = ['are-you-serious-face', 'bokete_24326']
    # test_text = ['you have windows 98 seriously?'
    #               ,'The answer is 10.']
    ##################### oxford_Top10_300k_mess ##########
    # test_image = ['imgflip_156', 'bokete_24326']
    # test_text = ['Friend: I just had a dream in which I married my crush! My dreams:'
    #               ,'The answer is 10.']
    ##################### oxford_Only1200_300k ############
    # test_image = ['imgflip_130', 'imgflip_659']
    # test_text = ['0 VIEWS 5 DISLIKES'
    #               ,'when the mobile game ad is so laggy that it crashes your game and you lose out on a reward:']
    ##################### oxford_Only100_300k #############
    # test_image = ['i-love-coloring-kid', 'imgflip_130']
    # test_text = ['she started writing notes !!'
    #               ,'WHEN YOUR FRIEND; DOSENT LIKE ROOT BEER']
    ##################### oxford_only10 ###################
    # test_image = ['bokete_100174', 'imgflip_834']
    # test_text = ['get out of my way. i\'ll do it.'
    #                 ,'me fully prepared for the test; question 1']
    ####################### default #######################
    test_image = []
    test_text = []
    test_emotion_list = []
    test_sentiment_list = []
    test_humor_list = []
    for i in range(len(testDataset)):
        caption = testDataset.captions[i]
        image_id = testDataset.image_ids[i]
        if image_id not in test_image:
            print(f"Image ID: {image_id}, Caption: {caption}")
            test_image.append(image_id)
            test_text.append(caption)
            if len(test_image) == 10:
                break
    #######################################################
    tokens_list = []
    mask_list = []
    prefix_list = []
    test_emotion_list = []
    test_sentiment_list = []
    test_humor_list = []
    test_funnyscore_list = []
    test_gt = []
    test_caption = dict()
    test_image_id_list = []

    if test_dataform != "Oxford":
        load = pd.read_csv(f'../Data/Instagram/CaptionID_{test_dataform}.csv')
        load['caption'] = load['caption'].str.lower()
        test_text = []
        for i in range(len(test_image)):
            caption = load[load['image_id'] == test_image[i]]['caption'].values[0]
            test_text.append(caption)
        for i in range(len(testDataset)):
            caption = testDataset.captions[i]
            image_id = testDataset.image_ids[i]
            if image_id in test_image and image_id not in test_image_id_list:
                test_caption[image_id] = []
                test_caption[image_id].append(caption)
                tokens, mask, prefix, item, emotion, sentiment, humor, funnyscore = testDataset[i]
                tokens_list.append(tokens)
                mask_list.append(mask)
                prefix_list.append(prefix)
                # emotion, sentiment, humor = testDataset.pad_emotion(item)
                test_emotion_list.append(emotion)
                test_sentiment_list.append(sentiment)
                test_humor_list.append(humor)
                test_funnyscore_list.append(funnyscore)
                test_gt.append(caption)
                test_image_id_list.append(image_id)
    else:
        for i in range(len(testDataset)):
            caption = testDataset.captions[i]
            image_id = testDataset.image_ids[i]
            if image_id in test_image:
                if test_caption.get(image_id) is not None:
                    test_caption[image_id].append(caption)
                else:
                    test_caption[image_id] = []
                    test_caption[image_id].append(caption)
                if caption in test_text and image_id not in test_image_id_list:
                    # print(f"Image ID: {image_id}, Caption: {caption}")
                    tokens, mask, prefix, item, emotion, sentiment, humor, funnyscore = testDataset[i]
                    tokens_list.append(tokens)
                    mask_list.append(mask)
                    prefix_list.append(prefix)
                    # emotion, sentiment, humor = testDataset.pad_emotion(item)
                    test_emotion_list.append(emotion)
                    test_sentiment_list.append(sentiment)
                    test_humor_list.append(humor)
                    test_funnyscore_list.append(funnyscore)
                    test_gt.append(caption)
                    test_image_id_list.append(image_id)

    test_tokens = torch.stack(tokens_list).to(device)
    test_mask = torch.stack(mask_list).to(device)
    test_prefix = torch.stack(prefix_list).to(device)
    test_emotion = torch.stack(test_emotion_list).to(device)
    test_sentiment = torch.stack(test_sentiment_list).to(device)
    test_humor = torch.stack(test_humor_list).to(device)
    test_funnyscore = torch.tensor(test_funnyscore_list).to(device)
    print(test_tokens.shape, test_mask.shape, test_prefix.shape)
    print(test_emotion.shape, test_sentiment.shape, test_humor.shape, test_funnyscore.shape)

100%|██████████| 1432/1432 [07:57<00:00,  3.00it/s]

Train Data size: 336000

100%|██████████| 1432/1432 [02:01<00:00, 11.82it/s]

Train Data size: 86400
Image ID: bokete_100219, Caption: listen to me. listen to me. it's a relief that you're hitting.
Image ID: bokete_100225, Caption: it's... it's melon.
Image ID: bokete_100357, Caption: speaking of "heh-ya," it's my brother who laughs 100%.
Image ID: bokete_100382, Caption: "i'd like some carrots, some potatoes, some potatoes, please."
Image ID: bokete_100433, Caption: the truth is, you can talk fast, can't you?
Image ID: bokete_100512, Caption: he's got a cock. he's got a coral on him.
Image ID: bokete_100652, Caption: metal allergy.
Image ID: bokete_100942, Caption: i imagined myself in a very wealthy family because of the fact that i was heard of classical music in my stomach.
Image ID: bokete_100979, Caption: no matter how many times i guess, i'm the killer.
Image ID: bokete_101023, Caption: mr. pigriola, you're growing up in battle.
torch.Size([10, 64]) torch.Size([10, 128]) torch.Size([10, 64, 768]) 10
torch.Size([10, 64, 768]) torch.Size([10, 64, 768]) torch.Size([10, 64, 768]) torch.Size([10])
Image ID: bokete_101263, Caption: they're the ones that stare at their shattered friends.
Image ID: bokete_102706, Caption: grandpa, you don't have a register, do you?
Image ID: bokete_103663, Caption: after taking this lost child with me for a week, i think it's okay to stay lost. the police officer began to think like that.
Image ID: bokete_105039, Caption: it's a barsand, and it's coming out.
Image ID: bokete_105913, Caption: i've been invited by chance to a brand-new show.
Image ID: bokete_105924, Caption: i've told you so many times, let's go look for something to eat.
Image ID: bokete_106268, Caption: one-eye-leaf and ichiro.
Image ID: bokete_107684, Caption: there was a lot of porno in there.
Image ID: bokete_107719, Caption: the trino olympics.
Image ID: bokete_107720, Caption: i'm sorry. i'm sorry.
torch.Size([10, 64]) torch.Size([10, 128]) torch.Size([10, 64, 768])
torch.Size([10, 64, 768]) torch.Size([10, 64, 768]) torch.Size([10, 64, 768]) torch.Size([10])

In [5]:
test_funnyscore_list

[tensor([751.]),
 tensor([700.]),
 tensor([804.]),
 tensor([556.]),
 tensor([408.]),
 tensor([537.]),
 tensor([1287.]),
 tensor([554.]),
 tensor([2307.]),
 tensor([296.])]

In [7]:
dirPath = '../Data/Oxford_Hic/Generate_bert_top1000_oxford_mix.csv'
data = pd.read_csv(dirPath)
image_id_counts = data['image_id'].value_counts()
data['caption'] = data['caption'].str.lower()
data['funny_score'] = data['funny_score_y']
data

,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated,funny_score
0,bokete_2176,"lowercase ""y"".",0.007244,711.0,69.727273,0,711.0
1,bokete_2176,"anpanman, new face!",0.000132,13.0,69.727273,0,13.0
2,bokete_2176,it's a driving shot!,0.000122,12.0,69.727273,0,12.0
3,bokete_2176,"if it's not moving, it's going to leak ...",0.000061,6.0,69.727273,0,6.0
4,bokete_2176,fracture of left ankle,0.000061,6.0,69.727273,0,6.0
...,...,...,...,...,...,...,...
4901249,bokete_91043,don't give up!,0.001691,166.0,25.428571,0,166.0
4901250,bokete_91043,"all right! if you save everything, you'll be a...",0.000051,5.0,25.428571,0,5.0
4901251,bokete_91043,"""don't save it, save it!""",0.000020,2.0,25.428571,0,2.0
4901252,bokete_91043,"i gave in to temptation and opened it, but tha...",0.000020,2.0,25.428571,0,2.0
4901253,bokete_91043,(in all 500 yen balls),0.000000,0.0,25.428571,0,0.0

In [4]:
class Predictor(object):
    def __init__(self, prefix_length, cp_num, train_caption, test_caption, train_image_id_list, test_image_id_list):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.device = torch.device("cpu")
        self.imageList = []
        self.gtList = []
        self.gt_fluency = []
        self.generate_beam_output = None
        self.generate2_output = None
        self.train_output = None
        self.generate_beam_text = []
        self.generate2_text = []
        self.train_text = []
        self.generate_beam_fitCount = []
        self.generate2_fitCount = []
        self.train_fitCount = []
        self.generate_beam_gtNum = []
        self.generate2_gtNum = []
        self.train_gtNum = []
        self.generate_beam_bleu1 = []
        self.generate_beam_bleu2 = []
        self.generate_beam_bleu3 = []
        self.generate_beam_bleu4 = []
        self.generate_beam_fluency = []
        self.generate2_bleu1 = []
        self.generate2_bleu2 = []
        self.generate2_bleu3 = []
        self.generate2_bleu4 = []
        self.generate2_fluency = []
        self.train_bleu1 = []
        self.train_bleu2 = []
        self.train_bleu3 = []
        self.train_bleu4 = []
        self.train_fluency = []
        self.train_loss = []
        self.train_caption_loss = []
        self.train_fc_loss = []
        self.prefix_length = prefix_length
        self.cp_num = cp_num
        self.train_caption = train_caption
        self.test_caption = test_caption
        self.train_image_id_list = train_image_id_list
        self.test_image_id_list = test_image_id_list
        # print("parrot model loading")
        # self.fluency_score  = Fluency()
        # self.fluency_score.fluency_model = self.fluency_score.fluency_model.to(self.device)
        # print("parrot model loaded")
        self.clip, self.clip_preprocess = clip.load("ViT-B/32")
        self.clip.to(self.device)
        self.clip.eval()
        print("clip model loaded")

    def fitCounter(self, data_mode, caption, dataIndex):
        bleu1_sum = 0
        bleu2_sum = 0
        bleu3_sum = 0
        bleu4_sum = 0
        if data_mode == "test":
            fitCount = 0
            caption_words = caption.split()
            index = self.test_image_id_list[dataIndex]
            for j in range(len(self.test_caption[index])):
                bleu1_sum += sentence_bleu([self.test_caption[index][j].split()], caption_words, weights=(1, 0, 0, 0))
                bleu2_sum += sentence_bleu([self.test_caption[index][j].split()], caption_words, weights=(0, 1, 0, 0))
                bleu3_sum += sentence_bleu([self.test_caption[index][j].split()], caption_words, weights=(0, 0, 1, 0))
                bleu4_sum += sentence_bleu([self.test_caption[index][j].split()], caption_words, weights=(0, 0, 0, 1))
                gt_words = self.test_caption[index][j].split()
                for k in range(len(caption_words)):
                    if caption_words[k] in gt_words:
                        fitCount += 1
            gtNum = len(self.test_caption[index])
        else:
            fitCount = 0
            caption_words = caption.split()
            index = self.train_image_id_list[dataIndex]
            for j in range(len(self.train_caption[index])):
                bleu1_sum += sentence_bleu([self.train_caption[index][j].split()], caption_words, weights=(1, 0, 0, 0))
                bleu2_sum += sentence_bleu([self.train_caption[index][j].split()], caption_words, weights=(0, 1, 0, 0))
                bleu3_sum += sentence_bleu([self.train_caption[index][j].split()], caption_words, weights=(0, 0, 1, 0))
                bleu4_sum += sentence_bleu([self.train_caption[index][j].split()], caption_words, weights=(0, 0, 0, 1))
                gt_words = self.train_caption[index][j].split()
                for k in range(len(caption_words)):
                    if caption_words[k] in gt_words:
                        fitCount += 1
            gtNum = len(self.train_caption[index])
        bleu1_sum /= gtNum
        bleu2_sum /= gtNum
        bleu3_sum /= gtNum
        bleu4_sum /= gtNum
        return fitCount, gtNum, bleu1_sum, bleu2_sum, bleu3_sum, bleu4_sum

    def fitCounter_test(self, caption, ground_truth):
        bleu1_sum = 0
        bleu2_sum = 0
        bleu3_sum = 0
        bleu4_sum = 0
        fitCount = 0
        caption_words = caption.split()
        bleu1_sum += sentence_bleu([ground_truth.split()], caption_words, weights=(1, 0, 0, 0))
        bleu2_sum += sentence_bleu([ground_truth.split()], caption_words, weights=(0, 1, 0, 0))
        bleu3_sum += sentence_bleu([ground_truth.split()], caption_words, weights=(0, 0, 1, 0))
        bleu4_sum += sentence_bleu([ground_truth.split()], caption_words, weights=(0, 0, 0, 1))
        gt_words = ground_truth.split()
        for k in range(len(caption_words)):
            if caption_words[k] in gt_words:
                fitCount += 1
        gtNum = 1

        return fitCount, gtNum, bleu1_sum, bleu2_sum, bleu3_sum, bleu4_sum

    def parrot_fluency(self, caption):
        input_ids = self.fluency_score.fluency_tokenizer("Sentence: " + caption, return_tensors='pt', truncation=True)
        input_ids = input_ids.to(self.device)
        prediction = self.fluency_score.fluency_model(**input_ids)
        scores = prediction[0][0].detach().cpu().numpy()
        scores = softmax(scores)
        fluency_score = scores[1]  # LABEL_0 = Bad Fluency, LABEL_1 = Good Fluency
        return fluency_score

    def diversity_score(self, captionList):
        # tokenize  and extract text features
        text_tokens = clip.tokenize(captionList, context_length=77, truncate=True).to(device)
        with torch.no_grad():
            text_features = self.clip.encode_text(text_tokens).float()
        text_features /= text_features.norm(dim=-1, keepdim=True)
        text_features = text_features.cpu().numpy()
        # 計算所有 pair 的 cosine similarity
        cosine_sim = np.dot(text_features, text_features.T)  # p_m^T * p_n
        norms = np.linalg.norm(text_features, axis=1, keepdims=True)
        cosine_sim /= (norms @ norms.T)  # 除以 |pm||pn|
        # 找出每個向量最相似的另一個向量（n ≠ m）
        max_similarities = np.array([max(row[np.arange(len(row)) != i]) for i, row in enumerate(cosine_sim)])
        # 計算 diversity score
        diversity = np.sqrt(1 - np.mean(max_similarities) ** 2)
        return diversity

    def predict(self, data_mode,tokens, masks, prefixs, text_gt, model, emotion, sentiment, humor, funnyscore):
        self.embedding_size = model.embedding_size
        # device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        device = torch.device("cpu")
        tokens, masks, prefixs = tokens.to(device), masks.to(device), prefixs.to(device, dtype=torch.bfloat16)
        # emotion, sentiment, humor = emotion.to(device), sentiment.to(device), humor.to(device)
        emotion, sentiment, humor = emotion.to(device, dtype=torch.bfloat16), sentiment.to(device, dtype=torch.bfloat16), humor.to(device, dtype=torch.bfloat16)

        # tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
        # tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
        tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
        # tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")
        tokenizer.pad_token = tokenizer.eos_token

        model.eval()
        model.to(device, dtype=torch.bfloat16)
        for i, text in enumerate(text_gt):
            print('====================== '+data_mode+' '+ str(i+1) +'======================')
            print('--------- ground truth ---------')
            print(text)
            print('--------- generate_beam ---------')
            # if model.LoRaActivated:
            #     embedding_emotion = model.falcon.base_model.model.model.embed_tokens(emotion[i].unsqueeze(0))
            #     embedding_sentiment = model.falcon.base_model.model.model.embed_tokens(sentiment[i].unsqueeze(0))
            #     embedding_humor = model.falcon.base_model.model.model.embed_tokens(humor[i].unsqueeze(0))
            # else:
            #     embedding_emotion = model.falcon.model.embed_tokens(emotion[i].unsqueeze(0))
            #     embedding_sentiment = model.falcon.model.embed_tokens(sentiment[i].unsqueeze(0))
            #     embedding_humor = model.falcon.model.embed_tokens(humor[i].unsqueeze(0))

            # empty_ESH = torch.zeros(embedding_emotion.shape[0], 1, embedding_emotion.shape[2], dtype=torch.bfloat16, device=embedding_emotion.device)
            # embedding_ESH = torch.cat((empty_ESH, embedding_emotion, embedding_sentiment, embedding_humor), dim=1)

            # emotion_proj = model.emotion_linear(emotion[i].unsqueeze(0)).unsqueeze(1)
            # sentiment_proj = model.sentiment_linear(sentiment[i].unsqueeze(0)).unsqueeze(1)
            # humor_proj = model.humor_linear(humor[i].unsqueeze(0)).unsqueeze(1)
            # embedding_ESH = torch.cat((emotion_proj, sentiment_proj, humor_proj), dim=1)
            # embedding_ESH = model.ESH_linear(embedding_ESH.transpose(1, 2)).transpose(1, 2)

            embedding_ESH = torch.cat((emotion[i].unsqueeze(0), sentiment[i].unsqueeze(0), humor[i].unsqueeze(0)), dim=1)
            embedding_ESH = model.ESH_linear(embedding_ESH.transpose(1, 2)).transpose(1, 2)

            ############################################ 202503 ##############################################
            clip_projections = model.clip_project(prefixs[i].unsqueeze(0)).view(-1, model.prefix_length, model.embedding_size)
            visual_projections_swin = model.visual_project_swin(embedding_ESH, clip_projections)
            visual_projections_ESH = model.visual_project_ESH(clip_projections, embedding_ESH)
            ########################################################################################
            ## 20250302_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_swin_tf8  ###
            ########################################################################################
            prefix_embed = torch.cat((visual_projections_swin, visual_projections_ESH), dim=1)
            prefix_embed = model.visual_project(prefix_embed.transpose(1, 2)).transpose(1, 2)
            ########################################################################################
            #### 20250303_oxford_lower_800up_only800_rest_300up_top300_ESH_co_concat_swin_tf8   ####
            ########################################################################################
            # prefix_embed = visual_projections_swin
            #######################################################################################
            # 20250310_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_add_768_swin_tf8    #
            # 20250307_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_768_swin_tf8 #
            #######################################################################################
            # prefix_embed = model.linear(prefix_embed)
            ################################################################################

            # caption = generate_beam(model, tokenizer, embed=prefix_embed)[0]
            # caption_token = tokenizer(caption, return_tensors='pt', padding='max_length', truncation=True, max_length=74)
            # # print(caption)
            # if self.generate_beam_output != None:
            #     self.generate_beam_output = torch.cat((self.generate_beam_output, caption_token['input_ids']), dim=0)
            # else:
            #     self.generate_beam_output = caption_token['input_ids']
            # self.generate_beam_text.append(caption)
            # self.generate_beam_fluency.append(self.parrot_fluency(caption))
            # fitCount, gtNum, bleu1, bleu2, bleu3, bleu4 = self.fitCounter(data_mode, caption, i)
            # self.generate_beam_fitCount.append(fitCount)
            # self.generate_beam_gtNum.append(gtNum)
            # self.generate_beam_bleu1.append(bleu1)
            # self.generate_beam_bleu2.append(bleu2)
            # self.generate_beam_bleu3.append(bleu3)
            # self.generate_beam_bleu4.append(bleu4)
            # # print('---------generate2---------')
            # caption = generate2(model, tokenizer, embed=prefix_embed)
            # caption_token = tokenizer(caption, return_tensors='pt', padding='max_length', truncation=True, max_length=74)
            # # print(caption)
            # if self.generate2_output != None:
            #     self.generate2_output = torch.cat((self.generate2_output, caption_token['input_ids']), dim=0)
            # else:
            #     self.generate2_output = caption_token['input_ids']
            # self.generate2_text.append(caption)
            # self.generate2_fluency.append(self.parrot_fluency(caption))
            # fitCount, gtNum, bleu1, bleu2, bleu3, bleu4 = self.fitCounter(data_mode, caption, i)
            # self.generate2_fitCount.append(fitCount)
            # self.generate2_gtNum.append(gtNum)
            # self.generate2_bleu1.append(bleu1)
            # self.generate2_bleu2.append(bleu2)
            # self.generate2_bleu3.append(bleu3)
            # self.generate2_bleu4.append(bleu4)
            print('---------train---------')
            # embedding_text = model.gemma.model.embed_tokens(tokens[i].unsqueeze(0))
            # embedding_text = model.gemma.base_model.model.model.embed_tokens(tokens[i].unsqueeze(0))
            # embedding_text = model.gpt.transformer.wte(tokens[i].unsqueeze(0))
            if model.LoRaActivated:
                embedding_text = model.falcon.base_model.model.model.embed_tokens(tokens[i].unsqueeze(0))
            else:
                embedding_text = model.falcon.model.embed_tokens(tokens[i].unsqueeze(0))
            print(prefix_embed.shape, embedding_text.shape)
            embedding_cat = torch.cat((prefix_embed, embedding_text), dim=1)
            # out = model.gemma(inputs_embeds=embedding_cat, attention_mask=masks[i].unsqueeze(0))
            # out = model.gpt(inputs_embeds=embedding_cat, attention_mask=masks[i].unsqueeze(0))
            out = model.falcon(inputs_embeds=embedding_cat, attention_mask=masks[i].unsqueeze(0))
            print(out.logits.shape)
            logits = out.logits[:, self.prefix_length-1: -1]
            if model.mode == 'lora' or model.LoRaActivated:
                output_fc = model.funnyscore_mlp1(embedding_cat).squeeze(-1)
                output_fc = model.funnyscore_relu(output_fc)
                output_fc = model.funnyscore_mlp2(output_fc).squeeze(-1)
                output_fc = model.funnyscore_sigmoid(output_fc)
                print(f'funnyscore {funnyscore[i]}')
                capLoss, fcLoss, loss = combine_loss(logits, tokens[i], funnyscore[i].unsqueeze(0).to(device, dtype=torch.bfloat16), output_fc)
                print(capLoss.item())
                self.train_caption_loss.append(capLoss.item())
                self.train_fc_loss.append(fcLoss.item())
            else:
                loss = nnf.cross_entropy(logits.reshape(-1, logits.shape[-1]), tokens[i].flatten(), ignore_index=0)
                # loss = PCloss(logits, tokens[i].unsqueeze(0))
            print(loss)
            caption_token = logits.argmax(-1)[0].cpu()
            caption = tokenizer.decode(caption_token, skip_special_tokens=True)
            caption_token = tokenizer(caption, return_tensors='pt', padding='max_length', truncation=True, max_length=489)['input_ids']
            print(caption)
            if self.train_output != None:
                self.train_output = torch.cat((self.train_output, caption_token), dim=0)
            else:
                self.train_output = caption_token
            self.train_text.append(caption)
            self.train_loss.append(loss.item())
            # self.train_fluency.append(self.parrot_fluency(caption))
            fitCount, gtNum, bleu1, bleu2, bleu3, bleu4 = self.fitCounter(data_mode, caption, i)
            self.train_fitCount.append(fitCount)
            self.train_gtNum.append(gtNum)
            self.train_bleu1.append(bleu1)
            self.train_bleu2.append(bleu2)
            self.train_bleu3.append(bleu3)
            self.train_bleu4.append(bleu4)

        if data_mode == "train":
            def dataframe_Name(name, count=489, rows=1):
                if rows == 1:
                    name_df = pd.DataFrame([[name]], columns=["Name"])
                    num_df = pd.DataFrame([[0] * count for _ in range(rows)], columns=[f"{i}" for i in range(0, count)])
                    name_df = pd.concat([name_df, num_df], axis=1)
                    return name_df
                else:
                    name_df = pd.DataFrame([[name] * count for _ in range(rows)],columns=[f"{i}" for i in range(489 - count, 489)])
                    return name_df

            test = pd.DataFrame()
            test['Name'] = ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7', 'test8', 'test9','test10',
                            'train1', 'train2', 'train3', 'train4', 'train5', 'train6', 'train7',
                            'train8', 'train9', 'train10']
            test['image_id'] = self.test_image_id_list[:10] + self.train_image_id_list[:10]
            generate_beam_df = pd.DataFrame(self.generate_beam_output.cpu().detach(),columns=[f"{i}" for i in range(0, 74)])
            generate_beam_df = pd.concat([test, generate_beam_df, dataframe_Name("-", 74, 16)], axis=1)
            generate_beam_df['text'] = self.generate_beam_text
            generate_beam_df['fitCount'] = self.generate_beam_fitCount
            generate_beam_df['gtNum'] = self.generate_beam_gtNum
            generate_beam_df['fluency'] = self.generate_beam_fluency
            generate_beam_df['diversity'] = self.diversity_score(self.generate_beam_text)
            generate_beam_df['bleu1'] = self.generate_beam_bleu1
            generate_beam_df['bleu2'] = self.generate_beam_bleu2
            generate_beam_df['bleu3'] = self.generate_beam_bleu3
            generate_beam_df['bleu4'] = self.generate_beam_bleu4
            test_avgscore = pd.DataFrame()
            train_avgscore = pd.DataFrame()
            for column in generate_beam_df.columns:
                if column == 'Name':
                    train_avgscore[column] = ["train_avg"]
                    test_avgscore[column] = ["test_avg"]
                elif pd.api.types.is_numeric_dtype(generate_beam_df[column]):
                    train_avgscore[column] = [generate_beam_df[column][10:].mean()]
                    test_avgscore[column] = [generate_beam_df[column][:10].mean()]
                else:
                    train_avgscore[column] = ["-"]
                    test_avgscore[column] = ["-"]
            generate_beam_df = pd.concat([generate_beam_df, test_avgscore, train_avgscore], axis=0)

            generate2_df = pd.DataFrame(self.generate2_output.cpu().detach(), columns=[f"{i}" for i in range(0, 74)])
            generate2_df = pd.concat([test, generate2_df, dataframe_Name("-", 74, 16)], axis=1)
            generate2_df['text'] = self.generate2_text
            generate2_df['fitCount'] = self.generate2_fitCount
            generate2_df['gtNum'] = self.generate2_gtNum
            generate2_df['fluency'] = self.generate2_fluency
            generate2_df['diversity'] = self.diversity_score(self.generate2_text)
            generate2_df['bleu1'] = self.generate2_bleu1
            generate2_df['bleu2'] = self.generate2_bleu2
            generate2_df['bleu3'] = self.generate2_bleu3
            generate2_df['bleu4'] = self.generate2_bleu4
            test_avgscore = pd.DataFrame()
            train_avgscore = pd.DataFrame()
            for column in generate2_df.columns:
                if column == 'Name':
                    train_avgscore[column] = ["train_avg"]
                    test_avgscore[column] = ["test_avg"]
                elif pd.api.types.is_numeric_dtype(generate2_df[column]):
                    train_avgscore[column] = [generate2_df[column][10:].mean()]
                    test_avgscore[column] = [generate2_df[column][:10].mean()]
                else:
                    train_avgscore[column] = ["-"]
                    test_avgscore[column] = ["-"]
            generate2_df = pd.concat([generate2_df, test_avgscore, train_avgscore], axis=0)

            train_df = pd.DataFrame(self.train_output.cpu().detach(), columns=[f"{i}" for i in range(0, 489)])
            train_df = pd.concat([test, train_df], axis=1)
            train_df['loss'] = self.train_loss
            if model.mode == 'lora' or model.LoRaActivated:
                train_df['caption_loss'] = self.train_caption_loss
                train_df['fc_loss'] = self.train_fc_loss
            train_df['text'] = self.train_text
            train_df['fitCount'] = self.train_fitCount
            train_df['gtNum'] = self.train_gtNum
            train_df['fluency'] = self.train_fluency
            train_df['diversity'] = self.diversity_score(self.train_text)
            train_df['bleu1'] = self.train_bleu1
            train_df['bleu2'] = self.train_bleu2
            train_df['bleu3'] = self.train_bleu3
            train_df['bleu4'] = self.train_bleu4
            test_avgscore = pd.DataFrame()
            train_avgscore = pd.DataFrame()
            for column in train_df.columns:
                if column == 'Name':
                    train_avgscore[column] = ["train_avg"]
                    test_avgscore[column] = ["test_avg"]
                elif pd.api.types.is_numeric_dtype(train_df[column]):
                    train_avgscore[column] = [train_df[column][10:].mean()]
                    test_avgscore[column] = [train_df[column][:10].mean()]
                else:
                    train_avgscore[column] = ["-"]
                    test_avgscore[column] = ["-"]
            train_df = pd.concat([train_df, test_avgscore, train_avgscore], axis=0)

            print(dataframe_Name("generate_beam").shape, generate_beam_df.shape, dataframe_Name("generate2").shape,
                  generate2_df.shape, dataframe_Name("train").shape, train_df.shape)
            final = pd.concat([dataframe_Name("generate_beam"), generate_beam_df, dataframe_Name("generate2"),
                               generate2_df, dataframe_Name("train"), train_df], axis=0)
            print(final.shape)
            print(final.columns)
            # final.to_csv(f'./Model/{save_file}/test_{self.cp_num:03d}.csv', float_format='%.15f', index=False)

            # final.to_csv(f'./Model/{save_file}/{save_file}_test_{self.cp_num:03d}.csv', float_format='%.15f', index=False)
            final.to_csv(f'./Model/{save_file}/test_{self.cp_num:03d}.csv', float_format='%.15f', index=False)
            # final.to_csv(f'./Model/{save_file}/Generate_mcdonalds_all.csv', index=False)

    def test(self, test_dataset, model, output_dir):
        # device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        device = torch.device("cpu")
        batch_size = 1
        model = model.to(device)
        test_data_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True, drop_last=True)

        model.eval()
        with torch.no_grad():
            progress = tqdm(total=len(test_data_loader))
            for idx, (tokens, masks, prefixs, item, emotion, sentiment, humor, funnyscore, image_id, ground_truth) in enumerate(test_data_loader):
                self.imageList.append(image_id[0])
                self.gtList.append(ground_truth[0])
                self.gt_fluency.append(self.parrot_fluency(ground_truth[0]))
                self.embedding_size = model.embedding_size
                # device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
                device = torch.device("cpu")
                tokens, masks, prefixs = tokens.to(device), masks.to(device), prefixs.to(device, dtype=torch.bfloat16)
                emotion, sentiment, humor = emotion.to(device), sentiment.to(device), humor.to(device)
                # emotion, sentiment, humor = emotion.to(device, dtype=torch.bfloat16), sentiment.to(device, dtype=torch.bfloat16), humor.to(device, dtype=torch.bfloat16)

                # tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
                # tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
                tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
                # tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")
                tokenizer.pad_token = tokenizer.eos_token

                model.eval()
                model.to(device, dtype=torch.bfloat16)
                # print('--------- ground truth ---------')
                # print(ground_truth)
                # print('--------- generate_beam ---------')
                if model.LoRaActivated:
                    embedding_emotion = model.falcon.base_model.model.model.embed_tokens(emotion)
                    embedding_sentiment = model.falcon.base_model.model.model.embed_tokens(sentiment)
                    embedding_humor = model.falcon.base_model.model.model.embed_tokens(humor)
                else:
                    embedding_emotion = model.falcon.model.embed_tokens(emotion)
                    embedding_sentiment = model.falcon.model.embed_tokens(sentiment)
                    embedding_humor = model.falcon.model.embed_tokens(humor)

                empty_ESH = torch.zeros(embedding_emotion.shape[0], 1, embedding_emotion.shape[2], dtype=torch.bfloat16, device=embedding_emotion.device)
                embedding_ESH = torch.cat((empty_ESH, embedding_emotion, embedding_sentiment, embedding_humor), dim=1)

                # emotion_proj = model.emotion_linear(emotion).unsqueeze(1)
                # sentiment_proj = model.sentiment_linear(sentiment).unsqueeze(1)
                # humor_proj = model.humor_linear(humor).unsqueeze(1)
                # embedding_ESH = torch.cat((emotion_proj, sentiment_proj, humor_proj), dim=1)
                # embedding_ESH = model.ESH_linear(embedding_ESH.transpose(1, 2)).transpose(1, 2)
                ############################################ 202503 ##############################################
                clip_projections = model.clip_project(prefixs).view(-1, model.prefix_length, model.embedding_size)
                visual_projections_swin = model.visual_project_swin(embedding_ESH, clip_projections)
                visual_projections_ESH = model.visual_project_ESH(clip_projections, embedding_ESH)
                ########################################################################################
                ## 20250302_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_swin_tf8  ###
                ########################################################################################
                prefix_embed = torch.cat((visual_projections_swin, visual_projections_ESH), dim=1)
                prefix_embed = model.visual_project(prefix_embed.transpose(1, 2)).transpose(1, 2)
                ########################################################################################
                #### 20250303_oxford_lower_800up_only800_rest_300up_top300_ESH_co_concat_swin_tf8   ####
                ########################################################################################
                # prefix_embed = visual_projections_swin
                #######################################################################################
                # 20250310_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_add_768_swin_tf8    #
                # 20250307_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_768_swin_tf8 #
                #######################################################################################
                # prefix_embed = model.linear(prefix_embed)
                ################################################################################

                caption = generate_beam(model, tokenizer, embed=prefix_embed)[0]
                caption_token = tokenizer(caption, return_tensors='pt', padding='max_length', truncation=True, max_length=74)
                # print(caption)
                if self.generate_beam_output != None:
                    self.generate_beam_output = torch.cat((self.generate_beam_output, caption_token['input_ids']), dim=0)
                else:
                    self.generate_beam_output = caption_token['input_ids']
                self.generate_beam_text.append(caption)
                self.generate_beam_fluency.append(self.parrot_fluency(caption))
                fitCount, gtNum, bleu1, bleu2, bleu3, bleu4 = self.fitCounter_test(caption, ground_truth[0])
                self.generate_beam_fitCount.append(fitCount)
                self.generate_beam_gtNum.append(gtNum)
                self.generate_beam_bleu1.append(bleu1)
                self.generate_beam_bleu2.append(bleu2)
                self.generate_beam_bleu3.append(bleu3)
                self.generate_beam_bleu4.append(bleu4)
                # print('---------generate2---------')
                caption = generate2(model, tokenizer, embed=prefix_embed)
                caption_token = tokenizer(caption, return_tensors='pt', padding='max_length', truncation=True, max_length=74)
                # print(caption)
                if self.generate2_output != None:
                    self.generate2_output = torch.cat((self.generate2_output, caption_token['input_ids']), dim=0)
                else:
                    self.generate2_output = caption_token['input_ids']
                self.generate2_text.append(caption)
                self.generate2_fluency.append(self.parrot_fluency(caption))
                fitCount, gtNum, bleu1, bleu2, bleu3, bleu4 = self.fitCounter_test(caption, ground_truth[0])
                self.generate2_fitCount.append(fitCount)
                self.generate2_gtNum.append(gtNum)
                self.generate2_bleu1.append(bleu1)
                self.generate2_bleu2.append(bleu2)
                self.generate2_bleu3.append(bleu3)
                self.generate2_bleu4.append(bleu4)
                # print('---------train---------')
                # embedding_text = model.gemma.model.embed_tokens(tokens)
                # embedding_text = model.gemma.base_model.model.model.embed_tokens(tokens)
                # embedding_text = model.gpt.transformer.wte(tokens)
                if model.LoRaActivated:
                    embedding_text = model.falcon.base_model.model.model.embed_tokens(tokens)
                else:
                    embedding_text = model.falcon.model.embed_tokens(tokens)
                # print(prefix_embed.shape, embedding_text.shape)
                embedding_cat = torch.cat((prefix_embed, embedding_text), dim=1)
                # out = model.gemma(inputs_embeds=embedding_cat, attention_mask=masks)
                # out = model.gpt(inputs_embeds=embedding_cat, attention_mask=masks)
                out = model.falcon(inputs_embeds=embedding_cat, attention_mask=masks)
                logits = out.logits[:, self.prefix_length - 1: -1]
                if model.mode == 'lora' or model.LoRaActivated:
                    output_fc = model.funnyscore_mlp1(embedding_cat).squeeze(-1)
                    output_fc = model.funnyscore_relu(output_fc)
                    output_fc = model.funnyscore_mlp2(output_fc).squeeze(-1)
                    output_fc = model.funnyscore_sigmoid(output_fc)
                    capLoss, fcLoss, loss = combine_loss(logits, tokens, funnyscore.to(device, dtype=torch.bfloat16),output_fc)
                    self.train_caption_loss.append(capLoss.item())
                    self.train_fc_loss.append(fcLoss.item())
                else:
                    loss = nnf.cross_entropy(logits.reshape(-1, logits.shape[-1]), tokens.flatten(), ignore_index=0)
                    # loss = PCloss(logits, tokens)
                # print(loss)
                caption_token = logits.argmax(-1)[0].cpu()
                caption = tokenizer.decode(caption_token, skip_special_tokens=True)
                caption_token = tokenizer(caption, return_tensors='pt', padding='max_length', truncation=True, max_length=489)['input_ids']
                # print(caption)
                if self.train_output != None:
                    self.train_output = torch.cat((self.train_output, caption_token), dim=0)
                else:
                    self.train_output = caption_token
                self.train_text.append(caption)
                self.train_loss.append(loss.item())
                self.train_fluency.append(self.parrot_fluency(caption))
                fitCount, gtNum, bleu1, bleu2, bleu3, bleu4 = self.fitCounter_test(caption, ground_truth[0])
                self.train_fitCount.append(fitCount)
                self.train_gtNum.append(gtNum)
                self.train_bleu1.append(bleu1)
                self.train_bleu2.append(bleu2)
                self.train_bleu3.append(bleu3)
                self.train_bleu4.append(bleu4)
                progress.update()
            progress.close()

        generate_beam_df = pd.DataFrame()
        generate_beam_df['image_id'] = self.imageList
        generate_beam_df['caption'] = self.generate_beam_text
        generate_beam_df['fitCount'] = self.generate_beam_fitCount
        generate_beam_df['gtNum'] = self.generate_beam_gtNum
        generate_beam_df['fluency'] = self.generate_beam_fluency
        generate_beam_df['diversity'] = self.diversity_score(self.generate_beam_text)
        generate_beam_df['bleu1'] = self.generate_beam_bleu1
        generate_beam_df['bleu2'] = self.generate_beam_bleu2
        generate_beam_df['bleu3'] = self.generate_beam_bleu3
        generate_beam_df['bleu4'] = self.generate_beam_bleu4
        generate_beam_df.to_csv(f'{output_dir}/generate_beam_{self.cp_num}.csv', index=False)

        generate2_df = pd.DataFrame()
        generate2_df['image_id'] = self.imageList
        generate2_df['caption'] = self.generate2_text
        generate2_df['fitCount'] = self.generate2_fitCount
        generate2_df['gtNum'] = self.generate2_gtNum
        generate2_df['fluency'] = self.generate2_fluency
        generate2_df['diversity'] = self.diversity_score(self.generate2_text)
        generate2_df['bleu1'] = self.generate2_bleu1
        generate2_df['bleu2'] = self.generate2_bleu2
        generate2_df['bleu3'] = self.generate2_bleu3
        generate2_df['bleu4'] = self.generate2_bleu4
        generate2_df.to_csv(f'{output_dir}/generate2_{self.cp_num}.csv', index=False)

        train_df = pd.DataFrame()
        train_df['image_id'] = self.imageList
        train_df['caption'] = self.train_text
        train_df['fitCount'] = self.train_fitCount
        train_df['gtNum'] = self.train_gtNum
        train_df['fluency'] = self.train_fluency
        train_df['diversity'] = self.diversity_score(self.train_text)
        train_df['bleu1'] = self.train_bleu1
        train_df['bleu2'] = self.train_bleu2
        train_df['bleu3'] = self.train_bleu3
        train_df['bleu4'] = self.train_bleu4
        if model.mode == 'lora' or model.LoRaActivated:
            train_df['loss'] = self.train_loss
            train_df['caption_loss'] = self.train_caption_loss
            train_df['fc_loss'] = self.train_fc_loss
        else:
            train_df['loss'] = self.train_loss
        train_df.to_csv(f'{output_dir}/train_{self.cp_num}.csv', index=False)

        ground_truth_df = pd.DataFrame()
        ground_truth_df['image_id'] = self.imageList
        ground_truth_df['caption'] = self.gtList
        ground_truth_df['fluency'] = self.gt_fluency
        ground_truth_df['diversity'] = self.diversity_score(self.gtList)
        ground_truth_df.to_csv(f'{output_dir}/ground_truth.csv', index=False)

        result = pd.DataFrame()
        result['Name'] = ['generate_beam', 'generate2', 'train', 'ground_truth']
        result['fitCount'] = [generate_beam_df['fitCount'].mean(), generate2_df['fitCount'].mean(), train_df['fitCount'].mean(), '-']
        result['gtNum'] = [generate_beam_df['gtNum'].mean(), generate2_df['gtNum'].mean(), train_df['gtNum'].mean(), '-']
        result['fluency'] = [generate_beam_df['fluency'].mean(), generate2_df['fluency'].mean(), train_df['fluency'].mean(), ground_truth_df['fluency'].mean(), ]
        result['diversity'] = [generate_beam_df['diversity'].mean(), generate2_df['diversity'].mean(), train_df['diversity'].mean(), ground_truth_df['diversity'].mean()]
        result['bleu1'] = [generate_beam_df['bleu1'].mean(), generate2_df['bleu1'].mean(), train_df['bleu1'].mean(), '-']
        result['bleu2'] = [generate_beam_df['bleu2'].mean(), generate2_df['bleu2'].mean(), train_df['bleu2'].mean(), '-']
        result['bleu3'] = [generate_beam_df['bleu3'].mean(), generate2_df['bleu3'].mean(), train_df['bleu3'].mean(), '-']
        result['bleu4'] = [generate_beam_df['bleu4'].mean(), generate2_df['bleu4'].mean(), train_df['bleu4'].mean(), '-']
        result.to_csv(f'{output_dir}/result_{self.cp_num}.csv', index=False)

class MLP(nn.Module):

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.model(x)

    def __init__(self, mode: str, sizes: Tuple[int, ...], bias=True, act=nn.Tanh):
        super(MLP, self).__init__()
        layers = []
        for i in range(len(sizes) - 1):
            if mode == 'lora':
                layers.append(lora.Linear(sizes[i], sizes[i + 1], bias=bias, r=8))
            else:
                layers.append(nn.Linear(sizes[i], sizes[i + 1], bias=bias))
            if i < len(sizes) - 2:
                layers.append(act())
        self.model = nn.Sequential(*layers)

class MlpTransformer(nn.Module):
    def __init__(self, mode: str, in_dim, h_dim, out_d: Optional[int] = None, act=nnf.relu, dropout=0.):
        super().__init__()
        out_d = out_d if out_d is not None else in_dim
        if mode == 'lora':
            self.fc1 = lora.Linear(in_dim, h_dim, r=8)
            self.fc2 = lora.Linear(h_dim, out_d, r=8)
        else:
            self.fc1 = nn.Linear(in_dim, h_dim)
            self.fc2 = nn.Linear(h_dim, out_d)
        self.act = act
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.dropout(x)
        return x

class MultiHeadAttention(nn.Module):

    def __init__(self, mode: str, dim_self, dim_ref, num_heads, bias=True, dropout=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim_self // num_heads
        self.scale = head_dim ** -0.5
        if mode == 'lora':
            self.to_queries = lora.Linear(dim_self, dim_self, bias=bias, r=8)
            self.to_keys_values = lora.Linear(dim_ref, dim_self * 2, bias=bias, r=8)
            self.project = lora.Linear(dim_self, dim_self, r=8)
        else:
            self.to_queries = nn.Linear(dim_self, dim_self, bias=bias)
            self.to_keys_values = nn.Linear(dim_ref, dim_self * 2, bias=bias)
            self.project = nn.Linear(dim_self, dim_self)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, y=None, mask=None):
        y = y if y is not None else x
        b, n, c = x.shape
        _, m, d = y.shape
        # b n h dh
        queries = self.to_queries(x).reshape(b, n, self.num_heads, c // self.num_heads)
        # b m 2 h dh
        keys_values = self.to_keys_values(y).reshape(b, m, 2, self.num_heads, c // self.num_heads)
        keys, values = keys_values[:, :, 0], keys_values[:, :, 1]
        attention = torch.einsum('bnhd,bmhd->bnmh', queries, keys) * self.scale
        if mask is not None:
            if mask.dim() == 2:
                mask = mask.unsqueeze(1)
            attention = attention.masked_fill(mask.unsqueeze(3), float("-inf"))
        attention = attention.softmax(dim=2)
        out = torch.einsum('bnmh,bmhd->bnhd', attention, values).reshape(b, n, c)
        out = self.project(out)
        return out, attention

class TransformerLayer(nn.Module):

    def forward_with_attention(self, x, y=None, mask=None):
        x_, attention = self.attn(self.norm1(x), y, mask)
        x = x + x_
        x = x + self.mlp(self.norm2(x))
        return x, attention

    def forward(self, x, y=None, mask=None):
        x = x + self.attn(self.norm1(x), y, mask)[0]
        x = x + self.mlp(self.norm2(x))
        return x

    def __init__(self, mode: str, dim_self, dim_ref, num_heads, mlp_ratio=4., bias=True, dropout=0., act=nnf.relu,
                 norm_layer: nn.Module = nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim_self)
        self.attn = MultiHeadAttention(mode, dim_self, dim_ref, num_heads, bias=bias, dropout=dropout)
        self.norm2 = norm_layer(dim_self)
        self.mlp = MlpTransformer(mode, dim_self, int(dim_self * mlp_ratio), act=act, dropout=dropout)

class Transformer(nn.Module):

    def forward_with_attention(self, x, y=None, mask=None):
        attentions = []
        for layer in self.layers:
            x, att = layer.forward_with_attention(x, y, mask)
            attentions.append(att)
        return x, attentions

    def forward(self, x, y=None, mask=None):
        for i, layer in enumerate(self.layers):
            if (i % 2 == 0 and self.enc_dec) or (self.cross == True):  # cross
                x = layer(x, y)
            elif self.enc_dec:  # self
                x = layer(x, x, mask)
            else:  # self or cross
                x = layer(x, y, mask)
        return x

    def __init__(self, mode: str, dim_self: int, num_heads: int, num_layers: int, dim_ref: Optional[int] = None,
                 mlp_ratio: float = 2., act=nnf.relu, norm_layer: nn.Module = nn.LayerNorm, enc_dec: bool = False,
                 cross=False):
        super(Transformer, self).__init__()
        dim_ref = dim_ref if dim_ref is not None else dim_self
        self.enc_dec = enc_dec
        self.cross = cross
        if enc_dec:
            num_layers = num_layers * 2
        layers = []
        for i in range(num_layers):
            if (i % 2 == 0 and self.enc_dec) or (self.cross == True):
                layers.append(
                    TransformerLayer(mode, dim_self, dim_ref, num_heads, mlp_ratio, act=act, norm_layer=norm_layer))
            elif enc_dec:  # self
                layers.append(
                    TransformerLayer(mode, dim_self, dim_self, num_heads, mlp_ratio, act=act, norm_layer=norm_layer))
            else:  # self or cross
                layers.append(
                    TransformerLayer(mode, dim_self, dim_ref, num_heads, mlp_ratio, act=act, norm_layer=norm_layer))
        self.layers = nn.ModuleList(layers)

class TransformerMapper(nn.Module):

    def forward(self, x):
        ### clip ###
        # x = self.linear(x).view(x.shape[0], self.clip_length, -1)
        ### swin ###
        if x.shape[2] == 768:
            x = self.linear(x)
        ############
        ### 768 ###
        # if x.shape[2] != 768:
        #     x = self.linear(x)
        ############
        prefix = self.prefix_const.unsqueeze(0).expand(x.shape[0], *self.prefix_const.shape)
        prefix = torch.cat((x, prefix), dim=1)
        out = self.transformer(prefix)[:, self.clip_length:]
        return out

    def __init__(self, mode: str, dim_clip: int, dim_embedding: int, prefix_length: int, clip_length: int,
                 num_layers: int = 8):
        super(TransformerMapper, self).__init__()
        self.clip_length = clip_length
        self.transformer = Transformer(mode, dim_embedding, 8, num_layers)
        ### clip ###
        # self.linear = nn.Linear(dim_clip, clip_length * dim_embedding)
        ### swin ###
        self.linear = nn.Linear(768, dim_embedding)
        ############
        ### 768 ###
        # self.linear = nn.Linear(2048, dim_embedding)
        ############
        self.prefix_const = nn.Parameter(torch.randn(prefix_length, dim_embedding), requires_grad=True)

class CrossTransformerMapper(nn.Module):

    def forward(self, x, y):
        ### clip ###
        # x = self.linear(x).view(x.shape[0], self.clip_length, -1)
        ### swin ###
        if x.shape[2] == 768:
            x = self.linear(x)
        if y.shape[2] == 768:
            y = self.linear(y)
        ############
        ### 768 ###
        # if x.shape[2] != 768:
        #     x = self.linear(x)
        # if y.shape[2] != 768:
        #     y = self.linear(y)
        ############

        out = self.transformer(x, y)
        return out

    def __init__(self, mode: str, dim_clip: int, dim_embedding: int, prefix_length: int, clip_length: int,
                 num_layers: int = 8):
        super(CrossTransformerMapper, self).__init__()
        self.clip_length = clip_length
        self.transformer = Transformer(mode, dim_embedding, 8, num_layers, cross=True)
        ### clip ###
        # self.linear = nn.Linear(dim_clip, clip_length * dim_embedding)
        ### swin ###
        self.linear = nn.Linear(768, dim_embedding)
        ############
        ### 768 ###
        # self.linear = nn.Linear(2048, dim_embedding)
        ############

class ClipCaptionModel(nn.Module):

    def get_dummy_token(self, batch_size: int, device: torch.device) -> torch.Tensor:
        return torch.zeros(batch_size, self.prefix_length, dtype=torch.int64, device=device)

    def forward(self, tokens: torch.Tensor, prefix: torch.Tensor, mask: Optional[torch.Tensor] = None,
                labels: Optional[torch.Tensor] = None, emotion: torch.Tensor = None, sentiment: torch.Tensor = None,
                humor: torch.Tensor = None) -> tuple[Any, Any] | Any:
        # embedding_text = self.gemma.model.embed_tokens(tokens)
        # embedding_text = self.gemma.base_model.model.model.embed_tokens(tokens)
        # embedding_text = self.gpt.transformer.wte(tokens)
        if self.LoRaActivated:
            embedding_text = self.falcon.base_model.model.model.embed_tokens(tokens)
            # embedding_emotion = self.falcon.base_model.model.model.embed_tokens(emotion)
            # embedding_sentiment = self.falcon.base_model.model.model.embed_tokens(sentiment)
            # embedding_humor = self.falcon.base_model.model.model.embed_tokens(humor)
        else:
            embedding_text = self.falcon.model.embed_tokens(tokens)
            # embedding_emotion = self.falcon.model.embed_tokens(emotion)
            # embedding_sentiment = self.falcon.model.embed_tokens(sentiment)
            # embedding_humor = self.falcon.model.embed_tokens(humor)

        # empty_ESH = torch.zeros(embedding_emotion.shape[0], 1, embedding_emotion.shape[2], dtype=torch.bfloat16, device=embedding_text.device)
        # embedding_ESH = torch.cat((empty_ESH, embedding_emotion, embedding_sentiment, embedding_humor), dim=1)

        # emotion_proj = self.emotion_linear(emotion).unsqueeze(1)
        # sentiment_proj = self.sentiment_linear(sentiment).unsqueeze(1)
        # humor_proj = self.humor_linear(humor).unsqueeze(1)
        # embedding_ESH = torch.cat((emotion_proj, sentiment_proj, humor_proj), dim=1)
        # embedding_ESH = self.ESH_linear(embedding_ESH.transpose(1, 2)).transpose(1, 2)

        embedding_ESH = torch.cat((emotion, sentiment, humor), dim=1)
        embedding_ESH = self.ESH_linear(embedding_ESH.transpose(1, 2)).transpose(1, 2)
        ############################################ 202503 ##############################################
        clip_projections = self.clip_project(prefix).view(-1, self.prefix_length, self.embedding_size)
        visual_projections_swin = self.visual_project_swin(embedding_ESH, clip_projections)
        visual_projections_ESH = self.visual_project_ESH(clip_projections, embedding_ESH)
        ########################################################################################
        ### 20250302_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_swin_tf8  ###
        ########################################################################################
        visual_projections = torch.cat((visual_projections_swin, visual_projections_ESH), dim=1)
        visual_projections = self.visual_project(visual_projections.transpose(1, 2)).transpose(1, 2)
        ########################################################################################
        #######  20250303_oxford_lower_800up_only800_rest_300up_top300_ESH_co_swin_tf8   #######
        ########################################################################################
        # visual_projections = visual_projections_swin
        #######################################################################################
        # 20250310_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_add_768_swin_tf8    #
        # 20250307_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_768_swin_tf8 #
        #######################################################################################
        # visual_projections = self.linear(visual_projections)
        #######################################################################################
        embedding_cat = torch.cat((visual_projections, embedding_text), dim=1)
        ##################################################################################################

        if labels is not None:
            dummy_token = self.get_dummy_token(tokens.shape[0], tokens.device)
            labels = torch.cat((dummy_token, tokens), dim=1)
        # out = self.gpt(inputs_embeds=embedding_cat, labels=labels, attention_mask=mask)
        # out = self.gemma(inputs_embeds=embedding_cat, labels=labels, attention_mask=mask)
        out = self.falcon(inputs_embeds=embedding_cat, labels=labels, attention_mask=mask)
        if self.mode == 'lora' or self.LoRaActivated:
            fc = self.funnyscore_mlp1(embedding_cat).squeeze(-1)
            fc = self.funnyscore_relu(fc)
            fc = self.funnyscore_mlp2(fc).squeeze(-1)
            fc = self.funnyscore_sigmoid(fc)
            return out, fc
        else:
            return out

    def __init__(self, mode: str, prefix_length: int, clip_length: Optional[int] = None, prefix_size: int = 512,
                 num_layers: int = 8):
        super(ClipCaptionModel, self).__init__()
        self.prefix_length = prefix_length
        self.LoRaActivated = False
        self.mode = mode
        # self.gemma = Gemma2ForCausalLM.from_pretrained("google/gemma-2-2b-it", device_map="auto", torch_dtype=torch.bfloat16)
        # self.embedding_size = 2304
        # LORAconfig = LoraConfig(
        #     task_type=TaskType.CAUSAL_LM,
        #     target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        #     inference_mode=False,  # 训练模式
        #     r=8,  # Lora 秩
        #     lora_alpha=32,  # Lora alaph，具体作用参见 Lora 原理
        #     lora_dropout=0.1  # Dropout 比例
        # )
        #
        # def count_trainable_parameters(model):
        #     model_parameters = filter(lambda p: p.requires_grad, model.parameters())
        #     params = sum([np.prod(p.size()) for p in model_parameters])
        #     return params
        # a = count_trainable_parameters(self.gemma)
        # self.gemma = get_peft_model(self.gemma, LORAconfig)
        # b = count_trainable_parameters(self.gemma)
        # #留下小數點後兩位就好
        # percent = round((b / a) * 100, 3)
        # print("Before: ", a, "After: ", b, "Percent: ", percent, "%")
        # self.gemma.eval()
        # for param in self.gemma.parameters():
        #     param.requires_grad = False

        # self.gpt = GPT2LMHeadModel.from_pretrained('gpt2')
        # self.gpt = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
        # self.gpt = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neo-2.7B")
        # self.embedding_size = self.gpt.transformer.wte.weight.shape[1]
        # self.gpt.eval()
        # for param in self.gpt.parameters():
        #     param.requires_grad = False

        self.falcon = AutoModelForCausalLM.from_pretrained("tiiuae/Falcon3-1B-Base")
        # self.falcon = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-1B")
        self.embedding_size = self.falcon.model.embed_tokens.weight.shape[1]
        # self.embedding_size = 768
        # self.falcon.eval()
        # for param in self.falcon.parameters():
        #     param.requires_grad = False
        self.clip_project = TransformerMapper(mode, prefix_size, self.embedding_size, prefix_length, clip_length,
                                              num_layers)
        self.visual_project_swin = CrossTransformerMapper(mode, prefix_size, self.embedding_size, clip_length,
                                                          num_layers)
        self.visual_project_ESH = CrossTransformerMapper(mode, prefix_size, self.embedding_size, clip_length,
                                                         num_layers)
        #######################################################################################
        ### 20250228_oxford_lower_800up_only800_rest_300up_top300_ESH_cross_concat_swin_tf8 ###
        #######################################################################################
        self.visual_project = nn.Linear(128, 64)
        # self.linear = nn.Linear(self.embedding_size, 2048)

        # self.emotion_linear = nn.Linear(384, 768)
        # self.sentiment_linear = nn.Linear(384, 768)
        # self.humor_linear = nn.Linear(768, 768)
        self.ESH_linear = nn.Linear(64 * 3, 64)
        if mode == 'lora' or self.LoRaActivated:
            self.funnyscore_mlp1 = nn.Linear(self.embedding_size, 1)
            self.funnyscore_relu = nn.ReLU()
            self.funnyscore_mlp2 = nn.Linear(128, 1)
            self.funnyscore_sigmoid = nn.Sigmoid()

    def activateLoRa(self):
        self.LoRaActivated = True
        self.funnyscore_mlp1 = nn.Linear(self.embedding_size, 1)
        self.funnyscore_relu = nn.ReLU()
        self.funnyscore_mlp2 = nn.Linear(128, 1)
        self.funnyscore_sigmoid = nn.Sigmoid()

        LORAconfig = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            inference_mode=False,  # 训练模式
            r=8,  # Lora 秩
            lora_alpha=32,  # Lora alaph，具体作用参见 Lora 原理
            lora_dropout=0.1  # Dropout 比例
        )

        def count_trainable_parameters(model):
            model_parameters = filter(lambda p: p.requires_grad, model.parameters())
            params = sum([np.prod(p.size()) for p in model_parameters])
            return params

        a = count_trainable_parameters(self.falcon)
        self.falcon = get_peft_model(self.falcon, LORAconfig)
        b = count_trainable_parameters(self.falcon)
        # 留下小數點後兩位就好
        percent = round((b / a) * 100, 3)
        print("Before: ", a, "After: ", b, "Percent: ", percent, "%")

def PCloss(logits: torch.Tensor, tokens: torch.Tensor, use_ce=True):
    """
    :param logits: output word logits from the generation model in shape [N, L, E]
    :param tokens:
    :param use_ce:
    :return:
    """
    EPSILON = torch.finfo(torch.bfloat16).eps
    token_length = logits.shape[1]
    vocab_size = logits.shape[2]
    loss_weight = 100
    fp_weights = [4*idx/token_length for idx in range(token_length)]
    fp_weights = torch.FloatTensor(fp_weights).to(logits.device)
    if use_ce:
        ce_thresh = 0.90
        fp_weights_ = fp_weights[None, fp_weights < ce_thresh, None]
        prob = nnf.sigmoid(logits[:, fp_weights < ce_thresh])
        label = nnf.one_hot(tokens[:, fp_weights < ce_thresh], num_classes=vocab_size)
        bce_entropy = label * torch.log(prob + EPSILON)
        bce_inv_entropy = (1 - label) * torch.log(1 - prob + EPSILON) * fp_weights_
        bce_loss = -torch.mean(bce_entropy+bce_inv_entropy)*loss_weight
        ce_loss = nnf.cross_entropy(logits[:, fp_weights >= ce_thresh].reshape(-1, logits.shape[-1]),
                                    tokens[:, fp_weights >= ce_thresh].flatten())
        loss = bce_loss + ce_loss
        return loss
    else:
        fp_weights = fp_weights[None, :, None]
        prob = nnf.sigmoid(logits)
        label = nnf.one_hot(tokens, num_classes=vocab_size)
        bce_entropy = label * torch.log(prob + EPSILON)
        bce_inv_entropy = (1 - label) * torch.log(1 - prob + EPSILON) * fp_weights
        loss = -torch.mean(bce_entropy+bce_inv_entropy)*loss_weight
        return loss

def combine_loss(logits: torch.Tensor, tokens: torch.Tensor, funnyscore: torch.Tensor, output_fc: torch.Tensor):
    output_loss = nnf.cross_entropy(logits.reshape(-1, logits.shape[-1]), tokens.flatten(), ignore_index=0)
    # humor // 1 ==1 > 1 , else == 0> 0
    funnyscore = funnyscore // 1
    print(output_fc.flatten())
    print(funnyscore.flatten())
    fc_loss = nnf.binary_cross_entropy(output_fc.flatten(), funnyscore.flatten())
    # reward  = output_fc.mean()
    loss = output_loss + fc_loss * 10 #- reward * 10
    return output_loss, fc_loss, loss

def generate_beam(model, tokenizer, beam_size: int = 5, prompt=None, embed=None, entry_length=74, temperature=1.0,
                  stop_token: str = ".", repetition_penalty = 1.5):
    model.eval()
    stop_token_index = tokenizer.encode(stop_token)[0]
    tokens = None
    scores = None
    device = next(model.parameters()).device
    seq_lengths = torch.ones(beam_size, device=device)
    is_stopped = torch.zeros(beam_size, device=device, dtype=torch.bool)
    with torch.no_grad():
        if embed is not None:
            generated = embed
        else:
            if tokens is None:
                tokens = torch.tensor(tokenizer.encode(prompt))
                tokens = tokens.unsqueeze(0).to(device)
                # generated = model.gpt.transformer.wte(tokens)
                # generated = model.gemma.model.embed_tokens(tokens)
                # generated = model.gemma.base_model.model.model.embed_tokens(tokens)
                generated = model.falcon.model.embed_tokens(tokens)
        for i in range(entry_length):
            # outputs = model.gemma(inputs_embeds=generated)
            # outputs = model.gpt(inputs_embeds=generated)
            outputs = model.falcon(inputs_embeds=generated)
            logits = outputs.logits
            logits = logits[:, -1, :] / (temperature if temperature > 0 else 1.0)
            # penalty add here #
            if tokens is not None:
                for i in range(tokens.shape[0]):
                    for previous_token in set(tokens[i].tolist()):
                        if logits[i, previous_token] > 0:
                            logits[i, previous_token] /= repetition_penalty
                        else:
                            logits[i, previous_token] *= repetition_penalty


            logits = logits.softmax(-1).log()
            if scores is None:
                scores, next_tokens = logits.topk(beam_size, -1)
                generated = generated.expand(beam_size, *generated.shape[1:])
                next_tokens, scores = next_tokens.permute(1, 0), scores.squeeze(0)
                if tokens is None:
                    tokens = next_tokens
                else:
                    tokens = tokens.expand(beam_size, *tokens.shape[1:])
                    tokens = torch.cat((tokens, next_tokens), dim=1)
            else:
                logits[is_stopped] = -float(np.inf)
                logits[is_stopped, 0] = 0
                scores_sum = scores[:, None] + logits
                seq_lengths[~is_stopped] += 1
                scores_sum_average = scores_sum / seq_lengths[:, None]
                scores_sum_average, next_tokens = scores_sum_average.view(-1).topk(
                    beam_size, -1
                )
                next_tokens_source = next_tokens // scores_sum.shape[1]
                seq_lengths = seq_lengths[next_tokens_source]
                next_tokens = next_tokens % scores_sum.shape[1]
                next_tokens = next_tokens.unsqueeze(1)
                tokens = tokens[next_tokens_source]
                tokens = torch.cat((tokens, next_tokens), dim=1)
                generated = generated[next_tokens_source]
                scores = scores_sum_average * seq_lengths
                is_stopped = is_stopped[next_tokens_source]
            # next_token_embed = model.gpt.transformer.wte(next_tokens.squeeze()).view(generated.shape[0], 1, -1)
            # next_token_embed = model.gemma.model.embed_tokens(next_tokens.squeeze()).view(generated.shape[0], 1, -1)
            # next_token_embed = model.gemma.base_model.model.model.embed_tokens(next_tokens.squeeze()).view( generated.shape[0], 1, -1)
            if model.LoRaActivated:
                next_token_embed = model.falcon.base_model.model.model.embed_tokens(next_tokens.squeeze()).view(generated.shape[0], 1, -1)
            else:
                next_token_embed = model.falcon.model.embed_tokens(next_tokens.squeeze()).view(generated.shape[0], 1, -1)
            generated = torch.cat((generated, next_token_embed), dim=1)
            is_stopped = is_stopped + next_tokens.eq(stop_token_index).squeeze()
            if is_stopped.all():
                break
    scores = scores / seq_lengths
    output_list = tokens.cpu().numpy()
    output_texts = [
        tokenizer.decode(output[: int(length)])
        for output, length in zip(output_list, seq_lengths)
    ]
    order = scores.argsort(descending=True)
    output_texts = [output_texts[i] for i in order]
    return output_texts

def generate2(model, tokenizer, tokens=None, prompt=None, embed=None, entry_count=1, entry_length=74, top_p=0.8,
              temperature=1.0, stop_token: str = ".", repetition_penalty= 1.5):
    model.eval()
    generated_num = 0
    generated_list = []
    stop_token_index = tokenizer.encode(stop_token)[0]
    filter_value = -float("Inf")
    device = next(model.parameters()).device

    with torch.no_grad():

        for entry_idx in range(entry_count):
            if embed is not None:
                generated = embed
            else:
                if tokens is None:
                    tokens = torch.tensor(tokenizer.encode(prompt))
                    tokens = tokens.unsqueeze(0).to(device)

                # generated = model.gpt.transformer.wte(tokens)
                # generated = model.gemma.model.embed_tokens(tokens)
                # generated = model.gemma.base_model.model.model.embed_tokens(tokens)
                if model.LoRaActivated:
                    generated = model.falcon.base_model.model.model.embed_tokens(tokens)
                else:
                    generated = model.falcon.model.embed_tokens(tokens)
            for i in range(entry_length):
                # outputs = model.gemma(inputs_embeds=generated)
                # outputs = model.gpt(inputs_embeds=generated)
                outputs = model.falcon(inputs_embeds=generated)
                logits = outputs.logits
                logits = logits[:, -1, :] / (temperature if temperature > 0 else 1.0)
                # penalty add here #
                # Apply repetition penalty
                if tokens is not None:
                    for i in range(tokens.shape[0]):
                        for previous_token in set(tokens[i].tolist()):
                            if logits[i, previous_token] > 0:
                                logits[i, previous_token] /= repetition_penalty
                            else:
                                logits[i, previous_token] *= repetition_penalty

                sorted_logits, sorted_indices = torch.sort(logits, descending=True)
                cumulative_probs = torch.cumsum(
                    nnf.softmax(sorted_logits, dim=-1), dim=-1
                )
                sorted_indices_to_remove = cumulative_probs > top_p
                sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[
                                                    ..., :-1
                                                    ].clone()
                sorted_indices_to_remove[..., 0] = 0

                indices_to_remove = sorted_indices[sorted_indices_to_remove]
                logits[:, indices_to_remove] = filter_value
                next_token = torch.argmax(logits, -1).unsqueeze(0)
                # next_token_embed = model.gemma.model.embed_tokens(next_token)
                # next_token_embed = model.gemma.base_model.model.model.embed_tokens(next_token)
                # next_token_embed = model.gpt.transformer.wte(next_token)
                if model.LoRaActivated:
                    next_token_embed = model.falcon.base_model.model.model.embed_tokens(next_token)
                else:
                    next_token_embed = model.falcon.model.embed_tokens(next_token)
                if tokens is None:
                    tokens = next_token
                else:
                    tokens = torch.cat((tokens, next_token), dim=1)
                generated = torch.cat((generated, next_token_embed), dim=1)
                if stop_token_index == next_token.item():
                    break
            if tokens.shape == torch.Size([1, 1]):
                output_list = [tokens.squeeze().item()]  # 如果是标量或 1-d，则获取值作为列表
            else:
                output_list = list(tokens.squeeze().cpu().numpy())  # 按正常方式处理
            output_text = tokenizer.decode(output_list)
            generated_list.append(output_text)

    return generated_list[0]

model = ClipCaptionModel(mode='nn', prefix_length=prefix_length, clip_length=prefix_length, prefix_size=512, num_layers=8)
adapter = True
save_file = '20250406_oxford_1408_300_8_300_2_ESH_bert_cross_concat'
i = 1
if adapter :
    model.load_state_dict(torch.load(f'./Model/{save_file}/checkpoint-{i:03d}.pt'))
    model_adapt = ClipCaptionModel(mode='lora', prefix_length=prefix_length, clip_length=prefix_length, prefix_size=512, num_layers=8)

    def count_trainable_parameters(model):
        model_parameters = filter(lambda p: p.requires_grad, model.parameters())
        params = sum([np.prod(p.size()) for p in model_parameters])
        return params


    def weightToLora(fullModel, newModel):
        for name, param in fullModel.named_parameters():
            newModel.state_dict()[name].copy_(param.data)
        for name, param in newModel.named_parameters():
            if 'falcon' not in name:
                if "lora_" not in name:  # 只讓 LoRA 參數訓練
                    if 'bias' in name:
                        param.requires_grad = True
                    else:
                        param.requires_grad = False
                    if 'funnyscore' in name:
                        param.requires_grad = True
                else:
                    param.requires_grad = True
        for name, param in newModel.named_parameters():
            print(f"{name}: requires_grad={param.requires_grad}")
        return newModel

    a = count_trainable_parameters(model)
    model = weightToLora(model, model_adapt)
    del model_adapt
    gc.collect()
    b = count_trainable_parameters(model)
    percent = round((b / a) * 100, 3)
    print("Before: ", a, "After: ", b, "Percent: ", percent, "%")

    # model.activateLoRa()
    #
    # b = count_trainable_parameters(model)
    # percent = round((b / a) * 100, 3)
    # print("Before: ", a, "After: ", b, "Percent: ", percent, "%")

save_file = '20250406_100up_only100_passlength_o_10_SD_base_0406_oxford_1408_300_8_300_2_ESH_bert_cross_concat_combineLoss'
for i in range(20):
    if os.path.exists(f'./Model/{save_file}/checkpoint-{i + 1:03d}.pt'):
        model.load_state_dict(torch.load(f'./Model/{save_file}/checkpoint-{i + 1:03d}.pt'))
        model = model.eval()
        model = model.to(device, dtype=torch.bfloat16)
        print(f"Model {i + 1:03d} loaded.")
        out_dir = f'./Model/{save_file}/'
        # pred = Predictor(prefix_length, cp_num=i + 1, train_caption=[], test_caption=[],train_image_id_list=[], test_image_id_list=[])
        # pred.test(testDataset, model, out_dir)
        pred = Predictor(prefix_length, cp_num=i + 1, train_caption=train_caption, test_caption=test_caption, train_image_id_list=train_image_id_list, test_image_id_list=test_image_id_list)
        pred.predict("test", test_tokens, test_mask, test_prefix, test_gt, model, test_emotion, test_sentiment, test_humor, test_funnyscore)
        pred.predict("train", train_tokens, train_mask, train_prefix, train_gt, model, train_emotion, train_sentiment, train_humor, train_funnyscore)

AllCaption = pd.DataFrame()
for i in range(20):
    if os.path.exists(f'./Model/{save_file}/checkpoint-{i + 1:03d}.pt'):
        # df = pd.read_csv(f'./Model/{save_file}/{save_file}_test_{i + 1:03d}.csv')
        df = pd.read_csv(f'./Model/{save_file}/test_{i + 1:03d}.csv')
        if adapter:
            textAndLoss = df[['text', 'loss', 'caption_loss', 'fc_loss', 'fitCount', 'gtNum', 'fluency', 'diversity', 'bleu1', 'bleu2', 'bleu3', 'bleu4']]
        else:
            textAndLoss = df[['text', 'loss', 'fitCount', 'gtNum', 'fluency', 'diversity', 'bleu1', 'bleu2', 'bleu3', 'bleu4']]
        if AllCaption.empty:
            AllCaption = df[['Name', 'image_id']]
        AllCaption = pd.concat([AllCaption, textAndLoss], axis=1)
# AllCaption.to_csv(f'./Model/{save_file}/{save_file}_test_all.csv', float_format='%.15f', index=False)
AllCaption.to_csv(f'./Model/{save_file}/test_all.csv', float_format='%.15f', index=False)

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_6932\2710020929.py:1183: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f'./Model/{save_file}/checkpoint-{i:03d}.pt'))

falcon.model.embed_tokens.weight: requires_grad=True
falcon.model.layers.0.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.0.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.0.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.0.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.0.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.0.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.0.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.0.input_layernorm.weight: requires_grad=True
falcon.model.layers.0.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.1.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.1.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.1.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.1.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.1.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.1.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.1.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.1.input_layernorm.weight: requires_grad=True
falcon.model.layers.1.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.2.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.2.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.2.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.2.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.2.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.2.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.2.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.2.input_layernorm.weight: requires_grad=True
falcon.model.layers.2.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.3.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.3.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.3.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.3.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.3.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.3.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.3.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.3.input_layernorm.weight: requires_grad=True
falcon.model.layers.3.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.4.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.4.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.4.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.4.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.4.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.4.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.4.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.4.input_layernorm.weight: requires_grad=True
falcon.model.layers.4.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.5.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.5.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.5.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.5.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.5.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.5.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.5.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.5.input_layernorm.weight: requires_grad=True
falcon.model.layers.5.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.6.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.6.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.6.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.6.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.6.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.6.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.6.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.6.input_layernorm.weight: requires_grad=True
falcon.model.layers.6.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.7.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.7.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.7.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.7.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.7.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.7.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.7.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.7.input_layernorm.weight: requires_grad=True
falcon.model.layers.7.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.8.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.8.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.8.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.8.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.8.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.8.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.8.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.8.input_layernorm.weight: requires_grad=True
falcon.model.layers.8.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.9.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.9.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.9.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.9.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.9.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.9.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.9.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.9.input_layernorm.weight: requires_grad=True
falcon.model.layers.9.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.10.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.10.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.10.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.10.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.10.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.10.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.10.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.10.input_layernorm.weight: requires_grad=True
falcon.model.layers.10.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.11.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.11.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.11.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.11.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.11.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.11.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.11.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.11.input_layernorm.weight: requires_grad=True
falcon.model.layers.11.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.12.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.12.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.12.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.12.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.12.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.12.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.12.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.12.input_layernorm.weight: requires_grad=True
falcon.model.layers.12.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.13.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.13.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.13.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.13.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.13.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.13.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.13.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.13.input_layernorm.weight: requires_grad=True
falcon.model.layers.13.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.14.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.14.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.14.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.14.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.14.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.14.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.14.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.14.input_layernorm.weight: requires_grad=True
falcon.model.layers.14.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.15.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.15.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.15.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.15.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.15.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.15.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.15.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.15.input_layernorm.weight: requires_grad=True
falcon.model.layers.15.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.16.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.16.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.16.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.16.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.16.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.16.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.16.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.16.input_layernorm.weight: requires_grad=True
falcon.model.layers.16.post_attention_layernorm.weight: requires_grad=True
falcon.model.layers.17.self_attn.q_proj.weight: requires_grad=True
falcon.model.layers.17.self_attn.k_proj.weight: requires_grad=True
falcon.model.layers.17.self_attn.v_proj.weight: requires_grad=True
falcon.model.layers.17.self_attn.o_proj.weight: requires_grad=True
falcon.model.layers.17.mlp.gate_proj.weight: requires_grad=True
falcon.model.layers.17.mlp.up_proj.weight: requires_grad=True
falcon.model.layers.17.mlp.down_proj.weight: requires_grad=True
falcon.model.layers.17.input_layernorm.weight: requires_grad=True
falcon.model.layers.17.post_attention_layernorm.weight: requires_grad=True
falcon.model.norm.weight: requires_grad=True
falcon.lm_head.weight: requires_grad=True
clip_project.prefix_const: requires_grad=False
clip_project.transformer.layers.0.norm1.weight: requires_grad=False
clip_project.transformer.layers.0.norm1.bias: requires_grad=True
clip_project.transformer.layers.0.attn.to_queries.weight: requires_grad=False
clip_project.transformer.layers.0.attn.to_queries.bias: requires_grad=True
clip_project.transformer.layers.0.attn.to_queries.lora_A: requires_grad=True
clip_project.transformer.layers.0.attn.to_queries.lora_B: requires_grad=True
clip_project.transformer.layers.0.attn.to_keys_values.weight: requires_grad=False
clip_project.transformer.layers.0.attn.to_keys_values.bias: requires_grad=True
clip_project.transformer.layers.0.attn.to_keys_values.lora_A: requires_grad=True
clip_project.transformer.layers.0.attn.to_keys_values.lora_B: requires_grad=True
clip_project.transformer.layers.0.attn.project.weight: requires_grad=False
clip_project.transformer.layers.0.attn.project.bias: requires_grad=True
clip_project.transformer.layers.0.attn.project.lora_A: requires_grad=True
clip_project.transformer.layers.0.attn.project.lora_B: requires_grad=True
clip_project.transformer.layers.0.norm2.weight: requires_grad=False
clip_project.transformer.layers.0.norm2.bias: requires_grad=True
clip_project.transformer.layers.0.mlp.fc1.weight: requires_grad=False
clip_project.transformer.layers.0.mlp.fc1.bias: requires_grad=True
clip_project.transformer.layers.0.mlp.fc1.lora_A: requires_grad=True
clip_project.transformer.layers.0.mlp.fc1.lora_B: requires_grad=True
clip_project.transformer.layers.0.mlp.fc2.weight: requires_grad=False
clip_project.transformer.layers.0.mlp.fc2.bias: requires_grad=True
clip_project.transformer.layers.0.mlp.fc2.lora_A: requires_grad=True
clip_project.transformer.layers.0.mlp.fc2.lora_B: requires_grad=True
clip_project.transformer.layers.1.norm1.weight: requires_grad=False
clip_project.transformer.layers.1.norm1.bias: requires_grad=True
clip_project.transformer.layers.1.attn.to_queries.weight: requires_grad=False
clip_project.transformer.layers.1.attn.to_queries.bias: requires_grad=True
clip_project.transformer.layers.1.attn.to_queries.lora_A: requires_grad=True
clip_project.transformer.layers.1.attn.to_queries.lora_B: requires_grad=True
clip_project.transformer.layers.1.attn.to_keys_values.weight: requires_grad=False
clip_project.transformer.layers.1.attn.to_keys_values.bias: requires_grad=True
clip_project.transformer.layers.1.attn.to_keys_values.lora_A: requires_grad=True
clip_project.transformer.layers.1.attn.to_keys_values.lora_B: requires_grad=True
clip_project.transformer.layers.1.attn.project.weight: requires_grad=False
clip_project.transformer.layers.1.attn.project.bias: requires_grad=True
clip_project.transformer.layers.1.attn.project.lora_A: requires_grad=True
clip_project.transformer.layers.1.attn.project.lora_B: requires_grad=True
clip_project.transformer.layers.1.norm2.weight: requires_grad=False
clip_project.transformer.layers.1.norm2.bias: requires_grad=True
clip_project.transformer.layers.1.mlp.fc1.weight: requires_grad=False
clip_project.transformer.layers.1.mlp.fc1.bias: requires_grad=True
clip_project.transformer.layers.1.mlp.fc1.lora_A: requires_grad=True
clip_project.transformer.layers.1.mlp.fc1.lora_B: requires_grad=True
clip_project.transformer.layers.1.mlp.fc2.weight: requires_grad=False
clip_project.transformer.layers.1.mlp.fc2.bias: requires_grad=True
clip_project.transformer.layers.1.mlp.fc2.lora_A: requires_grad=True
clip_project.transformer.layers.1.mlp.fc2.lora_B: requires_grad=True
clip_project.transformer.layers.2.norm1.weight: requires_grad=False
clip_project.transformer.layers.2.norm1.bias: requires_grad=True
clip_project.transformer.layers.2.attn.to_queries.weight: requires_grad=False
clip_project.transformer.layers.2.attn.to_queries.bias: requires_grad=True
clip_project.transformer.layers.2.attn.to_queries.lora_A: requires_grad=True
clip_project.transformer.layers.2.attn.to_queries.lora_B: requires_grad=True
clip_project.transformer.layers.2.attn.to_keys_values.weight: requires_grad=False
clip_project.transformer.layers.2.attn.to_keys_values.bias: requires_grad=True
clip_project.transformer.layers.2.attn.to_keys_values.lora_A: requires_grad=True
clip_project.transformer.layers.2.attn.to_keys_values.lora_B: requires_grad=True
clip_project.transformer.layers.2.attn.project.weight: requires_grad=False
clip_project.transformer.layers.2.attn.project.bias: requires_grad=True
clip_project.transformer.layers.2.attn.project.lora_A: requires_grad=True
clip_project.transformer.layers.2.attn.project.lora_B: requires_grad=True
clip_project.transformer.layers.2.norm2.weight: requires_grad=False
clip_project.transformer.layers.2.norm2.bias: requires_grad=True
clip_project.transformer.layers.2.mlp.fc1.weight: requires_grad=False
clip_project.transformer.layers.2.mlp.fc1.bias: requires_grad=True
clip_project.transformer.layers.2.mlp.fc1.lora_A: requires_grad=True
clip_project.transformer.layers.2.mlp.fc1.lora_B: requires_grad=True
clip_project.transformer.layers.2.mlp.fc2.weight: requires_grad=False
clip_project.transformer.layers.2.mlp.fc2.bias: requires_grad=True
clip_project.transformer.layers.2.mlp.fc2.lora_A: requires_grad=True
clip_project.transformer.layers.2.mlp.fc2.lora_B: requires_grad=True
clip_project.transformer.layers.3.norm1.weight: requires_grad=False
clip_project.transformer.layers.3.norm1.bias: requires_grad=True
clip_project.transformer.layers.3.attn.to_queries.weight: requires_grad=False
clip_project.transformer.layers.3.attn.to_queries.bias: requires_grad=True
clip_project.transformer.layers.3.attn.to_queries.lora_A: requires_grad=True
clip_project.transformer.layers.3.attn.to_queries.lora_B: requires_grad=True
clip_project.transformer.layers.3.attn.to_keys_values.weight: requires_grad=False
clip_project.transformer.layers.3.attn.to_keys_values.bias: requires_grad=True
clip_project.transformer.layers.3.attn.to_keys_values.lora_A: requires_grad=True
clip_project.transformer.layers.3.attn.to_keys_values.lora_B: requires_grad=True
clip_project.transformer.layers.3.attn.project.weight: requires_grad=False
clip_project.transformer.layers.3.attn.project.bias: requires_grad=True
clip_project.transformer.layers.3.attn.project.lora_A: requires_grad=True
clip_project.transformer.layers.3.attn.project.lora_B: requires_grad=True
clip_project.transformer.layers.3.norm2.weight: requires_grad=False
clip_project.transformer.layers.3.norm2.bias: requires_grad=True
clip_project.transformer.layers.3.mlp.fc1.weight: requires_grad=False
clip_project.transformer.layers.3.mlp.fc1.bias: requires_grad=True
clip_project.transformer.layers.3.mlp.fc1.lora_A: requires_grad=True
clip_project.transformer.layers.3.mlp.fc1.lora_B: requires_grad=True
clip_project.transformer.layers.3.mlp.fc2.weight: requires_grad=False
clip_project.transformer.layers.3.mlp.fc2.bias: requires_grad=True
clip_project.transformer.layers.3.mlp.fc2.lora_A: requires_grad=True
clip_project.transformer.layers.3.mlp.fc2.lora_B: requires_grad=True
clip_project.transformer.layers.4.norm1.weight: requires_grad=False
clip_project.transformer.layers.4.norm1.bias: requires_grad=True
clip_project.transformer.layers.4.attn.to_queries.weight: requires_grad=False
clip_project.transformer.layers.4.attn.to_queries.bias: requires_grad=True
clip_project.transformer.layers.4.attn.to_queries.lora_A: requires_grad=True
clip_project.transformer.layers.4.attn.to_queries.lora_B: requires_grad=True
clip_project.transformer.layers.4.attn.to_keys_values.weight: requires_grad=False
clip_project.transformer.layers.4.attn.to_keys_values.bias: requires_grad=True
clip_project.transformer.layers.4.attn.to_keys_values.lora_A: requires_grad=True
clip_project.transformer.layers.4.attn.to_keys_values.lora_B: requires_grad=True
clip_project.transformer.layers.4.attn.project.weight: requires_grad=False
clip_project.transformer.layers.4.attn.project.bias: requires_grad=True
clip_project.transformer.layers.4.attn.project.lora_A: requires_grad=True
clip_project.transformer.layers.4.attn.project.lora_B: requires_grad=True
clip_project.transformer.layers.4.norm2.weight: requires_grad=False
clip_project.transformer.layers.4.norm2.bias: requires_grad=True
clip_project.transformer.layers.4.mlp.fc1.weight: requires_grad=False
clip_project.transformer.layers.4.mlp.fc1.bias: requires_grad=True
clip_project.transformer.layers.4.mlp.fc1.lora_A: requires_grad=True
clip_project.transformer.layers.4.mlp.fc1.lora_B: requires_grad=True
clip_project.transformer.layers.4.mlp.fc2.weight: requires_grad=False
clip_project.transformer.layers.4.mlp.fc2.bias: requires_grad=True
clip_project.transformer.layers.4.mlp.fc2.lora_A: requires_grad=True
clip_project.transformer.layers.4.mlp.fc2.lora_B: requires_grad=True
clip_project.transformer.layers.5.norm1.weight: requires_grad=False
clip_project.transformer.layers.5.norm1.bias: requires_grad=True
clip_project.transformer.layers.5.attn.to_queries.weight: requires_grad=False
clip_project.transformer.layers.5.attn.to_queries.bias: requires_grad=True
clip_project.transformer.layers.5.attn.to_queries.lora_A: requires_grad=True

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_6932\2710020929.py:1227: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(f'./Model/{save_file}/checkpoint-{i + 1:03d}.pt'))

Model 001 loaded.
clip model loaded
====================== test 1======================
--------- ground truth ---------
they're the ones that stare at their shattered friends.
--------- generate_beam ---------
---------train---------
torch.Size([1, 64, 2048]) torch.Size([1, 64, 2048])
torch.Size([1, 128, 131072])
funnyscore 751.0
tensor([0.1128], dtype=torch.bfloat16, grad_fn=<SigmoidBackward0>)
tensor([752.], dtype=torch.bfloat16)

RuntimeError: all elements of target should be between 0 and 1

### Generate Oxford

In [1]:
import pandas as pd
from tqdm import tqdm
# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# dirPath = '../Data/Instagram/Minigpt4_mcdonalds_switzerland.csv'
data = pd.read_csv(
    '../../Data/Oxford_HIC/Generate_original/Minigpt4_sentence_generate_Oxford/Minigpt4_sentence_generate_Oxford_miss.csv')

In [2]:
import torch
import torch.nn.functional as F
from transformers import BertTokenizer, BertModel

# 加载预训练的BERT模型和分词器
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def bertTokenize(text):

    # 将文本编码为输入ID和注意力掩

    tokens = tokenizer(text, return_tensors='pt', truncation=False)
    seq_len = tokens['input_ids'].shape[1]
    max_len = max(seq_len, 64)

    inputs = tokenizer(text, return_tensors='pt', truncation=False, padding ='max_length', max_length=max_len)
    input_ids = inputs['input_ids']
    attention_mask = inputs['attention_mask']

    # 使用BERT模型获取文本的向量表示
    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)
        # 获取最后一层的隐藏状态
        last_hidden_state = outputs.last_hidden_state
        pooled_embedding = F.adaptive_max_pool1d(last_hidden_state.permute(0, 2, 1), 64).permute(0, 2, 1)
    pbar.update(1)
    return pooled_embedding.squeeze(0).tolist()

In [3]:
new_df = pd.DataFrame()
new_df['image_id'] = data['image_id'][:5]
with tqdm(total=len(data)) as pbar:
    new_df['emotion'] = data[:5].apply(lambda x: bertTokenize(x['emotion']), axis=1)
    pbar.close()

  1%|          | 5/512 [00:05<09:51,  1.17s/it]

In [11]:
from tqdm import tqdm
new_df = pd.DataFrame()
new_df['image_id'] = data['image_id']
with tqdm(total=len(data)) as pbar:
    new_df['emotion'] = data.apply(lambda x: bertTokenize(x['emotion']), axis=1)
    pbar.close()
with tqdm(total=len(data)) as pbar:
    new_df['sentiment'] = data.apply(lambda x: bertTokenize(x['sentiment']), axis=1)
    pbar.close()
with tqdm(total=len(data)) as pbar:
    new_df['humor'] = data.apply(lambda x: bertTokenize(x['humor']), axis=1)
    pbar.close()
new_df.shape

100%|██████████| 1432/1432 [00:40<00:00, 35.78it/s]
100%|██████████| 1432/1432 [00:40<00:00, 35.46it/s]
100%|██████████| 1432/1432 [00:39<00:00, 36.25it/s]

(1432, 4)

In [12]:
new_df.to_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_bert.csv')

In [15]:
test = pd.read_csv('../../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_bert.csv')

In [16]:
import ast
import torch
test = test[:5]
test['emotion'] = test['emotion'].apply(ast.literal_eval)
torch.tensor(test['emotion'][0]).shape

torch.Size([64, 768])

# MiniGPT4

In [127]:
from string import punctuation

import pandas as pd
from scipy.special import huber
from sklearn.model_selection import train_test_split
import re
import random
from nltk import sent_tokenize
import nltk
from tqdm import tqdm
# from albumentations.core.transforms_interface import DualTransform, BasicTransform
# from transformers import BertTokenizer, AutoTokenizer, RobertaTokenizer,BertForMaskedLM, RobertaForMaskedLM, AutoModelForMaskedLM
# import albumentations
import torch
import re
import string


# dirPath = '../Data/Oxford_HIC/CaptionID_oxford_hic_data.csv'
# dirPath = '../Data/Oxford_HIC/Minigpt4_Oxford.csv'

# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# dirPath = '../Data/Instagram/CaptionID_sonicdrivein.csv'
# data = pd.read_csv(dirPath)

original = pd.read_csv('../../Data/Instagram/CaptionID_mcdonalds_switzerland.csv')
generate = pd.read_csv('../../Data/Instagram/Generate_mcdonalds_switzerland.csv')
original['caption'] = original['caption'].str.lower()
generate['caption'] = generate['caption'].str.lower()

In [128]:
image_id_counts = generate['image_id'].value_counts()
print('image_id_counts: ', image_id_counts.shape)
original['text_len'] = original['caption'].apply(lambda x: len(x.split()))
original['gen_count'] = original['image_id'].apply(lambda x: image_id_counts[x] if x in image_id_counts else 0)
original

image_id_counts:  (1125,)

,caption,image_id,funny_score,caption_id,text_len,gen_count
0,how cool is that?!😍 thanks gegette_and_co for ...,mcdonalds_switzerland_0,0.0,caption1,21,289
1,"for me, it's a deal breaker.",mcdonalds_switzerland_1,1.0,caption2,6,104
2,sweet tooth alert! please give a warm welcome ...,mcdonalds_switzerland_2,0.0,caption3,14,170
3,pov: you have a free menu with your loyalty po...,mcdonalds_switzerland_3,1.0,caption4,14,258
4,which shape do you prefer? mine is the bell 🔔\...,mcdonalds_switzerland_4,0.0,caption5,21,254
...,...,...,...,...,...,...
1120,the chips! #theprimeburger,mcdonalds_switzerland_2081,0.0,caption1125,3,24
1121,#theprimeburger #ingredients,mcdonalds_switzerland_2082,0.0,caption1126,2,10
1122,the delicious #theprimeburger,mcdonalds_switzerland_2084,0.0,caption1127,3,10
1123,#theprimeburger #new @reneschudel,mcdonalds_switzerland_2085,0.0,caption1128,3,35
1124,instagram pic no1 :-) #spring,mcdonalds_switzerland_2086,0.0,caption1129,5,65

In [129]:
image_id_counts = generate['image_id'].value_counts()
valid_image_ids = image_id_counts[(image_id_counts >= 200)].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = generate[generate['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)
images = set(filtered_data['image_id'].unique())

shape of valid_image_ids:  (477,)
shape of filtered_data:  (163994, 3)

In [132]:
original = original[original['gen_count'] >= 100]
temp = original[original['text_len'] >= 12]
temp_img = set(temp['image_id'].unique())
print(len(temp_img), len(images))
print('intersection: ', len(images.intersection(temp_img)))
print('difference: ', len(images.difference(temp_img)))
print('difference: ', len(temp_img.difference(images)))

621 477
intersection:  466
difference:  11
difference:  155

In [9]:
temp = temp.sort_values(by=['funny_score'], ascending=[False])
temp[:100]

,caption,image_id,funny_score,caption_id,text_len,gen_count
827,we asked you for your favorite songs & artists...,sonicdrivein_831,1.0,caption828,25,438
306,no judgements at the drive-in. 🤣 watch the ful...,sonicdrivein_306,1.0,caption307,20,171
86,2024 solar eclipse 🤝 our new blackout slush fl...,sonicdrivein_86,1.0,caption87,19,160
307,the best car feature ever? no car seats. watch...,sonicdrivein_307,1.0,caption308,20,348
1454,when you look down and realize you ate all you...,sonicdrivein_1462,1.0,caption1458,17,234
...,...,...,...,...,...,...
475,"this season, give the gift of a $25 sonic gift...",sonicdrivein_479,0.0,caption476,26,397
478,when the food isn’t the only thing that’s comi...,sonicdrivein_482,0.0,caption479,18,242
480,treat your friends who are on the nice list th...,sonicdrivein_484,0.0,caption481,17,256
481,while we’re all in the queue for tickets… what...,sonicdrivein_485,0.0,caption482,18,276
485,tots have taken on a mind of their own...👀 @ye...,sonicdrivein_489,0.0,caption486,18,157

In [ ]:
# ['text_len'] >= 24]
# 301 900
# intersection:  300
# difference:  600
# difference:  1

In [159]:
filtered_data['text_len'] = filtered_data['caption'].apply(lambda x: len(x.split()))
filtered_data.describe()

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_6272\4250894817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['text_len'] = filtered_data['caption'].apply(lambda x: len(x.split()))

         funny_score       text_len
count  334806.000000  334806.000000
mean        0.073222      39.927486
std         0.257638      49.493781
min         0.000000       9.000000
25%         0.000000      20.000000
50%         0.000000      24.000000
75%         0.000000      48.000000
max         1.000000     384.000000

In [163]:

image_id_counts = generate['image_id'].value_counts()
valid_image_ids = image_id_counts[(image_id_counts >= 100) & (image_id_counts < 200)].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = generate[generate['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)
temp = filtered_data.merge(original, on='image_id', how='inner')
temp.describe()

shape of valid_image_ids:  (622,)
shape of filtered_data:  (91423, 3)

       funny_score_x  funny_score_y      text_len     aug_count
count   91423.000000   91423.000000  91423.000000  91423.000000
mean        0.239256       0.239256     12.118121    151.918368
std         0.420905       0.420905      3.742989     26.702788
min         0.000000       0.000000      5.000000    100.000000
25%         0.000000       0.000000      9.000000    131.000000
50%         0.000000       0.000000     11.000000    152.000000
75%         0.000000       0.000000     14.000000    173.000000
max         1.000000       1.000000     30.000000    199.000000

In [164]:
filtered_data['text_len'] = filtered_data['caption'].apply(lambda x: len(x.split()))
filtered_data.describe()

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_6272\4250894817.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['text_len'] = filtered_data['caption'].apply(lambda x: len(x.split()))

        funny_score      text_len
count  91423.000000  91423.000000
mean       0.239256     12.936088
std        0.420905      3.945971
min        0.000000      5.000000
25%        0.000000     10.000000
50%        0.000000     12.000000
75%        0.000000     15.000000
max        1.000000     31.000000

In [215]:
split1 = original[original['gen_count'] >= 100]
split2 = generate.merge(split1, on='image_id', how='inner')
split2['text_len'] = split2['caption_x'].apply(lambda x: len(x.split()))
print("shape of splt1: ", split2.shape)

shape of splt1:  (426229, 8)

In [226]:
original = original[original['gen_count'] >= 100]
original = original[original['text_len'] >= 11]
data = data.merge(original, on='image_id', how='inner')
sss.shape

(1522, 6)

(1253, 6)

In [216]:
image_id_counts = split2['image_id'].value_counts()
print('image_id_counts: ', image_id_counts.shape)
valid_image_ids = image_id_counts[(image_id_counts >= 100) & (image_id_counts < 200)].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = split2[split2['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)

image_id_counts:  (1522,)
shape of valid_image_ids:  (622,)
shape of filtered_data:  (91423, 8)

In [219]:
image_id_counts = generate['image_id'].value_counts()
valid_image_ids_gen = image_id_counts[(image_id_counts >= 200)].index
print('image_id_counts: ', image_id_counts.shape)
print('valid_image_ids_gen: ', valid_image_ids_gen.shape)
filtered_data = generate[generate['image_id'].isin(valid_image_ids_gen)]
filtered_data['text_len'] = filtered_data['caption'].apply(lambda x: len(x.split()))
filtered_data

image_id_counts:  (2208,)
valid_image_ids_gen:  (900,)

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_6272\1868607443.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['text_len'] = filtered_data['caption'].apply(lambda x: len(x.split()))

,caption,image_id,funny_score,text_len
1127,boss asked me to make something cool...what is...,sonicdrivein_12,0.0,12
1128,someone asked me to make something cool ... wh...,sonicdrivein_12,0.0,14
1129,you asked me to make something cool ... what i...,sonicdrivein_12,0.0,14
1130,he asked me to make something cool ... what is...,sonicdrivein_12,0.0,14
1131,they asked me to make something cool ... what ...,sonicdrivein_12,0.0,14
...,...,...,...,...
460259,"sonicland has moved to san antonio, tex. this ...",sonicdrivein_2237,0.0,14
460260,"sonicland has moved to san antonio, tex. this ...",sonicdrivein_2237,0.0,14
460261,"sonicland has moved to san antonio, tex. this ...",sonicdrivein_2237,0.0,14
460262,"sonicland has moved to san antonio, tex. this ...",sonicdrivein_2237,0.0,14
460263,"sonicland has moved to san antonio, tex. this ...",sonicdrivein_2237,0.0,14

In [193]:
image_id_counts = split2['image_id'].value_counts()
valid_image_ids = image_id_counts[(image_id_counts >= 200)].index
for img in valid_image_ids:
    if img not in valid_image_ids_gen:
        print(img)
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = split2[split2['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)

shape of valid_image_ids:  (899,)
shape of filtered_data:  (334596, 8)

In [210]:
split1 = original[original['text_len'] >= 30]
image_id_counts = split1['image_id'].value_counts()

for img in image_id_counts.index:
    if img not in valid_image_ids_gen:
        print(img)
print('image_id_counts: ', image_id_counts.shape)

sonicdrivein_917
image_id_counts:  (179,)

In [23]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
def setofcategory(text):
    text = str(text)
    text = text.lower()
    # remove spaces
    text = text.strip()
    # split by ;
    text = text.split(';')
    # get set
    text = set(text)
    txt = ''
    for i in text:
        word = lemmatizer.lemmatize(i)
        if txt == '':
            txt = word
        else:
            txt += ';' + word
    return txt

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\TonyLab\AppData\Roaming\nltk_data...

In [25]:
data['emotion'] = data['emotion'].apply(lambda x: setofcategory(x))
data['sentiment'] = data['sentiment'].apply(lambda x: setofcategory(x))
data['humor'] = data['humor'].apply(lambda x: setofcategory(x))
data.to_csv(dirPath, index=False)

In [74]:
emotion_df = pd.DataFrame()
emotion_df['image_id'] = data['image_id']
# emotion_df['sentiment'] = data['sentiment']
emotion_df

         image_id
0    bokete_94229
1       imgflip_0
2       imgflip_1
3       imgflip_2
4       imgflip_3
..            ...
429  imgflip_1472
430  imgflip_1508
431  imgflip_1535
432  imgflip_1774
433  imgflip_1781

[434 rows x 1 columns]

In [76]:
all_emotion = set()
for i in range(len(emotion_df)):
    text = str(data['humor'][i])
    text = text.split(';')
    temp = set(text)
    all_emotion = all_emotion.union(temp)
len(all_emotion)

255

In [77]:
emotions = data['humor'].str.split(';').explode().unique()

# 建立 one-hot 編碼欄位
for emotion in emotions:
    emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)

C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)
C:\Users\TonyLab\AppData\Local\Temp\ipykernel_2396\2476847226.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  emotion_df[emotion] = data['humor'].apply(lambda x: 1 if emotion in str(x).split(';') else 0)

In [78]:
print(emotion_df.shape)
emotion_df

(434, 256)

,image_id,irony,amusement,playful,sarcasm,none,exaggeration,mild,playfulness,innocence,...,privacy,seclusion,cumbersome,large,iron,satirical,crown,wearing,foreshadowing,carefree
0,bokete_94229,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,imgflip_0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,imgflip_1,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,imgflip_2,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,imgflip_3,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,imgflip_1472,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
430,imgflip_1508,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
431,imgflip_1535,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
432,imgflip_1774,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
433,imgflip_1781,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
emotion_df.to_csv('../Data/Oxford_HIC/Minigpt4_Oxford_humor.csv', index=False)

In [83]:
emotion_df[emotion_df['image_id'] == 'imgflip_7']
print(emotion_df[emotion_df['image_id'] == 'imgflip_7'].shape)
# except image_id
print(emotion_df[emotion_df['image_id'] == 'imgflip_7'].iloc[:, 1:].shape)

(1, 256)
(1, 255)

In [84]:
emotion_df[emotion_df['image_id'] == 'imgflip_7'].iloc[:, 1:].values

array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [87]:
import torch        # to tensor
A = torch.tensor(emotion_df[emotion_df['image_id'] == 'imgflip_7'].iloc[:, 1:].values, dtype=torch.bfloat16)
# padding to 768
A = torch.nn.functional.pad(A, (0, 768 - A.shape[1]), 'constant', 0)
print(A.shape)

torch.Size([1, 255])

In [2]:
emotion_df= pd.read_csv('../../Data/Oxford_HIC/Minigpt4_Oxford_emotion.csv')
sentiment = pd.read_csv('../../Data/Oxford_HIC/Minigpt4_Oxford_sentiment.csv')
humor = pd.read_csv('../../Data/Oxford_HIC/Minigpt4_Oxford_humor.csv')
print(emotion_df.shape, sentiment.shape, humor.shape)

(434, 402) (434, 419) (434, 256)

In [3]:
emotion_df['sum'] = emotion_df.iloc[:, 1:].sum(axis=1)
sentiment['sum'] = sentiment.iloc[:, 1:].sum(axis=1)
humor['sum'] = humor.iloc[:, 1:].sum(axis=1)
print(max(emotion_df['sum']), max(sentiment['sum']), max(humor['sum']))

15 12 14

In [ ]:
emotions_data = pd.read_csv('../../Oxford_HIC/Minigpt4_Oxford.csv')
for i in range(len(emotions_data)):
    tokens = torch.tensor(emotions_data.iloc[i, 1:].values, dtype=torch.bfloat16)

In [8]:
def addwhat(text, categorylist):
    if ':' in text:
        text = text.split(":")[0]
    elif '-' in text:
        text = text.split("-")[0]
    # remove punctuation and spaces
    text = re.sub(r'[^\w\s]', '', text)
    text = text.strip()
    # check if only one word
    if '.' in text:
        text = text.split(".")[1]
        text = text.strip()
    if ' ' in text:
        return categorylist
    if categorylist != '':
        categorylist += ';' + text
    else:
        categorylist = text
    return categorylist

def categorize(text, emotion, sentiment, humor):
    split1 = text.split("\n\n")
    category = ''
    if emotion == 'nan':
        emotion = ''
    if sentiment == 'nan':
        sentiment = ''
    if humor == 'nan':
        humor = ''
    for i in range(len(split1)):
        if category == '':
            if 'emotion' in split1[i]:
                category = 'emotion'
                continue
            elif 'sentiment' in split1[i]:
                category = 'sentiment'
                continue
            elif 'humor' in split1[i]:
                category = 'humor'
                continue
        else:
            if '*' in split1[i]:
                split2 = split1[i].split("\n")
                for j in range(len(split2)):
                    if '*' in split1[i]:
                        if category == 'emotion':
                            emotion = addwhat(split2[j], emotion)
                        elif category == 'sentiment':
                            sentiment = addwhat(split2[j], sentiment)
                        elif category == 'humor':
                            humor = addwhat(split2[j], humor)
                category = ''
    return emotion, sentiment, humor

In [9]:
data['emotion'], data['sentiment'], data['humor']  = zip(*data.apply(lambda x: categorize(x['chat'], str(x['emotion']), str(x['sentiment']), str(x['humor'])), axis=1))

In [10]:
# if emotion, sentiment, humor are all filled done = 'O'
# if emotion, sentiment, humor are all empty done = 'X'
# if emotion, sentiment, humor are not all empty done = 'P'
def checkdone(emotion, sentiment, humor, done):
    if emotion != '' and sentiment != '' and humor != '':
        return 'O'
    else:
        return done

data['done'] = data.apply(lambda x: checkdone(x['emotion'], x['sentiment'], x['humor'], x['done']), axis=1)
data

,image_id,funny_score,chat,done,emotion,sentiment,humor
0,sonicdrivein_0,0.0,the image is of a large room with a blue floor...,O,relaxed;curious,neutral;calm,none
1,sonicdrivein_2,0.0,"the image shows a woman sitting on a couch, we...",done,,,
2,sonicdrivein_8,0.0,the image shows a group of people sitting in a...,O,happiness;joy;contentment;relaxation,positive;cheerful;lighthearted,playful;whimsical;silly
3,sonicdrivein_11,0.0,the image shows two people standing in front o...,done,,,
4,sonicdrivein_12,0.0,the image shows a person wearing blue shirt ho...,done,,,
...,...,...,...,...,...,...,...
1517,sonicdrivein_2235,0.0,this image shows a group of people standing on...,X,,,
1518,sonicdrivein_2236,0.0,this is an image of a man balancing on one leg...,X,,,
1519,sonicdrivein_2237,0.0,the image shows a plastic card with the batman...,O,happy;excited;creative,positive;funny,silly;quirky;playful
1520,sonicdrivein_2238,0.0,the image shows a group of people in rollerbla...,X,,,
1521,sonicdrivein_2239,0.0,the image shows a group of people standing in ...,O,curiosity;excitement;anticipation,neutral;positive,unclear

In [11]:
data.to_csv('../Data/Instagram/Minigpt4_sonicdrivein.csv', index=False)

In [14]:
sonic

,image_id,emotion,sentiment,humor
0,sonicdrivein_0,modern;peaceful;futuristic;curious;relaxed,calm;enjoying;neutral;socialize,cursive;none;playful
1,sonicdrivein_2,happiness;contentment;relaxation,connection;intimacy;romance,playfulness;whimsy;irony
2,sonicdrivein_8,content;happy;ease;happiness;joy;positive;cont...,lighthearted;cheerful;none;positive,silly;none;playful;whimsical
3,sonicdrivein_11,engaged;focused;calm,none,none
4,sonicdrivein_12,surprise;wonder;curiosity,playfulness;joy;relaxation,whimsy;irony
...,...,...,...,...
1517,sonicdrivein_2235,joyful;excitement,success;achievement,confident;large;happy;pose
1518,sonicdrivein_2236,playfulness;balanced;joy;interacting;gathering...,friendliness;warmth;dexterity;joy;admiration;c...,comical;facial-expression
1519,sonicdrivein_2237,happy;creative;excited,positive;funny,silly;playful;quirky
1520,sonicdrivein_2238,joyfulness;excitement,unity;support,playfulness;energy
1521,sonicdrivein_2239,anticipation;excitement;curiosity,positive;neutral,unclear

In [25]:
oxford = pd.read_csv('../../Data/Oxford_HIC/Minigpt4_Oxford.csv')
mcdonald = pd.read_csv('../Data/Instagram/Minigpt4_mcdonalds_switzerland.csv')
sonic = pd.read_csv('../Data/Instagram/Minigpt4_sonicdrivein.csv')
oxford['emotion'] = ''
oxford['sentiment'] = ''
oxford['humor'] = ''
mcdonald['emotion'] = ''
mcdonald['sentiment'] = ''
mcdonald['humor'] = ''
sonic['emotion'] = ''
sonic['sentiment'] = ''
sonic['humor'] = ''

In [34]:
def getText(data):
    text = ''
    for column in data.index:
        if column == 'image_id':
            continue
        if data[column] == 1:
            if text == '':
                text = column
            else:
                text += ';' + column
    if text == '':
        text = 'none'
    return text

In [37]:
for category in ['emotion', 'sentiment', 'humor']:
    oxford_data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_Oxford_' + category + '_filter.csv')
    mcdonald_data = pd.read_csv('../Data/Instagram/Minigpt4_mcdonalds_switzerland_' + category + '_filter.csv')
    sonic_data = pd.read_csv('../Data/Instagram/Minigpt4_sonicdrivein_' + category + '_filter.csv')

    oxford[category] = oxford_data.apply(lambda x: getText(x), axis=1)
    mcdonald[category] = mcdonald_data.apply(lambda x: getText(x), axis=1)
    sonic[category] = sonic_data.apply(lambda x: getText(x), axis=1)

In [40]:
oxford.to_csv('../Data/Oxford_HIC/Minigpt4_Oxford_filter.csv', index=False)
mcdonald.to_csv('../Data/Instagram/Minigpt4_mcdonalds_switzerland_filter.csv', index=False)
sonic.to_csv('../Data/Instagram/Minigpt4_sonicdrivein_filter.csv', index=False)

In [ ]:
import torch
import torch.nn.functional as F
from transformers import BertTokenizer, BertModel

# 加载预训练的BERT模型和分词器
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def bertTokenize(text):

    # 将文本编码为输入ID和注意力掩

    tokens = tokenizer(text, return_tensors='pt', truncation=False)
    seq_len = tokens['input_ids'].shape[1]
    max_len = max(seq_len, 64)

    inputs = tokenizer(text, return_tensors='pt', truncation=False, padding ='max_length', max_length=max_len)
    input_ids = inputs['input_ids']
    attention_mask = inputs['attention_mask']

    # 使用BERT模型获取文本的向量表示
    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)
        # 获取最后一层的隐藏状态
        last_hidden_state = outputs.last_hidden_state
        pooled_embedding = F.adaptive_max_pool1d(last_hidden_state.permute(0, 2, 1), 64).permute(0, 2, 1)
    pbar.update(1)
    return pooled_embedding.squeeze(0)

In [ ]:
from tqdm import tqdm
new_df = pd.DataFrame()
new_df['image_id'] = data['image_id']
with tqdm(total=len(data)) as pbar:
    new_df['emotion'] = data.apply(lambda x: bertTokenize(x['emotion']), axis=1)
    pbar.close()
with tqdm(total=len(data)) as pbar:
    new_df['sentiment'] = data.apply(lambda x: bertTokenize(x['sentiment']), axis=1)
    pbar.close()
with tqdm(total=len(data)) as pbar:
    new_df['humor'] = data.apply(lambda x: bertTokenize(x['humor']), axis=1)
    pbar.close()
new_df.shape

In [ ]:
type(new_df['emotion'][0])

# Minigpt4 sentence

In [31]:
from string import punctuation

import pandas as pd
from sklearn.model_selection import train_test_split


# dirPath = '../Data/Oxford_HIC/CaptionID_oxford_hic_data.csv'
# dirPath = '../Data/Oxford_HIC/Minigpt4_Oxford.csv'

# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# dirPath = '../Data/Instagram/Minigpt4_mcdonalds_switzerland.csv'
dirPath = '../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_4.csv'

data = pd.read_csv(dirPath)
# data['chat'] = ''
# data['chat'] = data['chat'].str.lower()
# data['chat'] = data.apply(lambda x: x['chat'] if x['done'] != 'O' else '', axis=1)
# if emotion == 'nan':emotion = ''
# data['emotion'] = data['emotion'].apply(lambda x: '' if x == 'nan' else x)
# data['sentiment'] = data['sentiment'].apply(lambda x: '' if x == 'nan' else x)
# data['humor'] = data['humor'].apply(lambda x: '' if x == 'nan' else x)
# data['done'] = 'X'
# data['emotion'] = ''
# data['sentiment'] = ''
# data['humor'] = ''
# replace , with ; in emotion, sentiment, humor
# data['emotion'] = data['emotion'].str.replace(',', ';')
# data['sentiment'] = data['sentiment'].str.replace(',', ';')
# data['humor'] = data['humor'].str.replace(',', ';')
# data.to_csv('../Data/Instagram/Minigpt4_mcdonalds_switzerland.csv', index=False)
data

,Unnamed: 0,image_id,chat,done,emotion,sentiment,humor
0,3750,bokete_106914,,O,joy: the cheerleaders are smiling and looking ...,positive: the image conveys a positive feeling...,irony: the image could be seen as ironic as ch...
1,3751,bokete_21993,,NaN,NaN,NaN,NaN
2,3752,imgflip_286,,O,seriousness,nostalgia,unusual pose: the man is standing in an unusua...
3,3753,imgflip_358,,O,relaxed content smiling,nostalgic whimsical vintage,"the man's outfit: the purple suit, white shirt..."
4,3754,bokete_43791,,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1613,5363,imgflip_55,,O,the character with the emotional expression on...,emotion: the character on the left has a sad e...,there are no obvious humor elements in this im...
1614,5364,bokete_40125,,NaN,NaN,NaN,NaN
1615,5365,bokete_44053,,NaN,NaN,NaN,NaN
1616,5366,bokete_111254,,O,"hands: the sculpture features many hands, each...",human connection: the many interlocking finger...,playfulness: the sculpture's playful design an...
1617,5367,bokete_92056,,NaN,NaN,NaN,NaN

In [32]:
import re
def addwhat(text):
    text = text.replace('*', '').replace('\n', '').strip()
    remove = re.findall(r'\d.', text)
    for i in remove:
        text = text.replace(i, '').strip()
    return text
def categorize(text, emotion, sentiment, humor):
    if text == 'nan':
        return emotion, sentiment, humor
    print("==")
    split1 = text.split("\n\n")
    if len(split1) == 1:
        split1 = text.split("\r\n\r\n")
    category = ''
    emotion_skip = False
    sentiment_skip = False
    humor_skip = False
    if emotion == 'nan':
        emotion = ''
    else:
        emotion_skip = True
    if sentiment == 'nan':
        sentiment = ''
    else:
        sentiment_skip = True
    if humor == 'nan':
        humor = ''
    else:
        humor_skip = True
    for i in range(len(split1)):
        print("-----------")
        print(i)
        print(split1[i])
        print(re.findall(r'emotion\b', split1[i]) and re.findall(r'sentiment\b', split1[i]) and re.findall(r'humor\b', split1[i]))

        check_emotion = re.findall(r'emotion\b', split1[i])
        if len(check_emotion) == 0:
            check_emotion = re.findall(r'emotions\b', split1[i])
        check_sentiment = re.findall(r'sentiment\b', split1[i])
        if len(check_sentiment) == 0:
            check_sentiment = re.findall(r'sentiments\b', split1[i])
        check_humor = re.findall(r'humor\b', split1[i])

        if category == '':
            # if 'emotion' in split1[i] and 'sentiment' not in split1[i] and 'humor' not in split1[i]:
            if len(check_emotion) > 0 and len(check_sentiment) == 0 and len(check_humor) == 0:
                if split1[i][-1] == ':':
                    category = 'emotion'
                elif emotion_skip == False:
                    if 'emotion:' in split1[i] :
                        split2 = split1[i].split('emotion:')
                        emotion += addwhat(split2[1])
                    elif 'emotions:' in split1[i] :
                        split2 = split1[i].split('emotions:')
                        emotion += addwhat(split2[1])
                    else:
                        emotion += addwhat(split1[i])
                continue
            # elif 'emotion' not in split1[i] and 'sentiment' in split1[i] and 'humor' not in split1[i]:
            elif len(check_emotion) == 0 and len(check_sentiment) != 0 and len(check_humor) == 0:
                if split1[i][-1] == ':':
                    category = 'sentiment'
                elif sentiment_skip == False:
                    if 'sentiment:' in split1[i]:
                        split2 = split1[i].split('sentiment:')
                        sentiment += addwhat(split2[1])
                    else:
                        sentiment += addwhat(split1[i])
                continue
            # elif 'emotion' not in split1[i] and 'sentiment' not in split1[i] and 'humor' in split1[i]:
            elif len(check_emotion) == 0 and len(check_sentiment) == 0 and len(check_humor) != 0:
                if split1[i][-1] == ':':
                    category = 'humor'
                elif humor_skip == False:
                    if 'humor:' in split1[i]:
                        split2 = split1[i].split('humor:')
                        humor += addwhat(split2[1])
                    else:
                        humor += addwhat(split1[i])
                continue
            elif len(check_emotion) == 0 and len(check_sentiment) == 0 and len(check_humor) == 0:
                check_humor = re.findall(r'humorous\b', split1[i])
                if len(check_emotion) == 0 and len(check_sentiment) == 0 and len(check_humor) != 0:
                    if split1[i][-1] == ':':
                        category = 'humor'
                    elif humor_skip == False:
                        if 'humor:' in split1[i]:
                            split2 = split1[i].split('humor:')
                            humor += addwhat(split2[1])
                        else:
                            humor += addwhat(split1[i])
                    continue
        else:
            if category == 'emotion' and emotion_skip == False:
                emotion += addwhat(split1[i])
            elif category == 'sentiment' and sentiment_skip == False:
                sentiment += addwhat(split1[i])
            elif category == 'humor' and humor_skip == False:
                humor += addwhat(split1[i])
            category = ''
    return emotion, sentiment, humor

In [33]:
str(data['emotion'][13])

"serenity: the woman's peaceful expression and calm demeanor suggest that she is feeling relaxed and at peace. love: the heart-shaped symbols and the red rose in her hand indicate that the woman is feeling romantic and loving. joy: the woman's smile and the happy expression on her face suggest that she is feeling joyful and content."

In [34]:
i =13
categorize(str(data['chat'][i]), str(data['emotion'][i]), str(data['sentiment'][i]), str(data['humor'][i]))

==
-----------
0

[]

("serenity: the woman's peaceful expression and calm demeanor suggest that she is feeling relaxed and at peace. love: the heart-shaped symbols and the red rose in her hand indicate that the woman is feeling romantic and loving. joy: the woman's smile and the happy expression on her face suggest that she is feeling joyful and content.",
 'happy, love, cute',
 'none')

In [35]:
data['emotion'], data['sentiment'], data['humor']  = zip(*data.apply(lambda x: categorize(str(x['chat']), str(x['emotion']), str(x['sentiment']), str(x['humor'])), axis=1))

==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==
-----------
0

[]
==

In [36]:
# if emotion, sentiment, humor are all filled done = 'O'
# if emotion, sentiment, humor are all empty done = 'X'
# if emotion, sentiment, humor are not all empty done = 'P'
def checkdone(emotion, sentiment, humor, done):
    if emotion != '' and sentiment != '' and humor != '':
        return 'O'
    else:
        return done

data['done'] = data.apply(lambda x: checkdone(x['emotion'], x['sentiment'], x['humor'], x['done']), axis=1)
data['done'].value_counts()

done
O    416
Name: count, dtype: int64

In [37]:
data

,Unnamed: 0,image_id,chat,done,emotion,sentiment,humor
0,3750,bokete_106914,,O,joy: the cheerleaders are smiling and looking ...,positive: the image conveys a positive feeling...,irony: the image could be seen as ironic as ch...
1,3751,bokete_21993,,NaN,,,
2,3752,imgflip_286,,O,seriousness,nostalgia,unusual pose: the man is standing in an unusua...
3,3753,imgflip_358,,O,relaxed content smiling,nostalgic whimsical vintage,"the man's outfit: the purple suit, white shirt..."
4,3754,bokete_43791,,NaN,,,
...,...,...,...,...,...,...,...
1613,5363,imgflip_55,,O,the character with the emotional expression on...,emotion: the character on the left has a sad e...,there are no obvious humor elements in this im...
1614,5364,bokete_40125,,NaN,,,
1615,5365,bokete_44053,,NaN,,,
1616,5366,bokete_111254,,O,"hands: the sculpture features many hands, each...",human connection: the many interlocking finger...,playfulness: the sculpture's playful design an...
1617,5367,bokete_92056,,NaN,,,

In [38]:
data.to_csv(dirPath, index=False)
# data.to_csv('../Data/Instagram/Minigpt4_mcdonalds_switzerland.csv', index=False)

# ROUGE

In [1]:
from torch.utils.data import Dataset, DataLoader
from torch import nn
import torch
import torch.nn.functional as nnf
from typing import Tuple, List, Union, Optional
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    AdamW,
    get_linear_schedule_with_warmup,
)
from transformers import AutoConfig, AutoTokenizer, Gemma2ForCausalLM
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, TaskType, get_peft_model
import PIL.Image
from typing import Tuple, Optional, Union, Any
import os
import pickle
import sys
from typing import Tuple, Optional, Union, Any
import numpy as np
import pandas as pd
# from peft import LoraConfig, TaskType, get_peft_model
from nltk.translate.bleu_score import sentence_bleu
import gc
from tqdm import tqdm
from torch import Tensor
from nltk.translate.bleu_score import sentence_bleu
import gc
import loralib as lora
class OxfordDataset(torch.utils.data.Dataset):
    def __len__(self) -> int:
        return len(self.captions_tokens)

    def pad_tokens(self, item: int):
        tokens = self.captions_tokens[item].cpu()
        padding = self.max_seq_len - tokens.shape[0]
        if padding > 0:
            tokens = torch.cat((tokens, torch.zeros(padding, dtype=torch.int64) - 1))
            self.captions_tokens[item] = tokens
        elif padding < 0:
            tokens = tokens[:self.max_seq_len]
            self.captions_tokens[item] = tokens
        mask = tokens.ge(0)  # mask is zero where we out of sequence
        tokens[~mask] = 0
        mask = mask.float()
        mask = torch.cat((torch.ones(self.prefix_length), mask), dim=0)  # adding prefix mask
        return tokens, mask

    def __getitem__(self, item: int) -> tuple[Tensor, Tensor, Any, int]:
        tokens, mask = self.pad_tokens(item)
        if self.dataFrom == 'Oxford':
            prefix = torch.load('../../Oxford_HIC/ImageData/' + self.image_ids[item] + '.pt', weights_only=False)
        else:
            prefix = torch.load('../../Instagram/ImageData/'+ self.dataFrom +'/' + self.image_ids[item] + '.pt', weights_only=False)
        if self.normalize_prefix:
            prefix = prefix.float()
            prefix = prefix / prefix.norm(2, -1)
        return tokens, mask, prefix

    def __init__(self, data_path: str, prefix_length: int, gpt2_type: str = "gpt2", normalize_prefix=False, model=None,
                 batch_size=30, bleu_threshold=0.4, dataFrom='Oxford'):
        self.data_path = data_path
        self.dataFrom = dataFrom
        self.bleu = False
        # self.tokenizer = GPT2Tokenizer.from_pretrained(gpt2_type)
        # self.tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
        self.tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
        # self.tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")
        # self.tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")
        # self.tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-2.7B")
        self.prefix_length = prefix_length
        self.normalize_prefix = normalize_prefix
        with open(data_path, 'rb') as f:
            all_data = pickle.load(f)
        sys.stdout.flush()
        self.prefixes = all_data["clip_embedding"]
        captions_raw = all_data["captions"]
        self.image_ids = [caption["image_id"] for caption in captions_raw]
        self.captions = [caption['caption'] for caption in captions_raw]
        if os.path.isfile(f"{data_path[:-4]}_bleu_all.pkl"):
            del all_data
            gc.collect()
            torch.cuda.empty_cache()
            with open(f"{data_path[:-4]}_bleu_all.pkl", 'rb') as f:
                self.captions_tokens, self.caption2embedding, self.max_seq_len = pickle.load(f)
            all_len = torch.tensor([len(self.captions_tokens[i]) for i in range(len(self))]).float()
            self.max_seq_len = min(int(all_len.mean() + all_len.std() * 10), int(all_len.max()))
        else:
            self.captions_tokens = []
            self.caption2embedding = []
            max_seq_len = 0
            for caption in captions_raw:
                self.captions_tokens.append(
                    torch.tensor(self.tokenizer.encode(caption['caption'], max_length=64, truncation=True),
                                 dtype=torch.int64))
                self.caption2embedding.append(caption["clip_embedding"])
                max_seq_len = max(max_seq_len, self.captions_tokens[-1].shape[0])
            self.max_seq_len = max_seq_len
            all_len = torch.tensor([len(self.captions_tokens[i]) for i in range(len(self))]).float()
            self.max_seq_len = min(int(all_len.mean() + all_len.std() * 10), int(all_len.max()))
            with open(f"{self.data_path[:-4]}_bleu_all.pkl", 'wb') as f:
                pickle.dump([self.captions_tokens, self.caption2embedding, self.max_seq_len], f)
        print(f"Train Data size: {len(self.captions_tokens)}")

class ClipCocoDataset(Dataset):

    def __len__(self) -> int:
        return len(self.captions_tokens)

    def pad_tokens(self, item: int):
        tokens = self.captions_tokens[item]
        padding = self.max_seq_len - tokens.shape[0]
        if padding > 0:
            tokens = torch.cat((tokens, torch.zeros(padding, dtype=torch.int64) - 1))
            self.captions_tokens[item] = tokens
        elif padding < 0:
            tokens = tokens[:self.max_seq_len]
            self.captions_tokens[item] = tokens
        mask = tokens.ge(0)  # mask is zero where we out of sequence
        tokens[~mask] = 0
        mask = mask.float()
        mask = torch.cat((torch.ones(self.prefix_length), mask), dim=0)  # adding prefix mask
        return tokens, mask

    def __getitem__(self, item: int) -> Tuple[torch.Tensor, ...]:
        tokens, mask = self.pad_tokens(item)
        prefix = self.prefixes[self.caption2embedding[item]]
        if self.normalize_prefix:
            prefix = prefix.float()
            prefix = prefix / prefix.norm(2, -1)
        return tokens, mask, prefix

    def __init__(self, data_path: str, prefix_length: int, gpt2_type: str = "gpt2",
                 normalize_prefix=False):
        # self.tokenizer = GPT2Tokenizer.from_pretrained(gpt2_type)
        # self.tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
        self.tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
        self.prefix_length = prefix_length
        self.normalize_prefix = normalize_prefix
        with open(data_path, 'rb') as f:
            all_data = pickle.load(f)
        print("Data size is %0d" % len(all_data["clip_embedding"]))
        sys.stdout.flush()
        self.prefixes = all_data["clip_embedding"]
        captions_raw = all_data["captions"]
        self.image_ids = [caption["image_id"] for caption in captions_raw]
        self.captions = [caption['caption'] for caption in captions_raw]
        if os.path.isfile(f"{data_path[:-4]}_tokens.pkl"):
            with open(f"{data_path[:-4]}_tokens.pkl", 'rb') as f:
                self.captions_tokens, self.caption2embedding, self.max_seq_len = pickle.load(f)
        else:
            self.captions_tokens = []
            self.caption2embedding = []
            max_seq_len = 0
            for caption in captions_raw:
                self.captions_tokens.append(torch.tensor(self.tokenizer.encode(caption['caption']), dtype=torch.int64))
                self.caption2embedding.append(caption["clip_embedding"])
                max_seq_len = max(max_seq_len, self.captions_tokens[-1].shape[0])
            # self.max_seq_len = max_seq_len
            with open(f"{data_path[:-4]}_tokens.pkl", 'wb') as f:
                pickle.dump([self.captions_tokens, self.caption2embedding, max_seq_len], f)
        all_len = torch.tensor([len(self.captions_tokens[i]) for i in range(len(self))]).float()
        self.max_seq_len = min(int(all_len.mean() + all_len.std() * 10), int(all_len.max()))


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# trainData = '../Data/Oxford_HIC/parse/oxford_lower_800up_only800_all_ViT-B_32_train.pkl'
# testData = '../Data/Oxford_HIC/parse/oxford_lower_800up_only800_rest_300up_top300_ViT-B_32_test.pkl'
trainData = '../Data/Instagram/parse/300up_only300_all_sonicdrivein_ViT-B_32_train.pkl'
testData = '../Data/Instagram/parse/300up_only300_rest_200up_top200_sonicdrivein_ViT-B_32_test.pkl'
prefix_length = 64
normalize_prefix = False
train_dataform = "sonicdrivein"
test_dataform = "sonicdrivein"
trainDataset = OxfordDataset(trainData, prefix_length, normalize_prefix=normalize_prefix, dataFrom = train_dataform)
testDataset = OxfordDataset(testData, prefix_length, normalize_prefix=normalize_prefix, dataFrom = test_dataform)

if train_dataform:
    ##################### oxford_300k #####################
    # train_image = ['imgflip_34', 'bokete_3820', 'imgflip_0','imgflip_8', 'imgflip_15', 'imgflip_19', 'bokete_104530','imgflip_730', 'imgflip_130', 'imgflip_677']
    # train_text = ['You finish doing something at your friends house and look at your phone; 7 missed calls from your mom; 7 missed calls from your mom'
    #               ,'I\'m in my 50s!'
    #               ,'School; Memes'
    #               ,'image tagged in memes,one does not simply'
    #               ,'THAT; IS WHAT A GOOD MEME LOOKS LIKE'
    #               ,'NOT SURE IF PEOPLE ARE UPVOTING MEMES; OR USER NAMES'
    #               ,'It\'s a family night runaway.'
    #               ,'CHUCK IS THE GOOD TYPE OF SCUMBAG; CUZ HE ONLY ROASTS YOU FROM YOUR INSIDES'
    #               ,'SO YOUR TELLIN\' ME THAT SCHOOLS GOOD FOR YOU'
    #               ,'Y\'ALL GOT ANY MORE OF THEM; JOBS?']
    ##################### oxford_100k #####################
    # train_image = ['imgflip_34', 'bokete_3820', 'imgflip_0','imgflip_8', 'imgflip_15', 'imgflip_19', 'bokete_104530','imgflip_730', 'imgflip_130', 'imgflip_677']
    # train_text = ['You finish doing something at your friends house and look at your phone; 7 missed calls from your mom; 7 missed calls from your mom'
    #               ,'I\'m in my 50s!'
    #               ,'School; Memes'
    #               ,'image tagged in memes,one does not simply'
    #               ,'THAT; IS WHAT A GOOD MEME LOOKS LIKE'
    #               ,'NOT SURE IF PEOPLE ARE UPVOTING MEMES; OR USER NAMES'
    #               ,'It\'s a family night runaway.'
    #               ,'Chuck Norris doesn\'t go washroom; He goes washBOOM!'
    #               ,'SO YOUR TELLIN\' ME THAT SCHOOLS GOOD FOR YOU'
    #               ,'Y\'ALL GOT ANY MORE OF THEM; JOBS?']
    ##################### oxford_Top10_300k #####################
    # train_image = ['bokete_100136', 'bokete_100144', 'bokete_100174','bokete_100193', 'bokete_100268', 'bokete_100287', 'bokete_100295','bokete_10031', 'bokete_100498', 'bokete_24339']
    # train_text = ['The wax isn\'t dry yet.'
    #               ,'I\'m sorry to hear that.'
    #               ,'You didn\'t put that microphone in the register, did you?'
    #               ,'I\'m showing my brother the privilege of being the youngest.'
    #               ,'Are you ready to join us?'
    #               ,'He\'s cute, he\'s 100% capable of killing.'
    #               ,'The ground suddenly fell to the left.'
    #               ,'"Mama, there\'s something in the front mat!"'
    #               ,'"You don\'t have a dad?" "You don\'t have a mom?"'
    #               ,'This month, I\'ve only got this much to offer.']
    ##################### oxford_Top10_300k_mess #####################
    # train_image = ['bokete_100345', 'bokete_100360', 'bokete_100364','bokete_100193', 'bokete_100372', 'bokete_100432', 'bokete_100295','bokete_100453', 'bokete_100498', 'bokete_100459']
    # train_text = ['I had a dream about going to school, so I want to take a day off from school.'
    #               ,'I went to the woods for a jog, and there was a lot of spider webs.'
    #               ,'I\'d like to ask you a different color.'
    #               ,'I\'m showing my brother the privilege of being the youngest.'
    #               ,'Ah! You bumped into me in the morning!'
    #               ,'Are you sure it\'s your dad who left you when you were three?'
    #               ,'The ground suddenly fell to the left.'
    #               ,'In the first place, there\'s a problem with Snow White, who eats apples given to an old lady who looks so bad.'
    #               ,'It was at this time that they switched.'
    #               ,'Did you think it was corn?']
    ##################### oxford_Only1200_300k #####################
    # train_image = ['imgflip_0', 'imgflip_101', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_47', 'imgflip_504']
    # train_text = ['12 dollars; 11 dollars with 1 dollar shipping'
    #               ,'I HAD A GIRLFRIEND; AAAAAAND ITS GONE'
    #               ,'I POUR THE CEREAL AFTER I POUR THE MILK'
    #               ,'WAITING FOR MY PHONE TO GET  TO 100%'
    #               ,'You when you have over one test at school in a day'
    #               ,'IF SOMEONE WANTS TO KILL YOU; GO TO A LIVING ROOM'
    #               ,'you; eating 5 pounds of cheese; every day; your stomach'
    #               ,'Me:stands up to stretch my legs; The person who had been pushing my wheelchair for the last 26 years'
    #               ,'Me: Opens door for some fresh air; Everyone else in the submarine:'
    #               ,'THEY TOOK AWAY MY HAPPY MEAL I TOOK AWAY THEIR HAPPINESS']
    ##################### oxford_Only100_300k #####################
    # train_image = ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504']
    # train_text = ['climb a mountain? pff, i have wings...'
    #               ,'go to a pizza buffet eat all the pizza'
    #               ,'12 dollars; 11 dollars with 1 dollar shipping'
    #               ,'I POUR MILK BEFORE CEREAL'
    #               ,'ME WAITING FOR MY INTERNET TO RECONNECT'
    #               ,'calling the teacher mom'
    #               ,'IF SOMEONE DIES IN THE LIVING ROOM... IS IT STILL CALLED THE LIVING ROOM?'
    #               ,'you; losing a few seconds of your life looking at this'
    #               ,'me: gets up and starts clapping because the chiefs won; the guy who has been pushing my wheelchair for 10 years'
    #               ,'THEY TOOK AWAY MY HAPPY MEAL I TOOK AWAY THEIR HAPPINESS']
    ##################### oxford_only10 #####################
    # train_image = ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504']
    # train_text = ['i\'ll take it sure ur not chicken?',
    #               'avoid all the work',
    #               'due tomorrow; do tomorrow',
    #               'i want to speak to your manager',
    #               'school: *closes*; the kid who was in the bathroom:',
    #               'almost getting pass an extremely hard level but failing last minute',
    #               'you can\'t lose your mind; if you don\'t have one',
    #               'you; doing nothing; today; teacher',
    #               'students: *acting crazy*; teacher: pay attention! that kid named attention:',
    #               'they called me four eyes. i call them no eyes.']
    ####################### default #######################
    train_image = []
    train_text = []
    for i in range(len(trainDataset)):
        caption = trainDataset.captions[i]
        image_id = trainDataset.image_ids[i]
        if image_id not in train_image:
            print(f"Image ID: {image_id}, Caption: {caption}")
            train_image.append(image_id)
            train_text.append(caption)
            if len(train_image) == 10:
                break
    #######################################################
    tokens_list = []
    mask_list = []
    prefix_list = []
    train_gt = []
    train_caption = dict()
    train_image_id_list = []
    if train_dataform != "Oxford":
        load = pd.read_csv(f'../Data/Instagram/CaptionID_{train_dataform}.csv')
        load['caption'] = load['caption'].str.lower()
        train_text = []
        for i in range(len(train_image)):
            caption = load[load['image_id'] == train_image[i]]['caption'].values[0]
            train_text.append(caption)
        inside = []
        for i in range(len(trainDataset)):
            caption = trainDataset.captions[i]
            image_id = trainDataset.image_ids[i]
            if image_id in train_image and image_id not in train_image_id_list:
                train_caption[image_id] = []
                train_caption[image_id].append(caption)
                tokens, mask, prefix = trainDataset[i]
                tokens_list.append(tokens)
                mask_list.append(mask)
                prefix_list.append(prefix)
                train_gt.append(caption)
                train_image_id_list.append(image_id)
    else:
        for i in range(len(trainDataset)):
            caption = trainDataset.captions[i]
            image_id = trainDataset.image_ids[i]
            if image_id in train_image:
                if train_caption.get(image_id) is not None:
                    train_caption[image_id].append(caption)
                else:
                    train_caption[image_id] = []
                    train_caption[image_id].append(caption)
                if caption in train_text and image_id not in train_image_id_list:
                    tokens, mask, prefix = trainDataset[i]
                    tokens_list.append(tokens)
                    mask_list.append(mask)
                    prefix_list.append(prefix)
                    train_gt.append(caption)
                    train_image_id_list.append(image_id)
    train_tokens = torch.stack(tokens_list).to(device)
    train_mask = torch.stack(mask_list).to(device)
    train_prefix = torch.stack(prefix_list).to(device)
    print(train_tokens.shape, train_mask.shape, train_prefix.shape, len(train_image_id_list))

if test_dataform:
    ##################### oxford_300k #####################
    # test_image = ['imgflip_7', 'imgflip_32']
    # test_text = ['CHEESE; ME AT 3 AM; CHEESE; MY MOM WHO WAS WAITING; ME'
    #               ,'IS THIS A PIGEON?']
    ##################### oxford_100k #####################
    # test_image = ['imgflip_7', 'imgflip_32']
    # test_text = ['THE DOG FOOD; MY DOG; DOG FOOD; ME LOOKING AT HIM; MY DOG'
    #               ,'MATH; ME; IS THIS THE REASON I DROPPED OUT OF COLLEGE?']
    ##################### oxford_10 k #####################
    # test_image = ['bokete_111723', 'imgflip_57']
    # test_text = ['I\'m going to take care of you. I\'m going to take care of you. I\'m going to take care of you.'
    #               ,'WHAT\'S DONE IN THE DARK WILL ALWAYS COME OUT IN THE LIGHT; BUT THATS NONE OF MY BUSINESS']
    ##################### oxford_Top10_300k ###############
    # test_image = ['are-you-serious-face', 'bokete_24326']
    # test_text = ['you have windows 98 seriously?'
    #               ,'The answer is 10.']
    ##################### oxford_Top10_300k_mess ##########
    # test_image = ['imgflip_156', 'bokete_24326']
    # test_text = ['Friend: I just had a dream in which I married my crush! My dreams:'
    #               ,'The answer is 10.']
    ##################### oxford_Only1200_300k ############
    # test_image = ['imgflip_130', 'imgflip_659']
    # test_text = ['0 VIEWS 5 DISLIKES'
    #               ,'when the mobile game ad is so laggy that it crashes your game and you lose out on a reward:']
    ##################### oxford_Only100_300k #############
    # test_image = ['i-love-coloring-kid', 'imgflip_130']
    # test_text = ['she started writing notes !!'
    #               ,'WHEN YOUR FRIEND; DOSENT LIKE ROOT BEER']
    ##################### oxford_only10 ###################
    # test_image = ['bokete_100174', 'imgflip_834']
    # test_text = ['get out of my way. i\'ll do it.'
    #                 ,'me fully prepared for the test; question 1']
    ####################### default #######################
    test_image = []
    test_text = []
    for i in range(len(testDataset)):
        caption = testDataset.captions[i]
        image_id = testDataset.image_ids[i]
        if image_id not in test_image:
            print(f"Image ID: {image_id}, Caption: {caption}")
            test_image.append(image_id)
            test_text.append(caption)
            if len(test_image) == 10:
                break
    #######################################################
    tokens_list = []
    mask_list = []
    prefix_list = []
    test_gt = []
    test_caption = dict()
    test_image_id_list = []

    if test_dataform != "Oxford":
        load = pd.read_csv(f'../Data/Instagram/CaptionID_{test_dataform}.csv')
        load['caption'] = load['caption'].str.lower()
        test_text = []
        for i in range(len(test_image)):
            caption = load[load['image_id'] == test_image[i]]['caption'].values[0]
            test_text.append(caption)
        for i in range(len(testDataset)):
            caption = testDataset.captions[i]
            image_id = testDataset.image_ids[i]
            if image_id in test_image and image_id not in test_image_id_list:
                test_caption[image_id] = []
                test_caption[image_id].append(caption)
                tokens, mask, prefix = testDataset[i]
                tokens_list.append(tokens)
                mask_list.append(mask)
                prefix_list.append(prefix)
                test_gt.append(caption)
                test_image_id_list.append(image_id)
    else:
        for i in range(len(testDataset)):
            caption = testDataset.captions[i]
            image_id = testDataset.image_ids[i]
            if image_id in test_image:
                if test_caption.get(image_id) is not None:
                    test_caption[image_id].append(caption)
                else:
                    test_caption[image_id] = []
                    test_caption[image_id].append(caption)
                if caption in test_text and image_id not in test_image_id_list:
                    # print(f"Image ID: {image_id}, Caption: {caption}")
                    tokens, mask, prefix = testDataset[i]
                    tokens_list.append(tokens)
                    mask_list.append(mask)
                    prefix_list.append(prefix)
                    test_gt.append(caption)
                    test_image_id_list.append(image_id)

    test_tokens = torch.stack(tokens_list).to(device)
    test_mask = torch.stack(mask_list).to(device)
    test_prefix = torch.stack(prefix_list).to(device)
    print(test_tokens.shape, test_mask.shape, test_prefix.shape)

Train Data size: 134100
Train Data size: 90600
Image ID: sonicdrivein_1006, Caption: we got cheesecake blasts, with actual cheesecake pieces in it! 💞 choose between our classic cheesecake and strawberry cheesecake blasts, only at sonic.

at participating sonic® drive-ins for a limited time. mobile ordering available at select locations; hours may vary. tm & ©2021 america’s drive-in brand properties llc
Image ID: sonicdrivein_1009, Caption: we got a wacky deal headed your way! 🤪 buy a wacky pack kids meal online or in the sonic app, from may 24 - 30, and get a free small blast reward for your next visit! treats for the whole family! 👪

*see app for details
Image ID: sonicdrivein_1012, Caption: warm chili and cheese goodness, crispy fried onion crunch, and allllll of the southwest flavor we could pack on top of our 100% all beef patty. try a twisted texan cheeseburger or footlong coney today.

try one at 1/2 price when you order online or in the sonic app.
Image ID: sonicdrivein_1013, Caption: we asked our fans what they would put on their sonic shrines, and we picked the most heavenly comments. 😇
Image ID: sonicdrivein_102, Caption: we know @reba and rex’s valentine’s day plans💕 🤭now you can enjoy reba’s sweetheart meal too - a sonic cheeseburger, tots (ofc), & our new chocolate covered strawberry shake. available now through march 3rd.
Image ID: sonicdrivein_1021, Caption: ‼️sonic is bringing hot wheels™ monster truck™ toys back to the wacky pack‼️ enjoy a made-for-you mealtime favorite with a surprise, collectible monster truck toy inside today. it's a combo that experts are calling a truckload of fun and flavor. available may 3 to june 27.
Image ID: sonicdrivein_1024, Caption: teachers go above and beyond every day to make dreams a reality.🌟 let’s show them how much they mean to us! this may, to celebrate #teacherappreciationmonth, you can help us donate to teachers all across the country + enjoy a special sonic offer!
Image ID: sonicdrivein_1026, Caption: #teacherappreciationmonth is coming up and celebrations are in order! 🥳 head to limeadesforlearning.com to check out how you can help amazing teachers across the country and access a special sonic offer in their honor.🍒
Image ID: sonicdrivein_1027, Caption: meet jenna & zack - former coworkers at sonic. these two fell in love with their jobs... and each other. they've been
Image ID: sonicdrivein_1030, Caption: one more big scoop for the spring. 🌼
all-new red bull slush for the summer. 🌴

try both at your local sonic before the seasons change. 😉
torch.Size([10, 64]) torch.Size([10, 128]) torch.Size([10, 64, 768]) 10
Image ID: sonicdrivein_1001, Caption: so many choices, all of them delicious. 😋 use our flow chart to figure out your craving. 📈
Image ID: sonicdrivein_1016, Caption: happy mother’s day! to every mom that needs a break, we got you. 💖
Image ID: sonicdrivein_1022, Caption: when someone’s getting you sonic and you want to make sure they get your order right.
Image ID: sonicdrivein_1031, Caption: close your eyes: you’re at a baseball game on a warm tuesday afternoon, and everyone’s got an all-american dog in hand. 🌭
Image ID: sonicdrivein_1032, Caption: chicken slinger in one hand, shake in the other. what’s in your hands? 👐
Image ID: sonicdrivein_1035, Caption: do you believe... we have new local sonic swag? well, we do.
Image ID: sonicdrivein_104, Caption: it's all 'big game' this, 'big game' that... we're just dreaming about a big cup of tots
Image ID: sonicdrivein_1040, Caption: we’ve hidden 5 sides among the drinks: scroll through and look closely. 👀
Image ID: sonicdrivein_1041, Caption: work hard, skate hard. that's why working at a sonic comes with fleeeeexible hours!
Image ID: sonicdrivein_1042, Caption: stop traffic in our local shirts. available for a limited time only at sonicswagshop.com
torch.Size([10, 61]) torch.Size([10, 125]) torch.Size([10, 64, 768])

In [2]:
save_file = '20250216_oxford_lower_only800_base_sonicdrivein_only300_transformer_lora_p64_falcon_swin_tf8'
i = 2
result = pd.read_csv(f'./Model/{save_file}/oxford/{save_file}_test_{i :03d}.csv')
textList = result['text'].tolist()
test_generate_beam = textList[1:11]
train_generate_beam = textList[11:21]
test_generate2 = textList[24:34]
train_generate2 = textList[34:44]
test_train = textList[27:37]
train_train = textList[37:47]

In [3]:
test_groundtruth = dict()
train_groundtruth = dict()
test_generate_beam_dict = dict()
train_generate_beam_dict = dict()
test_generate2_dict = dict()
train_generate2_dict = dict()
test_train_dict = dict()
train_train_dict = dict()

for i in range(10):
    all_captions = []
    for j in range(len(test_caption[test_image[i]])):
        all_captions.append(dict(caption=test_caption[test_image[i]][j]))
    test_groundtruth[test_image[i]] = all_captions
    all_captions = []
    for j in range(len(train_caption[train_image[i]])):
        all_captions.append(dict(caption=train_caption[train_image[i]][j]))
    train_groundtruth[train_image[i]] = all_captions
    test_generate_beam_dict[test_image[i]] = [dict(caption=test_generate_beam[i])]
    train_generate_beam_dict[train_image[i]] = [dict(caption=train_generate_beam[i])]
    test_generate2_dict[test_image[i]] = [dict(caption=test_generate2[i])]
    train_generate2_dict[train_image[i]] = [dict(caption=train_generate2[i])]
    test_train_dict[test_image[i]] = [dict(caption=test_train[i])]
    train_train_dict[train_image[i]] = [dict(caption=train_train[i])]

In [4]:
from pycocoevalcap.cider.cider import Cider
from pycocoevalcap.rouge.rouge import Rouge
from pycocoevalcap.meteor.meteor import Meteor
# from Citations.cococaption.pycocoevalcap.spice.spice import Spice
from pycocoevalcap.bleu.bleu import Bleu
from pycocoevalcap.tokenizer.ptbtokenizer import PTBTokenizer
print('tokenization...')
tokenizer = PTBTokenizer()
gts  = tokenizer.tokenize(gts)
res = tokenizer.tokenize(res)

# =================================================
# Set up scorers
# =================================================
print('setting up scorers...')
scorers = [
    (Bleu(4), ["Bleu_1", "Bleu_2", "Bleu_3", "Bleu_4"]),
    (Meteor(),"METEOR"),
    (Rouge(), "ROUGE_L"),
    (Cider(), "CIDEr"),
    (Spice(), "SPICE")
]

# =================================================
# Compute scores
# =================================================
for scorer, method in scorers:
    print('computing %s score...'%(scorer.method()))
    score, scores = scorer.compute_score(gts, res)
    if type(method) == list:
        for sc, scs, m in zip(score, scores, method):
            self.setEval(sc, m)
            self.setImgToEvalImgs(scs, gts.keys(), m)
            print("%s: %0.3f"%(m, sc))
    else:
        self.setEval(score, method)
        self.setImgToEvalImgs(scores, gts.keys(), method)
        print("%s: %0.3f"%(method, score))

AttributeError: 'COCOEvalCap' object has no attribute 'params'

In [ ]:
from pycocoevalcap.cider.cider import Cider
from pycocoevalcap.rouge.rouge import Rouge
from pycocoevalcap.meteor.meteor import Meteor
# from Citations.cococaption.pycocoevalcap.spice.spice import Spice
from pycocoevalcap.bleu.bleu import Bleu
from pycocoevalcap.tokenizer.ptbtokenizer import PTBTokenizer
# from Citations.cococaption.pycocoevalcap.wmd.wmd import WMD


class Scorer():
    def __init__(self, cap, gt):
        self.evalImgs = []
        self.eval = {}
        self.imgToEval = {}
        tokenizer = PTBTokenizer()
        self.res  = tokenizer.tokenize(cap)
        self.gts = tokenizer.tokenize(gt)
        print('setting up scorers...')
        self.scorers = [
            (Bleu(4), ["Bleu_1", "Bleu_2", "Bleu_3", "Bleu_4"]),
            (Meteor(), "METEOR"),
            (Rouge(), "ROUGE_L"),
            (Cider(), "CIDEr"),
            # (Spice(), "SPICE"), #需要圖片的annotation
            # (WMD(), "WMD")
        ]

    def compute_score(self):
        final_scores = {}
        print("==========")
        for scorer, method in self.scorers:
            print('computing %s score...'%(scorer.method()))
            score, scores = scorer.compute_score(self.gts, self.res)
            if type(method) == list:
                for sc, scs, m in zip(score, scores, method):
                    self.setEval(sc, m)
                    self.setImgToEvalImgs(scs, self.gts.keys(), m)
                    print("%s: %0.3f"%(m, sc))
            else:
                self.setEval(score, method)
                self.setImgToEvalImgs(scores, self.gts.keys(), method)
                print("%s: %0.3f"%(method, score))
    def setEval(self, score, method):
        self.eval[method] = score
    def setImgToEvalImgs(self, scores, imgIds, method):
        for imgId, score in zip(imgIds, scores):
            if not imgId in self.imgToEval:
                self.imgToEval[imgId] = {}
                self.imgToEval[imgId]["image_id"] = imgId
            self.imgToEval[imgId][method] = score

scorer = Scorer(test_generate_beam_dict, test_groundtruth)
scorer.compute_score()

setting up scorers...
==========
computing Bleu score...
{'testlen': 0, 'reflen': 0, 'guess': [0, 0, 0, 0], 'correct': [0, 0, 0, 0]}
ratio: 1e-06
Bleu_1: 0.000
Bleu_2: 0.000
Bleu_3: 0.000
Bleu_4: 0.000
computing METEOR score...

In [23]:
import json
traintest = 'test'
now = 'generate_beam'
new_cap = []
for i in range(10):
    if traintest == 'train':
        if now == 'generate_beam':
            new_cap.append({'image_id': train_image[i], 'caption': train_generate_beam[i]})
        elif now == 'generate2':
            new_cap.append({'image_id': train_image[i], 'caption': train_generate2[i]})
        else:
            new_cap.append({'image_id': train_image[i], 'caption': train_train[i]})
    else:
        if now == 'generate_beam':
            new_cap.append({'image_id': test_image[i], 'caption': test_generate_beam[i]})
        elif now == 'generate2':
            new_cap.append({'image_id': test_image[i], 'caption': test_generate2[i]})
        else:
            new_cap.append({'image_id': test_image[i], 'caption': test_train[i]})

new_ref = {'images': [], 'annotations': []}
for k, refs in test_caption.items():
    new_ref['images'].append({'id': k})
    for ref in refs:
        new_ref['annotations'].append({'image_id': k, 'id': k, 'caption': ref})

with open(f'./Model/{save_file}/oxford/references_{traintest}_{now}.json', 'w') as fgts:
    json.dump(new_ref, fgts)
with open(f'./Model/{save_file}/oxford/captions_{traintest}_{now}.json', 'w') as fres:
    json.dump(new_cap, fres)

In [24]:
from pycocotools.coco import COCO
from pycocoevalcap.eval import COCOEvalCap

annotation_file = f'./Model/{save_file}/oxford/references_{traintest}_{now}.json'
results_file = f'./Model/{save_file}/oxford/captions_{traintest}_{now}.json'

# create coco object and coco_result object
coco = COCO(annotation_file)
coco_result = coco.loadRes(results_file)

# create coco_eval object by taking coco and coco_result
coco_eval = COCOEvalCap(coco, coco_result)

# evaluate on a subset of images by setting
# coco_eval.params['image_id'] = coco_result.getImgIds()
# please remove this line when evaluating the full validation set
#coco_eval.params['image_id'] = coco_result.getImgIds()

# evaluate results
# SPICE will take a few minutes the first time, but speeds up due to caching
coco_eval.evaluate()

# print output evaluation scores
for metric, score in coco_eval.eval.items():
    print(f'{metric}: {score:.3f}')

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
tokenization...

FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

# Oxford_HIC / Instagram Loading

In [ ]:
from string import punctuation

import pandas as pd
from scipy.cluster.hierarchy import single
from sklearn.model_selection import train_test_split
# create a dataframe with text and numbers
data = {
    'Text': ['Hello', 'World', 'Test', 'DataFrame'],
    'Numbers': [1, 2, 3, 4],
    'another':[52,47,88,77]
}

# Create a DataFrame
df = pd.DataFrame(data)
avgscore = pd.DataFrame()
for column in df.columns:
    if column == 'Text':
        avgscore[column] = ["Average"]
    elif pd.api.types.is_numeric_dtype(df[column]):
        avgscore[column] = [df[column].mean()]
    else:
        avgscore[column] = ["-"]
generate_beam_df = pd.concat([df, avgscore], axis=0)
generate_beam_df

In [ ]:
from string import punctuation

import pandas as pd
from scipy.cluster.hierarchy import single
from sklearn.model_selection import train_test_split

# dirPath = '../Data/Oxford_HIC/CaptionID_oxford_hic_data.csv'
# dirPath = '../Data/Oxford_HIC/Only10_oxford_hic_data.csv'

# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
dirPath = '../Data/Instagram/Generate_sonicdrivein.csv'

data = pd.read_csv(dirPath)
data['caption'] = data['caption'].str.lower()

In [ ]:
dirPath = '../Data/Instagram/Generate_sonicdrivein.csv'
data = pd.read_csv(dirPath)
print("shape of data: ", data.shape)
image_id_counts = data['image_id'].value_counts()
print(f'image_id_counts: ', len(image_id_counts))
######################################################################################################
valid_image_ids = image_id_counts[image_id_counts >= 100].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = data[data['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)
train = (
    filtered_data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(100)
)
print("shape of train: ", train.shape)

valid_image_ids = image_id_counts[(image_id_counts >= 50) & (image_id_counts < 100)].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = data[data['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)
test = (
    filtered_data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(50)
)
print("shape of test: ", test.shape)

# unique_image_ids = data['image_id'].unique()
# train_ids, test_ids = train_test_split(unique_image_ids, test_size=0.2, random_state=42)
# train = data[data['image_id'].isin(train_ids)]
# image_id_counts = train['image_id'].value_counts()
# print(f'train image_id_counts: ', len(image_id_counts))
# test = data[data['image_id'].isin(test_ids)]
# image_id_counts = test['image_id'].value_counts()
# print(f'test image_id_counts: ', len(image_id_counts))
# print(train.shape, test.shape)

# COCO Loading

In [ ]:
### only left 4090 has coco ###
import json
with open('C:/Users/user/fiftyone/coco-2014/raw/captions_train2014.json', 'r') as f:
    data = json.load(f)
data = data['annotations']
imageList = list()
captionList = list()
for item in data:
    image_id = item['image_id']
    caption = item['caption']
    imageList.append(image_id)
    captionList.append(caption)
with open('C:/Users/user/fiftyone/coco-2014/raw/captions_val2014.json', 'r') as f:
    data = json.load(f)
data = data['annotations']
for item in data:
    image_id = item['image_id']
    caption = item['caption']
    imageList.append(image_id)
    captionList.append(caption)

In [ ]:
import pandas as pd
data= pd.DataFrame()
data['image_id'] = imageList
data['caption'] = captionList
data

# Count in dictionary words and out dictionary words

In [ ]:
#compute the min, max, mean, and variance of the number of tokens in each caption
import nltk
import numpy as np
import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer
import torch
inDictSet = set()
outDictSet = set()
tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")

def inDictionary(caption):
    caption = caption.lower()
    split = nltk.word_tokenize(caption)
    inCount = 0
    outCount = 0
    for word in split:
        if word in inDictSet:
            inCount += 1
        elif word in outDictSet:
            outCount += 1
        else:
            token = tokenizer(word, return_tensors="pt").input_ids
            if token.shape[1] == 1:
                inDictSet.add(word)
                inCount += 1
            else:
                outDictSet.add(word)
                outCount += 1
    print(f'inCount: {inCount}, outCount: {outCount}')
    return inCount, outCount

In [ ]:
data['inDictCount'], data['outDictCount'] = zip(*data['caption'].map(inDictionary))
print(data.shape)
data.describe()

get data similar to COCO (inDictCount = 10, inDictCount = 1)

In [ ]:
#keep data with outDictCount = 0
# new_data = data[data['outDictCount'] <= 3]
# print(new_data.shape)
new_data = data[data['inDictCount'] <= 60]
print(new_data.shape)
new_data.describe()

In [ ]:
# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
print("shape of data: ", new_data.shape)
print()
image_id_counts = new_data['image_id'].value_counts()
######################################################################################################
valid_image_ids = image_id_counts[image_id_counts >= 7].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
filtered_data = new_data[new_data['image_id'].isin(valid_image_ids)]
print("shape of filtered_data: ", filtered_data.shape)
train = (
    filtered_data.sort_values(by=['image_id','funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(7)
)
print("shape of train: ", train.shape)
train.to_csv('../Data/Instagram/Only7_simCOCO_mcdonalds_switzerland.csv', index=False)

keep data with outDictCount = 0

In [ ]:
data = data[data['outDictCount'] == 0]
print(data.shape)
data.to_csv('../Data/Oxford_HIC/NoOutDict_oxford_hic_data.csv', index=False)

funny_score top n caption

In [ ]:
top_captions = (
    data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(10)
)
top_captions.shape
top_captions.to_csv('../Data/Oxford_HIC/NoOutDictTop10_oxford_hic_data.csv', index=False)

# Generate data

In [1]:
from string import punctuation
import pandas as pd
from sklearn.model_selection import train_test_split

dirPath = '../Data/Oxford_HIC/CaptionID_oxford_hic_data.csv'
# dirPath = '../Data/Oxford_HIC/Only10_oxford_hic_data.csv'

# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# dirPath = '../Data/Instagram/CaptionID_sonicdrivein.csv'

data = pd.read_csv(dirPath)
data['caption'] = data['caption'].str.lower()
data['fc_mean'] = data.groupby('image_id')['funny_score_y'].transform('mean')

In [3]:
data.shape

(5384, 6)

In [6]:
# data1 = pd.read_csv('../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1.csv')
# data = pd.read_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_bert_5384.csv')
from tqdm import tqdm
import torch
import ast
with tqdm(total=data.shape[0]) as pbar:
    for i in range(data.shape[0]):
        image_id = data.iloc[i]['image_id']
        emotion = torch.tensor(ast.literal_eval(data.iloc[i]['emotion']))
        torch.save(emotion, f"../../Oxford_HIC/ESH/bert_5384/emotion/{image_id}.pt")
        sentiment = torch.tensor(ast.literal_eval(data.iloc[i]['sentiment']))
        torch.save(emotion, f"../../Oxford_HIC/ESH/bert_5384/sentiment/{image_id}.pt")
        humor = torch.tensor(ast.literal_eval(data.iloc[i]['humor']))
        torch.save(emotion, f"../../Oxford_HIC/ESH/bert_5384/humor/{image_id}.pt")
        pbar.update(1)
    pbar.close()

100%|██████████| 5384/5384 [40:53<00:00,  2.19it/s]

In [4]:
data2 = data2.merge(data1, on='image_id', how='inner', suffixes=('', '_y'))
data2.shape

(1614900, 11)

In [9]:
print(data1.shape[0]/300, data2.shape)
print(len(set(data1['image_id']).union(set(data2['image_id']))))
print(len(set(data1['image_id']).intersection(set(data2['image_id']))))
print(len(set(data1['image_id']).difference(set(data2['image_id']))))
print(len(set(data2['image_id']).difference(set(data1['image_id']))))

5384.0 (6844, 5)
6618
4872
512
1234

In [16]:
temp = set(data1['image_id']).difference(set(data2['image_id']))
temp = list(temp)
new_df = pd.DataFrame()
new_df['image_id'] =temp

In [18]:
new_df['chat']=''
new_df['done']='X'
new_df['emotion']=''
new_df['sentiment']=''
new_df['humor']=''
new_df

         image_id chat done emotion sentiment humor
0    bokete_97718         X
1    bokete_31245         X
2    bokete_50026         X
3    bokete_52147         X
4    bokete_30750         X
..            ...  ...  ...     ...       ...   ...
507  bokete_19732         X
508  bokete_36400         X
509  bokete_89532         X
510   imgflip_698         X
511  bokete_12223         X

[512 rows x 6 columns]

In [19]:
new_df.to_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_miss.csv')

In [73]:
onlyone = (
    data.sort_values(by=['image_id', 'fc_mean'], ascending=[True, False])
    .groupby('image_id')
    .head(1)
)
onlyone = onlyone.sort_values(by=['fc_mean'], ascending=[False])
had = pd.read_csv('../../Data/Oxford_HIC/Minigpt4_Oxford.csv')

print('onlyone: ', onlyone.shape)
print('had: ', had.shape)
onlyone_img = set(onlyone[:5000]['image_id'].tolist())
had_img = set(had['image_id'].tolist())
print('intersection: ', len(onlyone_img.intersection(had_img)))
print('difference: ', len(onlyone_img.difference(had_img)))
print('difference: ', len(had_img.difference(onlyone_img)))

In [83]:
onlyone_img.union()
newDF = pd.DataFrame(list(onlyone_img.union(had_img)), columns=['image_id'])
newDF.shape
# sentence = pd.read_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford.csv')
# newDF = newDF.merge(sentence, on='image_id', how='left', suffixes=('', '_y'))
# newDF[3750:].to_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_4.csv')
newDF['chat']=''
newDF['done'] = ''
newDF['emotion'] = ''
newDF['sentiment'] = ''
newDF['humor'] = ''
newDF[738:].to_csv('../Data/Oxford_HIC/Minigpt4_sentence_generate_Oxford_5.csv')

In [6]:
data = data.merge(newDF, on='image_id', how='inner', suffixes=('', '_y'))
image_id_counts = data['image_id'].value_counts()
print(len(image_id_counts))

5368

In [7]:
data['generated'] = 0

In [8]:
import pandas as pd
print("shape of data: ", data.shape)
print()
image_id_counts = data['image_id'].value_counts()
######################################################################################################
print(f'                  Oxford_HIC')
print(f'           Total image counts: {len(image_id_counts)}')
x = image_id_counts[image_id_counts >= 1000]
sum = len(x)
print(f' {1000} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 300]
# sum = len(x)
# print(f' {300} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 200]
# x = x[x < 300]
# sum += len(x)
# print(f'{200:4d} <= caption < {300:4d} --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 100]
# x = x[x < 200]
# sum += len(x)
# print(f'{100:4d} <= caption < {200:4d} --- {len(x):6d} --- {sum:6d}')
for i in range(10):
    x = image_id_counts[image_id_counts >= (10-1-i)*100]
    x = x[x < (10-i)*100]
    sum += len(x)
    print(f' {(10-1-i)*100:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')

shape of data:  (1562588, 8)

                  Oxford_HIC
           Total image counts: 5368
 1000 <= caption        ---    203 ---    203
  900 <= caption < 1000 ---     10 ---    213
  800 <= caption <  900 ---     11 ---    224
  700 <= caption <  800 ---     19 ---    243
  600 <= caption <  700 ---     23 ---    266
  500 <= caption <  600 ---     35 ---    301
  400 <= caption <  500 ---     41 ---    342
  300 <= caption <  400 ---     92 ---    434
  200 <= caption <  300 ---     30 ---    464
  100 <= caption <  200 ---     65 ---    529
    0 <= caption <  100 ---   4839 ---   5368

In [9]:
import pandas as pd
import random
from nltk import sent_tokenize
import nltk
from tqdm import tqdm
from albumentations.core.transforms_interface import DualTransform, BasicTransform
import albumentations
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

class NLPTransform(BasicTransform):
    """ Transform for nlp task."""

    @property
    def targets(self):
        return {"data": self.apply}

    def update_params(self, params, **kwargs):
        if hasattr(self, "interpolation"):
            params["interpolation"] = self.interpolation
        if hasattr(self, "fill_value"):
            params["fill_value"] = self.fill_value
        return params

    def get_sentences(self, text, lang='en'):
        return sent_tokenize(text)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\TonyLab\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\TonyLab\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [10]:
import random
from nltk import sent_tokenize
import nltk
from tqdm import tqdm
from albumentations.core.transforms_interface import DualTransform, BasicTransform
from transformers import RobertaTokenizer,RobertaForMaskedLM
# from transformers import BertTokenizer, AutoTokenizer, RobertaTokenizer,BertForMaskedLM, RobertaForMaskedLM, AutoModelForMaskedLM
import albumentations
import torch
import re
import string

class LMmask(NLPTransform):

    def __init__(self, mask_num = 1, tokenizer_name='bert-base-uncased', model_name='bert-base-uncased'):
        self.punctuation = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~’'
        self.mask_num = mask_num
        if tokenizer_name == 'BertTokenizer':
            #   BertTokenizer + BertForMaskedLM  ==> 'bert-base-uncased'
            self.tokenizer = BertTokenizer.from_pretrained(model_name)
            self.model = BertForMaskedLM.from_pretrained(model_name)
            self.mask_token = self.tokenizer.mask_token
            self.mask_token_id = 103
        elif tokenizer_name == 'RobertaTokenizer':
            #   RobertaTokenizer + RobertaForMaskedLM  ==> 'FacebookAI/roberta-base'
            self.tokenizer = RobertaTokenizer.from_pretrained(model_name)
            self.model = RobertaForMaskedLM.from_pretrained(model_name)
            self.mask_token = self.tokenizer.mask_token
            self.mask_token_id = 50264
        elif tokenizer_name == 'AutoTokenizer':
            # AlbertConfig, BartConfig, BertConfig, BigBirdConfig, CamembertConfig, ConvBertConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, ElectraConfig, ErnieConfig, EsmConfig, FlaubertConfig, FNetConfig, FunnelConfig, IBertConfig, LayoutLMConfig, LongformerConfig, LukeConfig, MBartConfig, MegaConfig, MegatronBertConfig, MobileBertConfig, MPNetConfig, MraConfig, MvpConfig, NezhaConfig, NystromformerConfig, PerceiverConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, SqueezeBertConfig, TapasConfig, Wav2Vec2Config, XLMConfig, XLMRobertaConfig, XLMRobertaXLConfig, XmodConfig, YosoConfig.
            self.tokenizer = AutoTokenizer.from_pretrained(model_name)
            self.model = AutoModelForMaskedLM.from_pretrained(model_name)


            self.model.eval()
        for param in self.model.parameters():
            param.requires_grad = False

    def apply(self, data, top_k=10):
        new_text = []
        split = nltk.word_tokenize(data)
        for idx, n in enumerate(split):
            words = ''
            not_enough = False
            for i in range(self.mask_num):
                if idx + i >= len(split):
                    not_enough = True
                    break
                if split[idx + i] in self.punctuation:
                    words = words + split[idx + i]
                else:
                    words = words + ' ' + split[idx + i]
            if not_enough:
                continue
            words = re.sub(r'\s+', ' ', words)
            words = words.strip()
            token = self.tokenizer.encode(words, return_tensors="pt")
            single = token.shape[1] == self.mask_num + 2
            if single:
                text = ''
                words = nltk.word_tokenize(words)
                for idx_w, word_split in enumerate(split):
                    if word_split in words and idx_w in range(idx, idx + self.mask_num):
                        words.remove(word_split)
                        text = text + ' ' + self.mask_token
                    elif word_split in self.punctuation:
                        text = text + word_split
                    else:
                        text = text + ' ' + word_split
                text = re.sub(r'\s+', ' ', text)
                text = text.strip()
                # DEFINE SENTENCE
                indices = self.tokenizer.encode(text, add_special_tokens=True, return_tensors='pt')
                if torch.any(indices >= self.tokenizer.vocab_size):
                    raise ValueError("Input contains tokens out of vocabulary range.")
                # PREDICT MISSING WORDS
                pred = self.model(indices)
                masked_indices = torch.where(indices == self.mask_token_id)[1]
               # TOP 10 PREDICTIONS
                top10 = torch.topk(pred[0][0][masked_indices, :], top_k, axis=1)
                # FILL IN MISSING WORDS
                for i in range(top_k):
                    temp = text
                    for j in range(self.mask_num):
                        if j < top10.indices.shape[0] and i < top10.indices.shape[1]:
                            temp = temp.replace(self.mask_token, self.tokenizer.decode(top10.indices[j][i]), 1)
                    temp = re.sub(r'\s+', ' ', temp)
                    new_text.append(temp)
        return new_text

In [11]:
data.columns

Index(['Unnamed: 0', 'image_id', 'caption', 'funny_score_x', 'caption_id',
       'funny_score_y', 'fc_mean', 'generated'],
      dtype='object')

In [12]:
data

,Unnamed: 0,image_id,caption,funny_score_x,caption_id,funny_score_y,fc_mean,generated
0,2614,bokete_328,i wanted to blab on this subject for the last ...,0.000122,caption2615,12.0,20.916667,0
1,2621,bokete_328,a woman in a suit astride a lion... i have no ...,0.000000,caption2622,0.0,20.916667,0
2,2623,bokete_328,i'll... take... the... blood.,0.000020,caption2624,2.0,20.916667,0
3,2632,bokete_328,"if this is exposed, it will be worse than this.",0.000000,caption2633,0.0,20.916667,0
4,2656,bokete_328,the last shadow,0.000000,caption2657,0.0,20.916667,0
...,...,...,...,...,...,...,...,...
1562583,3270289,imgflip_2091,tries to become a downvote fairy feels bad bec...,0.000082,caption3241093,8.0,15.900000,0
1562584,3270290,imgflip_2091,farts out loud in public; forgives and doesn't...,0.000020,caption3241094,2.0,15.900000,0
1562585,3270291,imgflip_2091,i am on page 20 the last template on imgflip,0.000041,caption3241095,4.0,15.900000,0
1562586,3270292,imgflip_2091,very last template; is also the very worst,0.000010,caption3241096,1.0,15.900000,0
1562587,3270293,imgflip_2091,i'm trying too hard to be helpful; so recogniz...,0.000000,caption3241097,0.0,15.900000,0

In [13]:
data.drop(columns=['Unnamed: 0','caption_id'], inplace=True)

In [14]:
data = data.sort_values(by=['image_id', 'funny_score_y'], ascending=[True, False], ignore_index=True)
data

,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated
0,bokete_100087,i've got eyes on this place.,0.005288,519.0,11.500000,0
1,bokete_100087,you're gonna have to calm down.,0.000183,18.0,11.500000,0
2,bokete_100087,i really wanted to see it.,0.000153,15.0,11.500000,0
3,bokete_100087,"son, if this guy comes in on the train and tou...",0.000102,10.0,11.500000,0
4,bokete_100087,he was kind when he found out he had spent all...,0.000092,9.0,11.500000,0
...,...,...,...,...,...,...
1562583,imgflip_996,after you and your friend bids goodnight after...,0.000010,1.0,44.690909,0
1562584,imgflip_996,my balls; the rats in the kfc deep fryer,0.000010,1.0,44.690909,0
1562585,imgflip_996,what are you doing here? just looking for actu...,0.000000,0.0,44.690909,0
1562586,imgflip_996,"me playing super doomspire; captainspinxs, por...",0.000000,0.0,44.690909,0
1562587,imgflip_996,me on hypixel during virtual school; my teache...,0.000000,0.0,44.690909,0

In [15]:
img_id = data['image_id'].unique() #rl rr ll lr 2080
print(img_id[1000], data[data['image_id'] == img_id[1000]].index[0], data[data['image_id'] == img_id[1000]].index[-1])
print(img_id[2000], data[data['image_id'] == img_id[2000]].index[0], data[data['image_id'] == img_id[2000]].index[-1])
print(img_id[3000], data[data['image_id'] == img_id[3000]].index[0], data[data['image_id'] == img_id[3000]].index[-1])
print(img_id[4000], data[data['image_id'] == img_id[4000]].index[0], data[data['image_id'] == img_id[4000]].index[-1])
print(img_id[5000], data[data['image_id'] == img_id[5000]].index[0], data[data['image_id'] == img_id[5000]].index[-1])

bokete_13636 23664 23668
bokete_29473 37356 37379
bokete_44652 52888 52914
bokete_84062 66637 66651
imgflip_202 542381 543461

In [33]:
import pandas as pd
old = pd.read_csv(
    '../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1_rr.csv')
new = pd.read_csv('../Data/Oxford_HIC/Generate_bert_top5000_oxford_only1_rr10.csv')
mix = pd.concat([old, new], ignore_index=True)
mix.drop(columns=['Unnamed: 0'], inplace=True)
mix = mix.drop_duplicates()
print(old.shape, new.shape, mix.shape)
mix
mix.to_csv('../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1_rr.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../Data/Oxford_HIC/Generate_bert_top5000_oxford_only1_rr10.csv'

In [16]:
new_data = pd.read_csv(
    '../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1_rr.csv')
data[data['image_id'] == new_data.image_id.values[-1]].index

Index([32368, 32369, 32370, 32371, 32372], dtype='int64')

In [17]:
import os
fileNum = 'last'
if os.path.exists('../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1_rr.csv'):
    new_data = pd.read_csv('../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1_rr.csv')
    print(new_data.shape)
    done_img = len(new_data.image_id.unique())
    with tqdm(total=data.shape[0]) as progress_bar:
        progress_bar.update(365698)
        for i in range(data.shape[0]):
            i = i + 365698
            progress_bar.update()
            if data.image_id[i] in new_data.image_id.values:
                save_id = i
            else:
                break
        progress_bar.close()
else:
    save_id = 0
    done_img = 0
save = 0
print(f'save: {save}, save_id: {save_id}')
new_data = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
present = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
skip = None

with tqdm(total=data.shape[0]) as progress_bar:
    for i in range(data.shape[0]):
        progress_bar.update()
        if i <= save_id or i > 542381 :
            continue
        if skip != None:
            if data.image_id[i] == skip:
                continue
            else:
                skip = None
        if new_data.shape[0] // 900 > save:
            save = (new_data.shape[0] // 900)+1
            save_id = i
            new_data.to_csv(f'../Data/Oxford_HIC/Generate_bert_top5000_oxford_only1_rr_{fileNum}.csv', index=False)
            if new_data.shape[0] // 900 >= 60:
                done_img += len(new_data.image_id.unique())
                fileNum +=1
                save = 0
                new_data = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
        text = data.caption[i]
        split = text.split()
        if len(split) > 50:
            text = ''
            rest = ''
            for i in range(max(len(split[:50]), len(split[50:]))):
                if i < len(split[:50]):
                    text += ' ' + split[i]
                if i+50 < len(split):
                    rest += ' ' + split[i+50]
            text = text.strip()
            rest = rest.strip()
        image_id = data.image_id[i]
        funnyscore_x = data.funny_score_x[i]
        funnyscore_y = data.funny_score_y[i]
        fc_mean = data.fc_mean[i]
        generated = data.generated[i]
        present = pd.DataFrame([[image_id, text, funnyscore_x, funnyscore_y, fc_mean, 0]], columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
        generate_wordcount = len(nltk.word_tokenize(text)) - 5
        # print(f'image_id{image_id}, funnyscore{funnyscore}, generate_wordcount{generate_wordcount}, text{text}')
        if generate_wordcount > 0 and len(nltk.word_tokenize(text)) > 7:
            for j in range(min(generate_wordcount, 5)):
                # lm = LMmask(mask_num = i+1, tokenizer_name='BertTokenizer', model_name='bert-base-uncased')
                lm = LMmask(mask_num = j+1, tokenizer_name='RobertaTokenizer', model_name='FacebookAI/roberta-base')
                temp_sentences = lm.apply(text, top_k=5)
                for sentence in temp_sentences:
                    if len(split) > 50:
                        sentence += ' ' + rest
                    present = pd.concat([present, pd.DataFrame([[image_id, sentence, funnyscore_x, funnyscore_y, fc_mean, 1]], columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])], ignore_index=True)
                    present = present.drop_duplicates()
                    if present.shape[0] >= 300:
                        break
                progress_bar.set_postfix({"j": j, "k": len(temp_sentences),"img":len(new_data.image_id.unique())+done_img, "img_size": present.shape, "size": new_data.shape, "saveID": save_id})
                if present.shape[0] >= 300:
                    break
        if present.shape[0] >= 300:
             new_data = pd.concat([new_data, present], ignore_index=True)
             new_data = new_data.drop_duplicates()
             skip = data.image_id[i]
             progress_bar.set_postfix({"j": j, "k": len(temp_sentences),"img":len(new_data.image_id.unique())+done_img, "img_size": present.shape, "size": new_data.shape, "saveID": save_id})
new_data['caption'] = new_data['caption'].str.lower()
# remove duplicate data
new_data = new_data.drop_duplicates()
new_data.to_csv(f'../Data/Oxford_HIC/Generate_bert_top5000_oxford_only1_rr_{fileNum}.csv', index=False)

(179100, 7)

  2%|▏         | 32374/1562588 [00:00<?, ?it/s]

save: 0, save_id: 32372

  2%|▏         | 32378/1562588 [00:23<14:13, 1792.65it/s, j=2, k=135, img=572, img_size=(300, 6), size=(0, 6), saveID=32372]C:\Users\TonyLab\AppData\Local\Temp\ipykernel_14436\2392726851.py:82: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat([new_data, present], ignore_index=True)
  2%|▏         | 35620/1562588 [1:16:42<887:25:29,  2.09s/it, j=3, k=80, img=737, img_size=(300, 6), size=(0, 6), saveID=35598]      C:\Users\TonyLab\AppData\Local\Temp\ipykernel_14436\2392726851.py:82: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat([new_data, present], ignore_index=True)
100%|██████████| 1562588/1562588 [2:04:08<00:00, 209.80it/s, j=4, k=20, img=797, img_size=(180, 6), size=(19200, 6), saveID=37266]

In [68]:
import pandas as pd
old = pd.read_csv('../../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1.csv')
new = pd.read_csv(
    '../Data/Oxford_HIC/Generate_bert_oringinal/Generate_bert_top5000_only1/Generate_bert_top5000_oxford_mix_only1_rr.csv')
old = old[old.columns[-6:]]
new = new[new.columns[-6:]]
mix = pd.concat([old, new], ignore_index=True)
mix = mix.drop_duplicates()
print(old.shape, new.shape, mix.shape)
mix
mix.to_csv('../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1.csv')

(1313102, 6) (236700, 6) (1313102, 6)

In [71]:
import pandas as pd
filepath = '../../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1.csv'
data =  pd.read_csv(filepath)
image_id_counts = data['image_id'].value_counts()
valid_image_ids = image_id_counts[image_id_counts >= 300].index
print("shape of valid_image_ids: ", valid_image_ids.shape)
data = data[data['image_id'].isin(valid_image_ids)]
data = data.groupby('image_id').head(300)
image_id_counts = data['image_id'].value_counts()
# data.to_csv(filepath)
print("shape of data: ", data.shape)
print()
######################################################################################################
print(f'                  Oxford_HIC')
print(f'           Total image counts: {len(image_id_counts)}')
x = image_id_counts[image_id_counts >= 1000]
sum = len(x)
print(f' {1000} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 300]
# sum = len(x)
# print(f' {300} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 200]
# x = x[x < 300]
# sum += len(x)
# print(f'{200:4d} <= caption < {300:4d} --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 100]
# x = x[x < 200]
# sum += len(x)
# print(f'{100:4d} <= caption < {200:4d} --- {len(x):6d} --- {sum:6d}')
for i in range(10):
    x = image_id_counts[image_id_counts >= (10-1-i)*100]
    x = x[x < (10-i)*100]
    sum += len(x)
    print(f' {(10-1-i)*100:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')

shape of valid_image_ids:  (4361,)
shape of data:  (1308300, 7)

                  Oxford_HIC
           Total image counts: 4361
 1000 <= caption        ---      0 ---      0
  900 <= caption < 1000 ---      0 ---      0
  800 <= caption <  900 ---      0 ---      0
  700 <= caption <  800 ---      0 ---      0
  600 <= caption <  700 ---      0 ---      0
  500 <= caption <  600 ---      0 ---      0
  400 <= caption <  500 ---      0 ---      0
  300 <= caption <  400 ---   4361 ---   4361
  200 <= caption <  300 ---      0 ---   4361
  100 <= caption <  200 ---      0 ---   4361
    0 <= caption <  100 ---      0 ---   4361

In [25]:
import pandas as pd
data =  pd.read_csv('../Data/Oxford_HIC/Generate_bert_top5000_oxford_mix_only1_r.csv')
print("shape of data: ", data.shape)
print()
image_id_counts = data['image_id'].value_counts()
######################################################################################################
print(f'                  Oxford_HIC')
print(f'           Total image counts: {len(image_id_counts)}')
x = image_id_counts[image_id_counts >= 1000]
sum = len(x)
print(f' {1000} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 300]
# sum = len(x)
# print(f' {300} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 200]
# x = x[x < 300]
# sum += len(x)
# print(f'{200:4d} <= caption < {300:4d} --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 100]
# x = x[x < 200]
# sum += len(x)
# print(f'{100:4d} <= caption < {200:4d} --- {len(x):6d} --- {sum:6d}')
for i in range(10):
    x = image_id_counts[image_id_counts >= (10-1-i)*100]
    x = x[x < (10-i)*100]
    sum += len(x)
    print(f' {(10-1-i)*100:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')
data

shape of data:  (706800, 7)

                  Oxford_HIC
           Total image counts: 1281
 1000 <= caption        ---     85 ---     85
  900 <= caption < 1000 ---     91 ---    176
  800 <= caption <  900 ---      0 ---    176
  700 <= caption <  800 ---      0 ---    176
  600 <= caption <  700 ---    547 ---    723
  500 <= caption <  600 ---      0 ---    723
  400 <= caption <  500 ---      0 ---    723
  300 <= caption <  400 ---    558 ---   1281
  200 <= caption <  300 ---      0 ---   1281
  100 <= caption <  200 ---      0 ---   1281
    0 <= caption <  100 ---      0 ---   1281

,Unnamed: 0,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated
0,0,bokete_2232,and here i turn around and fire my pistol! hey...,0.00001,1.0,30.952381,0
1,1,bokete_2232,"So here i turn around and fire my pistol! hey,...",0.00001,1.0,30.952381,1
2,2,bokete_2232,"so here i turn around and fire my pistol! hey,...",0.00001,1.0,30.952381,1
3,3,bokete_2232,And here i turn around and fire my pistol! hey...,0.00001,1.0,30.952381,1
4,4,bokete_2232,and here i turn around and fire my pistol! hey...,0.00001,1.0,30.952381,1
...,...,...,...,...,...,...,...
706795,706795,imgflip_730,"once told a snowflake, if he ever saw it again...",0.00001,1.0,13.180909,1
706796,706796,imgflip_730,"once told a snowflake, if he ever saw it , , w...",0.00001,1.0,13.180909,1
706797,706797,imgflip_730,"once told a snowflake, if he ever saw it in wo...",0.00001,1.0,13.180909,1
706798,706798,imgflip_730,"once told a snowflake, if he ever saw it befor...",0.00001,1.0,13.180909,1
706799,706799,imgflip_730,"once told a snowflake, if he ever saw it anymo...",0.00001,1.0,13.180909,1

In [15]:
import os
if os.path.exists('../../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix.csv'):
    new_data = pd.read_csv('../../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix.csv')
    print(new_data.shape)
    with tqdm(total=data.shape[0]) as progress_bar:
        progress_bar.update(1480000)
        for i in range(data.shape[0]):
            i = i+1480000
            progress_bar.update()
            if data.image_id[i] in new_data.image_id.values:
                save_id = i
            else:
                break
        progress_bar.close()
else:
    save_id = 0
save = 0
print(f'save: {save}, save_id: {save_id}')
new_data = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
present = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
skip = None

with tqdm(total=data.shape[0]) as progress_bar:
    for i in range(data.shape[0]):
        if i <= save_id:
            progress_bar.update()
            continue
        progress_bar.update()
        if skip != None:
            if data.image_id[i] == skip:
                # progress_bar.set_postfix({"j": j, "k": len(temp_sentences),"img":data.image_id[i], "img_size": present.shape, "size": new_data.shape, "saveID": save_id})
                continue
            else:
                skip = None
        if new_data.shape[0] // 1000 > save:
            save = (new_data.shape[0] // 1000)+1
            save_id = i
            new_data.to_csv('../Data/Oxford_HIC/Generate_bert_top1000_oxford_10.csv', index=False)
        temp = data[data['image_id'] == data['image_id'][i]]
        if present.empty == False:
            temp = pd.concat([temp, present], ignore_index=True)
            temp = temp.drop_duplicates()
            if present.image_id[0] == data.image_id[i]:
                if temp.shape[0] > 800:
                    new_data = pd.concat([new_data, temp], ignore_index=True)
                    new_data = new_data.drop_duplicates()
                    present = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
                    skip = data.image_id[i]
                    progress_bar.set_postfix({"j": j, "k": len(temp_sentences),"img":data.image_id[i], "img_size": present.shape, "size": new_data.shape, "saveID": save_id})
                    continue
            else:
                new_data = pd.concat([new_data, temp], ignore_index=True)
                present = pd.DataFrame(columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
                progress_bar.set_postfix({"j": j, "k": len(temp_sentences),"img":data.image_id[i], "img_size": present.shape, "size": new_data.shape, "saveID": save_id})
        text = data.caption[i]
        image_id = data.image_id[i]
        funnyscore_x = data.funny_score_x[i]
        funnyscore_y = data.funny_score_y[i]
        fc_mean = data.fc_mean[i]
        generated = data.generated[i]
        generate_wordcount = len(nltk.word_tokenize(text)) - 3
        # print(f'image_id{image_id}, funnyscore{funnyscore}, generate_wordcount{generate_wordcount}, text{text}')
        if generate_wordcount > 0:
            for j in range(min(generate_wordcount, 5)):
                # lm = LMmask(mask_num = i+1, tokenizer_name='BertTokenizer', model_name='bert-base-uncased')
                lm = LMmask(mask_num = j+1, tokenizer_name='RobertaTokenizer', model_name='FacebookAI/roberta-base')
                temp_sentences = lm.apply(text, top_k=5)
                for sentence in temp_sentences:
                    if present.empty:
                        present = pd.DataFrame([[image_id, sentence, funnyscore_x, funnyscore_y, fc_mean, 1]], columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])
                    else:
                        present = pd.concat([present, pd.DataFrame([[image_id, sentence, funnyscore_x, funnyscore_y, fc_mean, 1]], columns=['image_id', 'caption', 'funny_score_x', 'funny_score_y', 'fc_mean', 'generated'])], ignore_index=True)
                progress_bar.set_postfix({"j": j, "k": len(temp_sentences),"img":data.image_id[i], "img_size": present.shape, "size": new_data.shape, "saveID": save_id})
new_data['caption'] = new_data['caption'].str.lower()
# remove duplicate data
new_data = new_data.drop_duplicates()

(4696323, 7)

 93%|█████████▎| 1376494/1484182 [00:59<00:04, 22980.80it/s]

save: 0, save_id: 1376492

 93%|█████████▎| 1376495/1484182 [00:08<00:00, 140610.16it/s, j=4, k=45, img=imgflip_315, img_size=(355, 6), size=(0, 6), saveID=1376492]  C:\Users\TonyLab\AppData\Local\Temp\ipykernel_11940\2360637038.py:45: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat([new_data, temp], ignore_index=True)
100%|██████████| 1484182/1484182 [52:54<00:00, 467.53it/s, j=4, k=25, img=imgflip_1824, img_size=(0, 6), size=(218792, 6), saveID=1483763]

In [16]:
new_data.to_csv('../Data/Oxford_HIC/Generate_bert_top1000_oxford_10.csv', index=False)

In [188]:
image_id_counts = new_data['caption'].value_counts()
image_id_counts

caption
bokete_654    271
Name: count, dtype: int64

In [120]:
import pandas as pd
new_data = pd.read_csv('../../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix.csv')
new_data.drop(columns=['Unnamed: 0'], inplace=True)
print(new_data.shape)
new_data.drop_duplicates(subset=['image_id', 'caption'], inplace=True)
print(new_data.shape)
image_id_counts = new_data['image_id'].value_counts()
new_data.to_csv('../Data/Oxford_HIC/Generate_bert_top1000_oxford_mix.csv', index=False)

(6397269, 6)
(4901254, 6)

In [115]:
valid_image_ids = image_id_counts[image_id_counts >= 800].index
filtered_data = new_data[new_data['image_id'].isin(valid_image_ids)]
print(f'Number of image_id with 800 captions: {len(valid_image_ids)}')
split = filtered_data.groupby('image_id').head(1)
train_img = set(split.sort_values(by=['fc_mean'], ascending=[False])[:1120].image_id.tolist())

valid_image_ids = image_id_counts[image_id_counts >= 300].index
filtered_data = new_data[new_data['image_id'].isin(valid_image_ids)]
print(f'Number of image_id with 300 captions: {len(valid_image_ids)}')
test_img = set(filtered_data.image_id.tolist()).difference(train_img)
print(len(train_img), len(test_img))

Number of image_id with 800 captions: 1322
Number of image_id with 300 captions: 1408
1120 288

In [116]:
train_data = filtered_data[filtered_data['image_id'].isin(train_img)]
test_data = filtered_data[filtered_data['image_id'].isin(test_img)]

In [117]:
origin_data = train_data[train_data['generated'] == 0]
origin_data

,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated
0,bokete_2176,"lowercase ""y"".",0.007244,711.0,69.727273,0
1,bokete_2176,"anpanman, new face!",0.000132,13.0,69.727273,0
2,bokete_2176,it's a driving shot!,0.000122,12.0,69.727273,0
3,bokete_2176,"if it's not moving, it's going to leak ...",0.000061,6.0,69.727273,0
4,bokete_2176,fracture of left ankle,0.000061,6.0,69.727273,0
...,...,...,...,...,...,...
4928581,bokete_91043,don't give up!,0.001691,166.0,25.428571,0
4928582,bokete_91043,"all right! if you save everything, you'll be a...",0.000051,5.0,25.428571,0
4928584,bokete_91043,"""don't save it, save it!""",0.000020,2.0,25.428571,0
4928585,bokete_91043,"i gave in to temptation and opened it, but tha...",0.000020,2.0,25.428571,0
4928587,bokete_91043,(in all 500 yen balls),0.000000,0.0,25.428571,0

In [118]:
def getData(data, total):
    origin_data = data[data['generated'] == 0]
    generate_data = data[data['generated'] == 1].sort_values(by=['image_id', 'funny_score_y'], ascending=[True, False])
    counter = origin_data.groupby('image_id').count()
    output = (
        origin_data.sort_values(by=['image_id', 'funny_score_y'], ascending=[True, False])
        .groupby('image_id')
        .head(total)
    )
    for img in counter.index:
        if total-counter['caption'][img] > 0:
            test = output[output['image_id'] == img]
            temp = generate_data[generate_data['image_id'] == img][:(total-counter['caption'][img])]
            if len(test)+len(temp) !=800:
                print(img,len(test), len(temp), total-counter['caption'][img],len(test)+len(temp) )
            output = pd.concat([output, temp], ignore_index=True)
    image_id_counts = output['image_id'].value_counts()
    print(f'Number of unique image_id: {len(image_id_counts)}')
    valid_image_ids = image_id_counts[image_id_counts == total].index
    print(f'Number of image_id with {total} captions: {len(valid_image_ids)}')
    return output

In [119]:
getData(train_data, 800)

Number of unique image_id: 1120
Number of image_id with 800 captions: 1120

,image_id,caption,funny_score_x,funny_score_y,fc_mean,generated
0,bokete_100219,listen to me. listen to me. it's a relief that...,1.000000,98148.0,1637.000000,0
1,bokete_100219,"that's not what ""use your feet"" means.",0.000306,30.0,1637.000000,0
2,bokete_100219,"""you know, don't give up your asthma every tim...",0.000082,8.0,1637.000000,0
3,bokete_100219,"hi, i'm your rival's father.",0.000051,5.0,1637.000000,0
4,bokete_100219,"""why are you wearing that?""",0.000041,4.0,1637.000000,0
...,...,...,...,...,...,...
895995,imgflip_996,my field trip to go the movies; my friend on a...,0.000041,4.0,44.690909,1
895996,imgflip_996,a friend wants to go the movies; my friend on ...,0.000041,4.0,44.690909,1
895997,imgflip_996,</s> a trips to go the movies; my friend on a ...,0.000041,4.0,44.690909,1
895998,imgflip_996,my school want to go the movies; my friend on ...,0.000041,4.0,44.690909,1
895999,imgflip_996,me 's excited to go the movies; my friend on a...,0.000041,4.0,44.690909,1

In [ ]:
# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# mcdonalds images: 9/306 , data = 2700/3654/29804
# mcdonalds_switzerland images: 262/1125 , data = 78600/110815/226667
# mcdonaldscanada images: 150/843 , data = 45000/86156/179124
# sonicdrivein images: 447/2208 , data = 134100/222368/460574
# wendys images: 14/367 , data = 4200/5846/35727
print(new_data.shape)
new_data.to_csv('../Data/Instagram/Generate_parrot_bert_sonicdrivein.csv', index=False)

In [55]:
import pandas as pd
print("shape of data: ", mix.shape)
print()
image_id_counts = mix['image_id'].value_counts()
######################################################################################################
print(f'                  Oxford_HIC')
print(f'           Total image counts: {len(image_id_counts)}')
x = image_id_counts[image_id_counts >= 1000]
sum = len(x)
print(f' {1000} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 300]
# sum = len(x)
# print(f' {300} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 200]
# x = x[x < 300]
# sum += len(x)
# print(f'{200:4d} <= caption < {300:4d} --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 100]
# x = x[x < 200]
# sum += len(x)
# print(f'{100:4d} <= caption < {200:4d} --- {len(x):6d} --- {sum:6d}')
for i in range(10):
    x = image_id_counts[image_id_counts >= (10-1-i)*100]
    x = x[x < (10-i)*100]
    sum += len(x)
    print(f' {(10-1-i)*100:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')

shape of data:  (6397269, 6)

                  Oxford_HIC
           Total image counts: 1432
 1000 <= caption        ---   1278 ---   1278
  900 <= caption < 1000 ---     34 ---   1312
  800 <= caption <  900 ---     27 ---   1339
  700 <= caption <  800 ---      9 ---   1348
  600 <= caption <  700 ---     18 ---   1366
  500 <= caption <  600 ---     19 ---   1385
  400 <= caption <  500 ---     15 ---   1400
  300 <= caption <  400 ---     10 ---   1410
  200 <= caption <  300 ---     13 ---   1423
  100 <= caption <  200 ---      2 ---   1425
    0 <= caption <  100 ---      7 ---   1432

# Generate data not in dictionary

In [ ]:
from string import punctuation
import pandas as pd
from sklearn.model_selection import train_test_split

# dirPath = '../Data/Oxford_HIC/CaptionID_oxford_hic_data.csv'
# dirPath = '../Data/Oxford_HIC/Only10_oxford_hic_data.csv'

# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
dirPath = '../Data/Instagram/CaptionID_wendys.csv'

data = pd.read_csv(dirPath)

In [ ]:
# lower caption
data['caption'] = data['caption'].str.lower()

In [ ]:
import pandas as pd
import random
from nltk import sent_tokenize
import nltk
from tqdm import tqdm
from albumentations.core.transforms_interface import DualTransform, BasicTransform
import albumentations
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

class NLPTransform(BasicTransform):
    """ Transform for nlp task."""

    @property
    def targets(self):
        return {"data": self.apply}

    def update_params(self, params, **kwargs):
        if hasattr(self, "interpolation"):
            params["interpolation"] = self.interpolation
        if hasattr(self, "fill_value"):
            params["fill_value"] = self.fill_value
        return params

    def get_sentences(self, text, lang='en'):
        return sent_tokenize(text)

In [ ]:
import random
from nltk import sent_tokenize
import nltk
from tqdm import tqdm
from albumentations.core.transforms_interface import DualTransform, BasicTransform
from transformers import BertTokenizer, AutoTokenizer, RobertaTokenizer,BertForMaskedLM, RobertaForMaskedLM, AutoModelForMaskedLM
import albumentations
import torch
import re
import string

class LMmask(NLPTransform):

    def __init__(self, mask_num = 1, tokenizer_name='bert-base-uncased', model_name='bert-base-uncased'):
        self.punctuation = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~…“”–’'
        self.mask_num = mask_num
        if tokenizer_name == 'BertTokenizer':
            #   BertTokenizer + BertForMaskedLM  ==> 'bert-base-uncased'
            self.tokenizer = BertTokenizer.from_pretrained(model_name)
            self.model = BertForMaskedLM.from_pretrained(model_name)
            self.mask_token = self.tokenizer.mask_token
            self.mask_token_id = 103
        elif tokenizer_name == 'RobertaTokenizer':
            #   RobertaTokenizer + RobertaForMaskedLM  ==> 'FacebookAI/roberta-base'
            self.tokenizer = RobertaTokenizer.from_pretrained(model_name)
            self.model = RobertaForMaskedLM.from_pretrained(model_name)
            self.mask_token = self.tokenizer.mask_token
            self.mask_token_id = 50264
        elif tokenizer_name == 'AutoTokenizer':
            # AlbertConfig, BartConfig, BertConfig, BigBirdConfig, CamembertConfig, ConvBertConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, ElectraConfig, ErnieConfig, EsmConfig, FlaubertConfig, FNetConfig, FunnelConfig, IBertConfig, LayoutLMConfig, LongformerConfig, LukeConfig, MBartConfig, MegaConfig, MegatronBertConfig, MobileBertConfig, MPNetConfig, MraConfig, MvpConfig, NezhaConfig, NystromformerConfig, PerceiverConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, SqueezeBertConfig, TapasConfig, Wav2Vec2Config, XLMConfig, XLMRobertaConfig, XLMRobertaXLConfig, XmodConfig, YosoConfig.
            self.tokenizer = AutoTokenizer.from_pretrained(model_name)
            self.model = AutoModelForMaskedLM.from_pretrained(model_name)


            self.model.eval()
        for param in self.model.parameters():
            param.requires_grad = False

    def apply(self, data, top_k=10):
        new_text = []
        split = data.split()
        def generateINDICT(split, idx, former):
            n = split[idx]
            token = self.tokenizer.encode(n, return_tensors="pt")
            single = token.shape[1] == 3

            if not single:
                words = data.replace(n, self.mask_token, 1)
                # DEFINE SENTENCE
                indices = self.tokenizer.encode(words, add_special_tokens=True, return_tensors='pt')
                # PREDICT MISSING WORDS
                pred = self.model(indices)
                masked_indices = torch.where(indices == self.mask_token_id)[1]
                # TOP 10 PREDICTIONS
                top10 = torch.topk(pred[0][0][masked_indices, :], top_k, axis=1)
                # FILL IN MISSING WORDS
                for i in range(top_k):
                    temp = words
                    for j in range(self.mask_num):
                        if j < top10.indices.shape[0] and i < top10.indices.shape[1]:
                            temp = temp.replace(self.mask_token, self.tokenizer.decode(top10.indices[j][i]), 1)
                    temp = re.sub(r'\s+', ' ', temp)
                    if idx + 1 < len(split):
                        generateINDICT(split, idx + 1, former)
                    else:
                        new_text.append(temp)
            else:
                if idx + 1 < len(split):
                    generateINDICT(split, idx + 1, former)
                else:
                    new_text.append(former)
        generateINDICT(split, 0, data)
        return new_text

In [ ]:
words_not_in_dict = []
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
for i in range(data.shape[0]):
    text = data.caption[i]
    # remove punctuation
    text = text.translate(str.maketrans('', '', '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~…“”–’'))
    #lowercase
    text = text.lower()
    split = text.split()
    for word in split:
        single = tokenizer.encode(word, return_tensors="pt").shape[1] == 3
        # check if word is number
        number = False
        try:
            int(word)
            number = True
        except:
            pass
        if not single and not number:
            words_not_in_dict.append(word)

In [ ]:
words_not_in_dict = set(words_not_in_dict)
print(len(words_not_in_dict))
words_not_in_dict

In [ ]:
temp = tokenizer.encode('lol', return_tensors="pt")
for i in range(temp.shape[1]):
    print(f'{i}: {tokenizer.decode(temp[0][i])}')
# tokenizer.decode(101)

In [ ]:
# complete following code
new_data = pd.DataFrame(columns=['caption', 'image_id', 'funny_score'])

with tqdm(total=data.shape[0]) as progress_bar:
    for i in range(data.shape[0]):
        text = data.caption[i]
        image_id = data.image_id[i]
        funnyscore = data.funny_score[i]
        new_data = pd.concat([new_data, pd.DataFrame([[text, image_id, funnyscore]], columns=['caption', 'image_id', 'funny_score'])], ignore_index=True)
        generate_wordcount = len(nltk.word_tokenize(text)) - 3
        # print(f'image_id{image_id}, funnyscore{funnyscore}, generate_wordcount{generate_wordcount}, text{text}')
        if generate_wordcount > 0:
            for j in range(min(generate_wordcount, 1)):
                # lm = LMmask(mask_num = i+1, tokenizer_name='BertTokenizer', model_name='bert-base-uncased')
                lm = LMmask(mask_num = j+1, tokenizer_name='RobertaTokenizer', model_name='FacebookAI/roberta-base')
                temp_sentences = lm.apply(text, top_k=5)

                for sentence in temp_sentences:
                    new_data = pd.concat([new_data, pd.DataFrame([[sentence, image_id, funnyscore]], columns=['caption', 'image_id', 'funny_score'])], ignore_index=True)
                progress_bar.set_postfix({"j": j, "k": len(temp_sentences), "size": new_data.shape})
        progress_bar.update()
new_data['caption'] = new_data['caption'].str.lower()
# remove duplicate data
new_data = new_data.drop_duplicates()

In [ ]:
new_data

In [ ]:
# 計算每個 image_id 的資料數量
image_id_counts = new_data['image_id'].value_counts()
print(f'Number of unique image_id: {len(image_id_counts)}')
# 篩選出有 1000 條以上資料的 image_id
valid_image_ids = image_id_counts[image_id_counts >= 300].index
print(f'Number of image_id with 300 captions: {len(valid_image_ids)}')
# 篩選原始資料
filtered_data = new_data[new_data['image_id'].isin(valid_image_ids)]
print(f'Number of data: {filtered_data.shape[0]}')
top_captions = (
    filtered_data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(300)
)
print(f'Number of data: {top_captions.shape[0]}')

In [ ]:
# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# mcdonalds_switzerland images: 262/1125 , data = 78600/110815/226667
print(new_data.shape)
new_data.to_csv('../Data/Instagram/Generate_mcdonalds_switzerland.csv', index=False)# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
# mcdonalds_switzerland images: 262/1125 , data = 78600/110815/226667
print(new_data.shape)
new_data.to_csv('../Data/Instagram/Generate_mcdonalds_switzerland.csv', index=False)

# Check distribution of how many captions in each image

In [ ]:
import pandas as pd
# ff_list=['mcdonalds', 'mcdonalds_switzerland', 'mcdonaldscanada', 'sonicdrivein','wendys']
name = 'wendys'
fileName = 'Generate_' + name
dirPath = '../Data/Instagram/' + fileName + '.csv'
data = pd.read_csv(dirPath)
print("shape of data: ", data.shape)
print()
image_id_counts = data['image_id'].value_counts()
######################################################################################################
print(f'          {fileName}')
print(f'           Total image counts: {len(image_id_counts)}')
x = image_id_counts[image_id_counts >= 1000]
sum = len(x)
print(f' {1000} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 300]
# sum = len(x)
# print(f' {300} <= caption        --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 200]
# x = x[x < 300]
# sum += len(x)
# print(f'{200:4d} <= caption < {300:4d} --- {len(x):6d} --- {sum:6d}')
# x = image_id_counts[image_id_counts >= 100]
# x = x[x < 200]
# sum += len(x)
# print(f'{100:4d} <= caption < {200:4d} --- {len(x):6d} --- {sum:6d}')
for i in range(10):
    x = image_id_counts[image_id_counts >= (10-1-i)*100]
    x = x[x < (10-i)*100]
    sum += len(x)
    print(f' {(10-1-i)*100:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')

#########################################

In [ ]:
text = "You can’t achieve strawberry lemonade until you first get strawberry lemonade followed by strawberry lemonade."
new_data = pd.DataFrame()
for i in range(3):
    # lm = LMmask(mask_num = i+1, tokenizer_name='BertTokenizer', model_name='bert-base-uncased')
    lm = LMmask(mask_num = i+1, tokenizer_name='RobertaTokenizer', model_name='FacebookAI/roberta-base')
# lm = LMmask(mask_num = 1, tokenizer_name='AutoTokenizer', model_name='')
    # 'DataFrame' object has no attribute 'append'

    new_data = pd.concat([new_data, pd.DataFrame(lm.apply(text, top_k=5))], ignore_index=True)
    new_data = pd.concat([new_data, pd.DataFrame(["============================================================="])], ignore_index=True)
new_data
# lm = LMmask(mask_num = 1, tokenizer_name='BertTokenizer', model_name='bert-base-uncased')
# lm.apply(text, top_k=5)

In [ ]:
new_data.to_csv('./roberta2.csv', index=False)

In [ ]:
from transformers import AutoConfig, AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
tokenizer.decode(2226)

In [ ]:
import string
from torch.utils.data import Dataset, DataLoader
import clip
import os
import pandas as pd
import pickle
from torch import nn
import numpy as np
import torch
import torch.nn.functional as nnf
import sys
from typing import Tuple, List, Union, Optional
from transformers import (
    GPT2Tokenizer,
    GPT2LMHeadModel,
    AdamW,
    get_linear_schedule_with_warmup,
)
from transformers import AutoConfig, AutoTokenizer, Gemma2ForCausalLM
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, TaskType, get_peft_model
import PIL.Image
from tqdm import tqdm
tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
inwordList = set()
outwordList = set()
progress_counter = tqdm(total=len(data), desc='Counting tokens', position=0, leave=True)
progress_inDict = tqdm(total=len(data), desc='Counting in dict', position=0, leave=True)
def token_counter(caption):
    caption = caption.lower()
    caption = caption.translate(str.maketrans('', '', string.punctuation))
    words = caption.split()
    temp = set(words)
    progress_counter.update(1)
    return len(temp)

def word_in_dict(caption):
    # caption = caption.lower()
    caption = caption.translate(str.maketrans('', '', string.punctuation))
    words = caption.split()
    temp = set(words)
    notTested = temp.difference(inwordList).difference(outwordList)
    notInDictCounter = len(temp.intersection(outwordList))
    # print(f'notInDictCounter: {notInDictCounter}, notTested: {notTested}')
    for word in notTested:
        token = tokenizer(word, return_tensors="pt").input_ids
        # print(f'word: {word}, token: {token}')
        if token.shape[1] == 1:
            inwordList.add(word)
        else:
            notInDictCounter += 1
            outwordList.add(word)
    # progress_inDict.update(1)
    return notInDictCounter

In [ ]:
train, test = train_test_split(data, test_size=0.2, random_state=42)

In [ ]:
# 計算每個 caption 的字數
data['token_count'] = data['caption'].apply(token_counter)
progress_counter.close()
# 計算每個 caption 中不在字典內的字數
data['out_of_dict_count'] = data['caption'].apply(word_in_dict)
progress_inDict.close()
print(f'Number of unique words in the dictionary: {len(inwordList)}')
print(f'Number of unique words out of the dictionary: {len(outwordList)}')

In [ ]:
test_tokens = inwordList.union(outwordList)

In [ ]:
train_tokens = inwordList.union(outwordList)

In [ ]:
a = set(test_tokens)
b = set(train_tokens)
c = set()
d = set()
for testDatasetToken in a:
    c.add(testDatasetToken.item())
print(len(c))
for testDatasetToken in b:
    d.add(testDatasetToken.item())
print(len(d))
print(len(c.symmetric_difference(d)))
print(len(c.intersection(d)))

In [ ]:
print(data.shape)
print(data[data['out_of_dict_count'] < 4].shape)
print(data[data['out_of_dict_count'] < 3].shape)
print(data[data['out_of_dict_count'] < 2].shape)
print(data[data['out_of_dict_count'] < 1].shape)
print(data[data['out_of_dict_count'] < 0].shape)
data.describe()

In [ ]:
data = data[data['out_of_dict_count'] < 1]

In [ ]:
# 計算每個 image_id 的資料數量
image_id_counts = data['image_id'].value_counts()
# 篩選出有 1000 條以上資料的 image_id
valid_image_ids = image_id_counts[image_id_counts >= 1000].index
# 篩選原始資料
filtered_data = data[data['image_id'].isin(valid_image_ids)]
print(len(valid_image_ids))
top_captions = (
    filtered_data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(1000)
)
print(top_captions.shape)
print(filtered_data.shape)

In [ ]:
print(f'          Total image counts: {len(image_id_counts)}')
x = image_id_counts[image_id_counts >= 1000]
sum = len(x)
print(f' {1000} <= caption        --- {len(x):6d} --- {sum:6d}')
for i in range(10):

    if i == 9:
        x = image_id_counts[image_id_counts >= 50]
        x = x[x < (10-i)*100]
        sum += len(x)
        print(f' {50:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')
        x = image_id_counts[image_id_counts >= 10]
        x = x[x < 50]
        sum += len(x)
        print(f' {10:4d} <= caption < {50:4d} --- {len(x):6d} --- {sum:6d}')
        x = image_id_counts[image_id_counts < 10]
        sum += len(x)
        print(f' {(10-1-i)*100:4d} <= caption < {10:4d} --- {len(x):6d} --- {sum:6d}')
    else:
        x = image_id_counts[image_id_counts >= (10-1-i)*100]
        x = x[x < (10-i)*100]
        sum += len(x)
        print(f' {(10-1-i)*100:4d} <= caption < {(10-i)*100:4d} --- {len(x):6d} --- {sum:6d}')

In [ ]:
# get data differ from data_all and data1500
print(data.shape)
print(filtered_data.shape)
exceptdata = data[~data['image_id'].isin(filtered_data['image_id'])]
print(len(exceptdata['image_id'].value_counts()))
print(exceptdata.shape)
exceptdata.to_csv('../Data/Oxford_HIC/except1000up_oxford_hic_data.csv', index=False)

In [ ]:
filtered_data.to_csv('../Data/Oxford_HIC/1000up_oxford_hic_data.csv', index=False)

In [ ]:
top_captions = (
    filtered_data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(1)
)
top_captions.shape
top_captions.to_csv('../Data/Oxford_HIC/Only10_oxford_hic_data.csv', index=False)

In [ ]:
top_captions.to_csv('../Data/Oxford_HIC/Only10_oxford_hic_data.csv', index=False)

In [ ]:
whole = pd.read_csv('../../Data/Oxford_HIC/Only10_oxford_hic_data.csv')
unique_image_ids = whole['image_id'].unique()

train_ids, test_ids = train_test_split(unique_image_ids, test_size=0.2, random_state=42)
train = whole[whole['image_id'].isin(train_ids)]
test = whole[whole['image_id'].isin(test_ids)]
print(train.shape, test.shape)

In [ ]:
train_mess = pd.DataFrame()
test_mess = pd.DataFrame()
for image_id, group in whole.groupby("image_id"):
    train_split, test_split = train_test_split(group, test_size=0.2, random_state=42)
    train_mess = pd.concat([train_mess, train_split])
    test_mess = pd.concat([test_mess, test_split])
print(f'train: {train_mess.shape}')
print(f'test: {test_mess.shape}')

In [ ]:
train_image = ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504']
train_data = train[train['image_id'].isin(train_image)]
test_image = ['bokete_100174', 'imgflip_834']
test_data = test[test['image_id'].isin(test_image)]
print(train_data.shape, test_data.shape)
train_data.to_csv('../Data/Oxford_HIC/Train_Only10_oxford_hic_data.csv', index=False)
test_data.to_csv('../Data/Oxford_HIC/Test_Only10_oxford_hic_data.csv', index=False)

In [ ]:
train_image = ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504','bokete_100174', 'imgflip_834']
train_data_mess = train_mess[train_mess['image_id'].isin(train_image)]
test_image =  ['2spbgym', 'all-the-things', 'imgflip_0', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_504','bokete_100174', 'imgflip_834']
test_data_mess = test_mess[test_mess['image_id'].isin(test_image)]
print(train_data_mess.shape, test_data_mess.shape)
train_data.to_csv('../Data/Oxford_HIC/Train_Only10_mess_oxford_hic_data.csv', index=False)
test_data.to_csv('../Data/Oxford_HIC/Test_Only10_mess_oxford_hic_data.csv', index=False)

In [ ]:
train_data_mess

In [ ]:
# list same caption in train_data and test_data_mess
a = test_data[test_data['image_id'] == 'imgflip_130']
b = test_data_mess[test_data_mess['image_id'] == 'imgflip_130']
x = set(a['caption']).intersection(set(b['caption']))
for i in x:
    if '' in i:
        print(i)
# 2spbgym,climb a mountain? pff, i have wings...
# all-the-things,go to a pizza buffet eat all the pizza
# imgflip_0,12 dollars; 11 dollars with 1 dollar shipping
# imgflip_1033,I POUR MILK BEFORE CEREAL
# imgflip_11,ME WAITING FOR MY INTERNET TO RECONNECT
# imgflip_117,calling the teacher mom
# imgflip_16,IF SOMEONE DIES IN THE LIVING ROOM... IS IT STILL CALLED THE LIVING ROOM?
# imgflip_189,you; losing a few seconds of your life looking at this
# imgflip_23,me: gets up and starts clapping because the chiefs won; the guy who has been pushing my wheelchair for 10 years
# imgflip_504,THEY TOOK AWAY MY HAPPY MEAL I TOOK AWAY THEIR HAPPINESS

# i-love-coloring-kid,she started writing notes !!
# imgflip_130,WHEN YOUR FRIEND; DOSENT LIKE ROOT BEER

In [ ]:
a

In [ ]:
img_names = data['image_id'].unique()
len(img_names)

In [ ]:
top_captions = (
    data.sort_values(by=['image_id', 'funny_score'], ascending=[True, False])
    .groupby('image_id')
    .head(50)
)
top_captions.shape

In [ ]:
train_data = pd.DataFrame()
test_data = pd.DataFrame()
only = pd.DataFrame()
for image_id, group in top_captions.groupby("image_id"):
    if group.shape[0] < 50:
        continue
    only = pd.concat([only, group])
    # train, test = train_test_split(group, test_size=0.2, random_state=42)
    # train_data = pd.concat([train_data, train])
    # test_data = pd.concat([test_data, test])
print(only.shape)

In [ ]:
only.to_csv('../Data/Oxford_HIC/Only50_oxford_hic_data.csv', index=False)

In [ ]:
top_captions.to_csv('../Data/Oxford_HIC/Top10_oxford_hic_data.csv', index=False)

In [ ]:
# 獲取唯一的 image_id
unique_image_ids = top_captions['image_id'].unique()
print(unique_image_ids.shape)
# 將 image_id 拆分為 80% 訓練集和 20% 測試集
train_ids, test_ids = train_test_split(unique_image_ids, test_size=0.2, random_state=42)

# 根據拆分的 image_id 選取資料
train_data = top_captions[top_captions['image_id'].isin(train_ids)]
test_data = top_captions[top_captions['image_id'].isin(test_ids)]
print(train_data.shape, test_data.shape)

In [ ]:
unique_image_ids.shape[0]/3

In [ ]:
a = unique_image_ids[:30000]
print(a.shape)

In [ ]:
dirPath = '../Data/Oxford_HIC/Only1200_oxford_hic_data.csv'
data = pd.read_csv(dirPath)
print("shape of data: ", data.shape)
######################################################################################################
train = pd.DataFrame()
test = pd.DataFrame()
for image_id, group in data.groupby("image_id"):
    train_split, test_split = train_test_split(group, test_size=0.2, random_state=42)
    train = pd.concat([train, train_split])
    test = pd.concat([test, test_split])
print(f'train: {train.shape}')
print(f'test: {test.shape}')
######################################################################################################
# unique_image_ids = data['image_id'].unique()
# # unique_image_ids = unique_image_ids[:30000]
# # unique_image_ids, rest = train_test_split(unique_image_ids, test_size=0.7, random_state=42)
# # print(unique_image_ids.shape)
# train_ids, test_ids = train_test_split(unique_image_ids, test_size=0.2, random_state=42)
# train = data[data['image_id'].isin(train_ids)]
# test = data[data['image_id'].isin(test_ids)]
# print(train.shape, test.shape)

In [ ]:
train=train.reset_index()
test=test.reset_index()

In [ ]:



train_image = ['imgflip_0', 'imgflip_101', 'imgflip_1033','imgflip_11', 'imgflip_117', 'imgflip_16', 'imgflip_189','imgflip_23', 'imgflip_47', 'imgflip_504']
train_text = ['12 dollars; 11 dollars with 1 dollar shipping'
              ,'I HAD A GIRLFRIEND; AAAAAAND ITS GONE'
              ,'I POUR THE CEREAL AFTER I POUR THE MILK'
              ,'WAITING FOR MY PHONE TO GET  TO 100%'
              ,'You when you have over one test at school in a day'
              ,'IF SOMEONE WANTS TO KILL YOU; GO TO A LIVING ROOM'
              ,'you; eating 5 pounds of cheese; every day; your stomach'
              ,'Me:stands up to stretch my legs; The person who had been pushing my wheelchair for the last 26 years'
              ,'Me: Opens door for some fresh air; Everyone else in the submarine:'
              ,'THEY TOOK AWAY MY HAPPY MEAL I TOOK AWAY THEIR HAPPINESS']
# imgflip_130,WHEN YOU SEE PICS OF YOUR FRIENDS HANGING OUT; BUT YOU WEREN'T INVITED
# imgflip_659,When the teacher uses your voice recording on the homework as an example
test_image = ['imgflip_130', 'imgflip_659']
test_text = ['0 VIEWS 5 DISLIKES'
              ,'when the mobile game ad is so laggy that it crashes your game and you lose out on a reward:']

tokens_list = []
mask_list = []
prefix_list = []
train_gt = []
train_caption = dict()
train_image_id_list = []
# mess = set()
mess_a = set()
mess_b =set()
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("tiiuae/Falcon3-1B-Base")
print(train.shape)
for i in range(train.shape[0]):
    caption = train['caption'][i]
    image_id = train['image_id'][i]
    # if image_id == 'imgflip_117':#and 'GONE' in caption:
    #     notmess.add(caption)
    #     print(f"Image ID: {image_id}, Caption: {caption}")
# train_image = ['', 'imgflip_101', '','', 'imgflip_117', '', '','', '', '']


    if image_id in train_image and caption in train_text:
        print(f"Image ID: {image_id}, Caption: {caption}")
print("===================================================================================")
for i in range(test.shape[0]):
    caption = test['caption'][i]
    image_id = test['image_id'][i]
    if image_id == 'imgflip_130':#and 'GONE' in caption:
        mess_a.add(caption)
    if image_id == 'imgflip_659':
        mess_b.add(caption)
    if image_id in test_image and caption in test_text:
        print(f"Image ID: {image_id}, Caption: {caption}")

In [ ]:
set.intersection(notmess_b, mess_b)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neo-2.7B")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neo-2.7B")

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-1B")